### ISSUE TITLE
logstash not starting with init.d script

### ISSUE THREAD

**Issue by tfgm-bud** [spujadas/elk-docker#11]
With the docker hub version of the image, I'm having a problem getting logstash to start using the init.d script.  Seems to work fine launching from the command line with:

    /opt/logstash/bin/logstash agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log

Here's what's in the log files:

	root@460d0f13460f:/# cat /var/log/logstash/logstash.stdout
	(Prepend -J in front of these options when using 'jruby' command)

	root@460d0f13460f:/# cat /var/log/logstash/logstash.err
	WARNING: Default JAVA_OPTS will be overridden by the JAVA_OPTS defined in the environment. Environment JAVA_OPTS are -Djava.io.tmpdir=/opt/logstash
	Usage: java [-options] class [args...]
			   (to execute a class)
	   or  java [-options] -jar jarfile [args...]
			   (to execute a jar file)
	where options include:
		-d32          use a 32-bit data model if available
		-d64          use a 64-bit data model if available
		-server       to select the "server" VM
		-zero         to select the "zero" VM
		-jamvm        to select the "jamvm" VM
		-avian        to select the "avian" VM
		-dcevm        to select the "dcevm" VM
					  The default VM is server,
					  because you are running on a server-class machine.

		-cp <class search path of directories and zip/jar files>
		-classpath <class search path of directories and zip/jar files>
					  A : separated list of directories, JAR archives,
					  and ZIP archives to search for class files.
		-D<name>=<value>
					  set a system property
		-verbose:[class|gc|jni]
					  enable verbose output
		-version      print product version and exit
		-version:<value>
					  require the specified version to run
		-showversion  print product version and continue
		-jre-restrict-search | -no-jre-restrict-search
					  include/exclude user private JREs in the version search
		-? -help      print this help message
		-X            print help on non-standard options
		-ea[:<packagename>...|:<classname>]
		-enableassertions[:<packagename>...|:<classname>]
					  enable assertions with specified granularity
		-da[:<packagename>...|:<classname>]
		-disableassertions[:<packagename>...|:<classname>]
					  disable assertions with specified granularity
		-esa | -enablesystemassertions
					  enable system assertions
		-dsa | -disablesystemassertions
					  disable system assertions
		-agentlib:<libname>[=<options>]
					  load native agent library <libname>, e.g. -agentlib:hprof
					  see also, -agentlib:jdwp=help and -agentlib:hprof=help
		-agentpath:<pathname>[=<options>]
					  load native agent library by full pathname
		-javaagent:<jarpath>[=<options>]
					  load Java programming language agent, see java.lang.instrument
		-splash:<imagepath>
					  show splash screen with specified image
	See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.

I pulled/ran the image with:

	$ docker pull sebp/elk
	Using default tag: latest
	latest: Pulling from sebp/elk
	Digest: sha256:388c55c8451719aabd73d6f5e2e3e9d480f707238d958bd5ddb54ce4997b18dc
	Status: Image is up to date for sebp/elk:latest

	$ docker run --rm -p 5601:5601 -p 9200:9200 -p 5000:5000 -it --name elk sebp/elk
	 * Starting Elasticsearch Server                                       [OK]
	sysctl: setting key "vm.max_map_count": Read-only file system
	logstash started.

	waiting for Elasticsearch to be up (1/30)
	waiting for Elasticsearch to be up (2/30)

**Comment by spujadas** [comment]
Logstash doesn't seem to start when `JAVA_OPTS` is set (not only does it override the default `JAVA_OPTS` set by Logstash – hence the warning, which is normal – but it plainly and simply prevents Logstash from starting), so removed this environment variable and simply left `LS_JAVA_OPTS`, which appends options to Logstash's default `JAVA_OPTS`.

After some tests, now looks good to me, but let me know if it works for you.
