### ISSUE TITLE
Private key file's format pkcs8 for logstash key

### ISSUE THREAD

**Issue by philippbussche** [spujadas/elk-docker#112]
Hi there,
I was producing my own cert and key files for the images as advised in your description but logstash would not come up due to this problem/error message:
"Looks like you either have an invalid key or your private key was not in PKCS8 format."
I then made a PKCS8 file out of the one produced by the command from your description and that solved the issue.
I was using sebp/elk:es241_l240_k461
Thanks
Philipp

**Comment by spujadas** [comment]
Sorry, didn't get a chance to get back to you on this one earlier.

I believe that this [only happens with Logstash 2.4.x](https://github.com/elastic/logstash/issues/5865), earlier versions as well as version 5.x accept the default (PKCS#1) format.
I'm adding a word on this in the documentation.

Just to track it here (in case someone has the same issue), the command to convert a (default) private key file to PKCS#8 is:

    openssl pkcs8 -in logstash-beats.key -topk8 -nocrypt -out logstash-beats.p8

**Comment by strtwtsn** [comment]
I've tried changing my key to PKCS#8 format using the above command, and then changing my logstash config to point to the .p8 file, but I get the same error after restarting logstash.  What am I missing?

**Comment by spujadas** [comment]
@strtwtsn could you walk me through how you put the key in the container and changed the config file?
(Also I would strongly recommend using a recent version of the image, as version 2 of Logstash is now getting fairly old + many things have been corrected in the image since.)
