### ISSUE TITLE
Couln't start Elasticsearch by "docker run  -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk01 sebp/elk:latest"

### ISSUE THREAD

**Issue by xiaoxiaohui1209** [spujadas/elk-docker#113]
Hi,sebp~
I have pulled your latest sebp/elk image ,and then run "cocker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk01 sebp/elk" .But the elasticsearch could't been start. 
The log follows below. 
I'm looking for your help.
Thanks very much!
![bug](https://cloud.githubusercontent.com/assets/18656415/22818326/a8778986-efa7-11e6-998e-848749f6094c.png)

**Comment by xiaoxiaohui1209** [comment]
image tag :520

**Comment by kulevg** [comment]
Did you change system parameter vm.**max_map_count**?
My solution in CentOS7:
```
# sysctl -w vm.max_map_count=262144
262144
# docker run ...
```
See too [https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html)
