### ISSUE TITLE
logstash-beats.crt ERROR

### ISSUE THREAD

**Issue by busterbytes** [spujadas/elk-docker#114]
ELK-docker container up and running.
Installed Filebeat on Windows client, but when running
` PS C:\Program Files\Filebeat> .\filebeat.exe -c filebeat.yml -e -v`
connection does not occur, get error:
`single.go:140: ERR Connecting error publishing events (retrying): x509: certificate is valid for *, not <domainname used in filebeat.yml>`

**Comment by busterbytes** [comment]
Found partial solution here:
https://elk-docker.readthedocs.io/#security-considerations

**Comment by spujadas** [comment]
The directions provided in the documentation should have worked, so if they only partially solved the issue then I'm going to need more information: could you obfuscate the names as needed and tell me what the domain name of the ELK service is (as declared in your `filebeat.yml` file) and what domain name you generated the certificate for (as described in the documentation)?

**Comment by busterbytes** [comment]
Hi, thank you for responding.

I have this container installed in a VM. Inside that VM i ran this command:
```
sudo openssl req -x509 -batch -nodes -subj "/CN=vmname.domain.extension/" \
    -days 3650 -newkey rsa:2048 \
    -keyout private/logstash-beats.key -out certs/logstash-beats.crt
```
I then copied that into the container, and also copied it to the Beats client. 
I just confirmed that this certificate exists in the following places:

VM hosting docker:
/etc/pki/tls/certs/logstash-beats.crt

Inside ELK container:
/etc/pki/tls/certs/logstash-beats.crt

Inside Beats client machine:
/etc/pki/ssl/certs/logstash-beats.crt

And here is the (relevant) content of the filebeat.yml on the Beats client:
```
#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  hosts: ["vmname.domain.extension:5044"] 
  bulk_max_size: 1024

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: ["/etc/pki/ssl/certs/logstash-beats.crt"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
```

Thank you in advance for any help you could offer.

**Comment by spujadas** [comment]
Thanks for the updated error message:

> `single.go:140: ERR Connecting error publishing events (retrying): Get http://vmname.domain.extension:5044: read tcp 192.168.221.131:39454->10.0.40.105:5044: read: connection reset by peer`

Did you also copy the `logstash-beats.key` file to `/etc/pki/tls/private/logstash-beats.key`?

If you did, then you could you have a look at https://github.com/spujadas/elk-docker/issues/24#issuecomment-185049621 for more troubleshooting suggestions.

**Comment by busterbytes** [comment]
I did copy the key. It's in the VM and inside the container. 
I didn't need to restart anything in either of those places? 

I ran commands from beats client using openssl per #24 comment with the following results 

```
$> openssl s_client -connect vmname.domain.extension:5044
CONNECTED(00000003)
depth=0 CN = vmname.domain.extension
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = vmname.domain.extension
verify return:1
---
Certificate chain
 0 s:/CN=vmname.domain.extension
   i:/CN=vmname.domain.extension
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDBzCCAe+gAwIBAgIJAOJR3/zAAHkqMA0GCSqGSIb3DQEBCwUAMBoxGDAWBgNV
...
OFM8NUYJZ8lYxms=
-----END CERTIFICATE-----
subject=/CN=vmname.domain.extension
issuer=/CN=vmname.domain.extension
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1284 bytes and written 431 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: CC100D81FAB6A1F003948E0F50BE2566B58F7CB76425AF8E78BA9C319A5423D8
    Session-ID-ctx: 
    Master-Key: 3634D4148ED09C9714DCD8CE3732BE6BB2D86031147CADCAB27903B23000915B1FE71861BE54312D783412882BF1ED81
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1487863946
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---





$> openssl s_client -connect vmname.domain.extension:5044 -CAfile /etc/pki/ssl/certs/logstash-beats.crt 
CONNECTED(00000003)
depth=0 CN = vmname.domain.extension
verify return:1
---
Certificate chain
 0 s:/CN=vmname.domain.extension
   i:/CN=vmname.domain.extension
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDBzCCAe+gAwIBAgIJAOJR3/zAAHkqMA0GCSqGSIb3DQEBCwUAMBoxGDAWBgNV
...
...
...
OFM8NUYJZ8lYxms=
-----END CERTIFICATE-----
subject=/CN=vmname.domain.extension
issuer=/CN=vmname.domain.extension
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1284 bytes and written 431 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 13711B05281656E3C7EFD13F97B7FFA0971CFE47A4AD30744A6E96FA36637E38
    Session-ID-ctx: 
    Master-Key: 06F6BB66116F59971AA3FA212DE3FE78885046CD47AD14258705A981E45F7F6111FBC69D9C03289A5F2221CEACC0CA13
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1487863746
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

```

**Comment by busterbytes** [comment]
Running filebeat client in a windows 12 server, now getting this error:

2017/02/23 15:49:37.861155 single.go:140: ERR Connecting error publishing events (retrying): x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "vmname.domain.extension")

**Comment by spujadas** [comment]
Hmmm, very strange indeed... everything looks absolutely fine on the Logstash side of things: the proper certificate/key have been taken into account by Logstash (seems that `service logstash restart` wasn't needed in the container; and nothing is needed on the VM itself), and Logstash is listening for requests on a properly accessible port, so that would point towards a configuration issue on the Beats side of things, but 
Do Logstash's logs show anything suspicious (especially when Beats tries to connect)?
Also, could you try to disable SSL/TLS altogether (Filebeat and Logstash; you don't need to do anything on the VM itself) to try to narrow down the root cause?

**Comment by spujadas** [comment]
> `2017/02/23 15:49:37.861155 single.go:140: ERR Connecting error publishing events (retrying): x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "vmname.domain.extension")`

Don't have access to a Windows 12 server, but the `ssl.certificate_authorities: ["/etc/pki/ssl/certs/logstash-beats.crt"]` line in `filebeat.yml` is supposed to avoid this exact error.

Could you cross-check that you the Beats client has the exact same `logstash-beats.crt` file as Logstash?

**Comment by busterbytes** [comment]
I reuploaded the cert to the windows machine and added it to the Trusted Root Certificate Authorities. It seems to be working now, at least from Filebeats' perspective.

However, the logs it says it's writing are not showing up in Kibana. Do i need to refresh something or restart?

**Comment by spujadas** [comment]
Interesting, I didn't know that the Windows version of the Filebeat client relied on Microsoft's certificate store… will add a note on that in the documentation. Thanks for that.

As far Kibana and the logs not showing up are concerned, you don't need to restart/refresh anything if your Logstash/Elasticsearch is properly configured to process the logs you're pushing, and if you're using the right index pattern in Kibana (the base image only processes incoming syslog and nginx logs).
Best bet here is to look at the official documentation for guidance (and if needed to ask for help from the ELK community – who are much more knowledgeable than I am on this! – over at http://discuss.elastic.co/).

**Comment by busterbytes** [comment]
Thanks for your help!

**Comment by spujadas** [comment]
Afterthought as I was updating the documentation (it should have struck me much earlier!): in `filebeat.yml`, the `ssl.certificate_authorities: ["/etc/pki/ssl/certs/logstash-beats.crt"]` line must point to the path of the local `logstash-beats.crt` file on the Windows machine (so something like `c:/…`, with forward slashes).
(Installing the certificate in the trusted store also works, of course, as you pointed out.)

**Comment by busterbytes** [comment]
Additionally, the path needs double slashes \\ to escape characters, fyi.

**Comment by spujadas** [comment]
Cheers for that one!
