### ISSUE TITLE
How do I configure elasticsearch and logstash settings?

### ISSUE THREAD

**Issue by stonefury** [spujadas/elk-docker#119]
I have a LOT of incoming logs. I know how to configure the ES and logstash heap size, but after a month my elk stack breaks.  Elasticseach seems to be overwhelmed.

I wanted to try tuning logstash.yml or elasticsearch config file options so I can tweak the number of logstash workers, etc.. How do I modify these settings? I tried using -v to override the logstash.yml file but it didn't work.

**Comment by stonefury** [comment]
Oops, never mind I think I found it. I need to extend the docker image.

https://elk-docker.readthedocs.io/#building-image

**Comment by spujadas** [comment]
Indeed the documented solution is to extend the image, but

>  I tried using -v to override the logstash.yml file but it didn't work.

^ this should have worked (and in fact I'm considering adding a word on this in the documentation).

Could you tell me more about what you did and what happened or didn't happen?

**Comment by stonefury** [comment]
Sure!  Well, after running fine for a month, I log into Kibana and I get a RED status. If I try to restart the container or even re-create the container using the same data store, it will not recover.  

I believe it is a volume issue because I don't see this so far on my dev systems which handle a lot less logs.

I took a snapshot of my broken VM to debug later.  I'll get specific error messages and post.

thanks!
