### ISSUE TITLE
Unable to connect to Elasticsearch

### ISSUE THREAD

**Issue by kretsu** [spujadas/elk-docker#120]
sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk
 * Starting periodic command scheduler cron                                                                                                                                                                          [ OK ]
 * Starting Elasticsearch Server                                                                                                                                                                                            /etc/init.d/elasticsearch: line 136: [: : integer expression expected

....

==> /var/log/logstash/logstash-plain.log <==
[2017-03-08T11:00:18,673][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2017-03-08T11:00:18,677][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x58fe29dc URL:http://localhost:9200/>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}

==> /var/log/kibana/kibana5.log <==
{"type":"log","@timestamp":"2017-03-08T11:00:19Z","tags":["warning","elasticsearch","admin"],"pid":207,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2017-03-08T11:00:19Z","tags":["warning","elasticsearch","admin"],"pid":207,"message":"No living connections"}
{"type":"log","@timestamp":"2017-03-08T11:00:21Z","tags":["warning","elasticsearch","admin"],"pid":207,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2017-03-08T11:00:21Z","tags":["warning","elasticsearch","admin"],"pid":207,"message":"No living connections"}

from container:

root@4b37a7e44f39:/# service elasticsearch status
 * elasticsearch is not running

root@4b37a7e44f39:/# service elasticsearch start
 * Starting Elasticsearch Server                                                /etc/init.d/elasticsearch: line 136: [: : integer expression expected
                                                                         [ OK ]
root@4b37a7e44f39:/# service elasticsearch status
 * elasticsearch is running
root@4b37a7e44f39:/# service elasticsearch status
 * elasticsearch is not running

**Comment by spujadas** [comment]
Bug introduced by https://github.com/spujadas/elk-docker/commit/96a04bba3df2660206470aab3c611a8175a86063 :slightly_frowning_face: 

I'll fix this when I get the chance. In the meantime please use either the `elk:5.2.1` tag for the latest stable version, or (as a workaround) set the `MAX_MAP_COUNT` environment variable to e.g. the value in your host's `/proc/sys/vm/max_map_count`.

Note to self: remove test on `/proc/sys/vm/max_map_count` at https://github.com/spujadas/elk-docker/commit/96a04bba3df2660206470aab3c611a8175a86063#diff-077b4284a436d74bced2c8edcb663897L136

**Comment by kretsu** [comment]
And I think I found issue in my docker, memory size somehow reduced to the 2GB (after reset maybe). After I increased it to the 4Gb - started work fine.

**Comment by justinmchase** [comment]
I'm getting this error when attempting to use it on windows. What is the desired `MAX_MAP_COUNT` value?

**Comment by spujadas** [comment]
@justinmchase 262144 (http://elk-docker.readthedocs.io/#es-not-starting-max-map-count)

**Comment by justinmchase** [comment]
Thanks, it turns out the problem for me was memory. Docker was set at 2GB which wasn't enough and ES was silently crashing. Upped it to 4GB and boom, started working. Upping memory in the UI is virtually the same on Windows as on the Mac also.

**Comment by spujadas** [comment]
@justinmchase Ah yes, one of the usual suspects! Thanks for the update!
