### ISSUE TITLE
filebeat issues

### ISSUE THREAD

**Issue by choman** [spujadas/elk-docker#125]
I hope you can help me out here, and I'm not sure what I'm doing wrong, 

Caveat: I'm not a filebeat nor an elk guru.  but I am leaning as fast as I can.

So to start with I ran into cert issues with the default cert.  found enough documentation to 
regen them.  so I am sure everything is good there.  launching filebeat in debug does not 
produce any  error messages along the certs. 

Now I'm getting the following error
```
Failed to publish events caused by: write tcp 10.0.2.4:33822->10.0.2.15:5044: write: connection reset by peer
2017-03-25T12:55:33-05:00 INFO Error publishing events (retrying): write tcp 10.0.2.4:33822->10.0.2.15:5044: write: connection reset by peer
```
and most of the references to this I've seen online don't seem to fix it

My current setup is
- A VM running docker running elk inside a container.  
- A separate VM running filebeat to send logs to elk

**Comment by spujadas** [comment]
Unfortunately this is a generic situation that is hard to troubleshoot (hence a lot of references online that may or may not help), and that could be explained by a variety of things, usually:

- The VM at 10.0.2.4 can't connect to port 5044 of VM at 10.0.2.15: VM networking set-up, firewall rules, and a non-exposed port are possible culprits. In your case if you had certificate issues but are no longer having them, then I would rule out such connectivity issues (but do have a look at http://elk-docker.readthedocs.io/#logstash-unreachable just in case).

- Logstash isn't running for some reason. Again, on account of the previous point, I would assume that this isn't the explanation.

- Filebeat and Logstash are running different versions: are you using the same version of Beats as the version of the ELK image?

Also, are the logs showing anything on the Logstash side of things?

**Comment by choman** [comment]
I try and look at these today.  I know the first bullet should be OK.  but
i'll double check

Together We Win!   Looking for cloud storage, try pCloud
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67> (10g free
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67>)
--
Chad

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows

**Comment by choman** [comment]
So I know,
- filebeat version was off now they are the same
- nc -v <docker host> 5044 succeeds

Where should I see the log files on the logstash side

**Comment by spujadas** [comment]
>nc -v "docker host" 5044 succeeds

Yep, that would be the case regardless of whether Logstash is running or not, as Docker exposes the port.

Could you confirm that the SSL connection is established properly by running `openssl s_client -connect 10.0.2.15:5044 -CAfile logstash-beats.crt` on the host that you're running Filebeat on?

>Where should I see the log files on the logstash side, although I won't have anything base on the failed write from above

`/var/log/logstash`, but indeed it's unlikely to report anything if the messages aren't getting through.

>update: could this be ipv6 related?

I have literally zero experience using IPv6 with Docker, so I'm afraid I can't answer that one.
