### ISSUE TITLE
Can't recover from a crash

### ISSUE THREAD

**Issue by stonefury** [spujadas/elk-docker#126]
After about 3 weeks I nearly ran out of disk space. I had 1.8GB left on my disk, and elk stack crashed.

I fixed the disk issue but now I can't get the system back up.  The kibana control panel shows ES as red and:

Elasticsearch is still initializing the kibana index.

I've waited 15-20 mins but nothing.

`sudo docker run -p 4560:4560 -p 5601:5601 -d -p 9200:9200  -p 5044:5044 -p 5000:5000     -v /home/elasticsearch/elk-data-prod:/var/lib/elasticsearch --name elk-prod -v /root/elk-docker-overrides/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf -v /root/elk-docker-overrides/logback.conf:/etc/logstash/conf.d/logback.conf -e ES_HEAP_SIZE="16g" -e LS_HEAP_SIZE="16g" -e ES_JAVA_OPTS="-Xms4g -Xmx4g" sebp/elk`

logstash logs inside the container is throwing this stuff

`[2017-03-30T22:24:13,975][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch' but Elasticsearch appears to be unreachable or down! {:error_message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketTimeout] Read timed out", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :will_retry_in_seconds=>2}
[2017-03-30T22:24:15,978][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
[2017-03-30T22:24:15,979][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreachable or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>4}
[2017-03-30T22:24:16,805][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2017-03-30T22:24:16,826][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<URI::HTTP:0xebba0d8 URL:http://localhost:9200/>}
`

elasticsearch is showing this and nothing more.

> [2017-03-30T22:17:12,788][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: 8c:64:d2:e5:c8:d3:6e:25
> [2017-03-30T22:17:12,846][INFO ][o.e.t.TransportService   ] [9vll-E2] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
> [2017-03-30T22:17:12,853][INFO ][o.e.b.BootstrapChecks    ] [9vll-E2] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
> [2017-03-30T22:17:15,902][INFO ][o.e.c.s.ClusterService   ] [9vll-E2] new_master {9vll-E2}{9vll-E2uRYyXJOhd9klKxw}{hhCs8llbTCKcU_WCl68_jA}{172.17.0.2}{172.17.0.2:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
> [2017-03-30T22:17:15,921][INFO ][o.e.h.n.Netty4HttpServerTransport] [9vll-E2] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
> [2017-03-30T22:17:15,926][INFO ][o.e.n.Node               ] [9vll-E2] started
> [2017-03-30T22:17:23,239][INFO ][o.e.g.GatewayService     ] [9vll-E2] recovered [76] indices into cluster_state
> [2017-03-30T22:18:53,685][INFO ][o.e.c.m.MetaDataCreateIndexService] [9vll-E2] [prod-2017.03.29] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
> [2017-03-30T22:19:04,217][INFO ][o.e.c.m.MetaDataMappingService] [9vll-E2] [prod-2017.03.30/wP3lyUbtR0Si3Kt_YCSTbQ] update_mapping [jboss]
> [2017-03-30T22:22:22,992][INFO ][o.e.c.m.MetaDataMappingService] [9vll-E2] [logstash-2017.03.30/RNV6JZtZR-aKIzKEcswmaA] create_mapping [log]
> [2017-03-30T22:22:22,998][INFO ][o.e.c.m.MetaDataMappingService] [9vll-E2] [logstash-2017.03.30/RNV6JZtZR-aKIzKEcswmaA] create_mapping [jboss]
> 

From within the container
`root@e3dccaa572da:/var/log/elasticsearch# curl http://localhost:9200/_cluster/health
{"cluster_name":"elasticsearch","status":"red","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":263,"active_shards":263,"relocating_shards":0,"initializing_shards":4,"unassigned_shards":495,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":34.51443569553806}root@e3dccaa572da:/var/log/elasticsearch#`

Any ideas? I know if I deleted the data dir it of course will come up fine, but then I lose my history.

Sidenote (maybe useful maybe totally not) : I don't think the java options are working, since when I run top I see this. FYI;

.5 15.2   9:32.41 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -X

Thanks!

**Comment by stonefury** [comment]
This might have been just a regular out of disk issue, though the disk did have almost 2GB left.

I found a suggestion that fixed my problem though.

1) upgraded to latest docker image first off
2) curl -XDELETE http://localhost:9200/.kibana
3) stopped the container / deleted the container to start off fresh
4) start it back up...  It went from yellow to red but the red was a timeout issue...  I just waited awhile and ES came up. So a little tricky there because I thought I hit a new problem but turns out it was just churning away on something.

So if the data above doesn't seem like an issue with the docker image plesae close it.  I am curious about the java options though, why it seemed like they are not taking effect.

Thanks!

**Comment by spujadas** [comment]
Thanks for the detailed report!

> Sidenote (maybe useful maybe totally not) : I don't think the java options are working, since when I run top I see this.

They should be working, they're just overridden later in the command-line options, as shown in the full output:

	# ps aux | less -+S
	...
	elastic+   659 73.4 84.9 5804200 1740928 ?     Sl   05:36   0:19 /usr/bin/java -
	Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+
	UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server
	 -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io
	.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOp
	timization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookE
	nabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOut
	OfMemoryError -Xms4g -Xmx4g -Des.path.home=/opt/elasticsearch -cp /opt/elasticse
	arch/lib/elasticsearch-5.3.0.jar:/opt/elasticsearch/lib/* org.elasticsearch.boot
	strap.Elasticsearch -d -p /var/run/elasticsearch/elasticsearch.pid -Edefault.pat
	h.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefau
	lt.path.conf=/etc/elasticsearch

As for your issue, I have no idea, but it seems non-Docker-specific. May I suggest that you pop over to https://discuss.elastic.co/c/elasticsearch to ask for their thoughts. I'll leave this open in the meantime in case in turns out that it is related to this image after all.

**Comment by stonefury** [comment]
Don't think it was an image issue, just running out of disk space and corrupting some data. :) Sorry about that. Thanks!

**Comment by spujadas** [comment]
Thanks for the update!
Oh, and by the way you were right, the Java options didn't work (they do now), see #129.
