### ISSUE TITLE
Enhancement: MAX_OPEN_FILES should be adjustable over docker environment variables

### ISSUE THREAD

**Issue by giezi** [spujadas/elk-docker#131]
Hi there,

first thank you for the great docker image! We identified, that this docker image cannot be used out of the box on Jelastic (www.jelastic.com).

Jelastic rely on Virtuozzo / OpenVZ and converts the docker image into their format and there is an issue with MAX_OPEN_FILES. The default in Virtuozzo / OpenVZ containers is 4096 and ElasticSearch cannot be started:

<img width="1780" alt="jelastic-error" src="https://cloud.githubusercontent.com/assets/1326203/25120439/5a58e5a0-241e-11e7-82cc-b08401705c06.png">

```
Couln't start Elasticsearch. Exiting. 
...... 
max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
```

I've created a quick fix last week (https://github.com/giezi/elk-docker/commit/739c2bd9bb266e8e69b1404623ba3e040118054b) and the image is now able to start on Jelastic without any issues.

In my opinion, the most elegant option would be to have MAX_OPEN_FILES as an option in overriding-variables: http://elk-docker.readthedocs.io/#overriding-variables

What do you think about?

Many thanks and cheers
Reto

**Comment by spujadas** [comment]
Interesting, hadn't encountered that one before.
Anyway, having an env var for this sounds like the best way to fix the issue, I've just pushed a commit that implements this.
Leaving this open until you confirm that it's working on your side.

**Comment by giezi** [comment]
Hi Sébastien

Wow - many thanks! It works perfectly with specifying the following environment variable in Jelastic:

MAX_OPEN_FILES -> 65536

I will close the issue and again many thanks :)

Cheers
Reto
