### ISSUE TITLE
syslog is filling up quickly

### ISSUE THREAD

**Issue by giezi** [spujadas/elk-docker#133]
Hi Sébastien

I encountered a second problem, when we deploy elk-docker on Jelastic:
One logfile (/var/log/syslog) is growing very fast (about 0.5 GB per minute) with just these messages:

`Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: vdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runs
Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runsvdir-start[218]: vdir-start[218]: Apr 21 12:31:28 node44472-env-9901849 runs`

If you need a test-account in Jelastic to debug the issue, I can provide one for you.

Many thanks!

Cheers
Reto

**Comment by spujadas** [comment]
Interestingly, there's the exact same (and unresolved) issue [here](https://github.com/phusion/passenger-docker/issues/165) (and this is the only instance of the issue I've found), leading me to assume that the issue may be with the base image that sebp/elk extends (i.e. `phusion/baseimage`, see [`Dockerfile`](https://github.com/spujadas/elk-docker/blob/master/Dockerfile#L10)).

If you could provide me a Jelastic test account to see if I can reproduce you situation, that would be great... but do note that if it turns out that the issue is indeed due to the specific combination of `phusion/baseimage` and Jelastic, then unfortunately there won't be much I'll be able to do about it. :confused:

**Comment by giezi** [comment]
Hi Sébastien

Sure, feel free to signup here:
https://app.appengine.flow.ch/?lang=en&signup=true

If you need any assistance, just let me know :) Thanks!

Best regards
Reto

**Comment by spujadas** [comment]
Thanks for the link, reproduced the issue.

I _think_ it's an issue with Jelastic overriding the way the services are started in Docker containers (and https://github.com/docker-library/openjdk/issues/107 may be – somewhat – related, or at least helped me analyse the situation).
The `sebp/elk` image has (as per Docker best practices) its own startup script, that explicitly (and only) starts cron, Elasticsearch, Logstash, and Kibana. Jelastic appears to supplement this by (also) starting services meant for the init daemon, namely by (to the best of my understanding) processing `/etc/inittab`… which among other things, starts cron (and syslog-ng, and sshd apparently). This in turn means that cron gets started twice, and failing to create the lock file (`/var/run/crond.pid`) results in this being tried over and over again, overloading the CPU and writing to `/var/log/syslog` until the disk is full.

I suppose that Jelastic overrides the image's intended behaviour to add services that facilitate monitoring and whatnot, but I don't know how this is done exactly.

It's possible that commenting out this section of `/etc/inittab`

	#-- runit begin
	SV:123456:respawn:/usr/sbin/runsvdir-start
	#-- runit end

would stop Jelastic from starting services that aren't supposed to run, but it may have unintended side effects (for Jelastic)… and besides, it seems strange to change the image to comment out things in files that aren't supposed to be used…

If you have access to support from Jelastic it may be worth asking them for guidance on this specific issue (I had a look around at the documentation on their site, but didn't find anything on how images are "extended" by Jelastic to run additional services that may include unintended ones).

P.S. – Having said that there's something else I don't understand: using the base image `phphusion/baseimage` (which _does_ start the services using the `run` scripts in `/etc/service`, including one for cron – and again, this startup script is overriden by `sebp/elk`) fails in Jelastic with the exact same erratic behaviour:

	# ps aux | less -+S
	USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
	root         1  0.0  0.0  37144   600 ?        Ss   19:13   0:00 init -z
	root         2  0.0  0.0      0     0 ?        S    19:13   0:00 [kthreadd/45590]
	root         3  0.0  0.0      0     0 ?        S    19:13   0:00 [khelper]
	root        76 50.2  0.0  42968   952 ?        Rs   19:13   2:11 /lib/systemd/systemd-journald
	root        85  0.0  0.0  41688    88 ?        Ss   19:13   0:00 /lib/systemd/systemd-udevd
	root       304  0.0  0.0  29272   184 ?        Ss   19:13   0:00 /usr/sbin/cron -f
	root       306  0.0  0.0  72344   108 ?        Ss   19:13   0:00 /usr/sbin/syslog-ng -F
	root       308  0.0  0.0   4396    84 ?        Ss   19:13   0:00 runsvdir -P /etc/service log: source temporarily unavailable cron: can't lock /var/run/crond.pid, otherpid may be 304: Resource temporarily unavailable cron: can't lock /var/run/crond.pid, otherpid may be 304: Resource temporarily unavailable cron: can't lock /var/run/crond.pid, otherpid may be 304: Resource temporarily unavailable cron: can't lock /var/run/crond.pid, otherpid may be 304: Resource temporarily unavailable

**Comment by giezi** [comment]
Hi Sébastien

Thank you very much for your depth analysis - we really appreciate this.
I've opened a new case at Jelastic regarding the issue and will update you asap.

Best regards
Reto

**Comment by joelbernstein** [comment]
Hi guys, was there any progress on this? We are experiencing exactly the same issue on Jelastic 5.3 with sepb/elk

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
