### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by simbnb** [spujadas/elk-docker#136]
Hi
Do you have any idea about this problem? (5.4.0)

> elk_1  | {"type":"log","@timestamp":"2017-05-12T13:13:05Z","tags":["error","metrics","cgroup"],"pid":205,"level":"error","message":"EACCES: permission denied, open '/sys/fs/cgroup/cpuacct/docker/6d4cd2dd85f83d7587b6e923d2f7972781c4ece1e1d04b1b9258ae5552474575/cpuacct.usage'","error":{"message":"EACCES: permission denied, open '/sys/fs/cgroup/cpuacct/docker/6d4cd2dd85f83d7587b6e923d2f7972781c4ece1e1d04b1b9258ae5552474575/cpuacct.usage'","name":"Error","stack":"Error: EACCES: permission denied, open '/sys/fs/cgroup/cpuacct/docker/6d4cd2dd85f83d7587b6e923d2f7972781c4ece1e1d04b1b9258ae5552474575/cpuacct.usage'\n    at Error (native)","code":"EACCES"}}

Thank you

**Comment by spujadas** [comment]
Seems that Docker is having issues updating runtime metrics (https://docs.docker.com/engine/admin/runmetrics/), probably due to an improperly configured/installed Docker.
As this is very unlikely to be related to the ELK image, I would advise that you ask for guidance at https://forums.docker.com/
