### ISSUE TITLE
how to config "ssl_certificate_authorities" in logstash

### ISSUE THREAD

**Issue by lcnsir** [spujadas/elk-docker#137]
Hi spuiadas:

After read your doc, I can not find a way to config the full ssl configuration for logstash with beat.

refer to official doc: https://www.elastic.co/guide/en/beats/filebeat/5.1/configuring-ssl-logstash.html

we can config the ssl_certificate_authorities in logstash beat input, and config ssl_verify_mode and so on

input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate_authorities => ["/etc/ca.crt"]
    ssl_certificate => "/etc/server.crt"
    ssl_key => "/etc/server.key"
    ssl_verify_mode => "force_peer"
  }
}

from your doc, there are no way to set it all of them

we can run the commands to generate certs and key:
`openssl req -x509 -batch -nodes -subj "/CN=logstash" \
    -days 3650 -newkey rsa:2048 \
    -keyout private/logstash-beats.key -out certs/logstash-beats.crt`

for logstash 2.4.x we also need do
`$ openssl pkcs8 -in logstash-beats.key -topk8 -nocrypt -out logstash-beats.p8
`
will generate the crt and key,  then we need to config it to 
ssl_certificate  ---> logstash-beats.crt 
ssl_key ----> logstash-beats.p8

right?  so how we can config "ssl_certificate_authorities" and enable "ssl_verify_mode" to "force peer"

And for filebeat config "filebeat yaml" the full setting of ssl are
output.logstash:
  hosts: ["logs.mycompany.com:5044"]
  ssl.certificate_authorities: ["/etc/ca.crt"]
  ssl.certificate: "/etc/client.crt"
  ssl.key: "/etc/client.key"

 After we config ssl.certificate_authorities  --to--> logstash-beats.crt ?

How to config the ssl.key and ssl.certificate?

Thanks for your help

**Comment by spujadas** [comment]
> from your doc, there are no way to set it all of them

Correct, the documentation for the image only provides information for basic configuration, i.e. certificate-based server authentication, where only Logstash has a (self-signed server) certificate.
For more advanced situations, such as enabling certificate-based client authentication like you want to do, you should look into the official Elastic documentation.

> How to config the ssl.key and ssl.certificate?

As high-level guidance, you need to :

- Generate a private key and certificate for Filebeat, which you will use to populate `ssl.certificate` and `ssl.key` in `filebeat.yml`

- Configure `ssl_certificate_authorities` in Logstash to trust the certificate that was used to sign Filebeat's certificate (could be the same certificate as Filebeat's `ssl.certificate` if it is auto-signed, as is the case for Logstash in the default ELK image)

I won't go into more detail (and am therefore closing this issue) as issuing and managing certificates properly is a complex matter that is well outside of the remit of this image. Here are some extra pointers:

- For more information on issuing certificates, you may be interested in https://www.feistyduck.com/books/openssl-cookbook/

- More generally, as your questions are not specific to this ELK image, you may want to head over to https://discuss.elastic.co/ for help with your configuration

**Comment by Busindre** [comment]
Hi.

My little grain of sand: https://github.com/Busindre/How-to-configure-SSL-for-FileBeat-and-Logstash-step-by-step.
