### ISSUE TITLE
Error while building the image : gpg: no valid OpenPGP data found. gpg: the signature could not be verified.

### ISSUE THREAD

**Issue by Daggerlands** [spujadas/elk-docker#140]
Hello,

I'm trying to build the image by myself but I've come across an error.

> + mktemp -d
> + export GNUPGHOME=/tmp/tmp.BIwKxBnbPc
> + gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
> gpg: keyring `/tmp/tmp.BIwKxBnbPc/secring.gpg' created
> gpg: keyring `/tmp/tmp.BIwKxBnbPc/pubring.gpg' created
> gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
> gpg: /tmp/tmp.BIwKxBnbPc/trustdb.gpg: trustdb created
> gpg: key BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
> gpg: no ultimately trusted keys found
> gpg: Total number processed: 1
> gpg:               imported: 1  (RSA: 1)
> + gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu
> gpg: no valid OpenPGP data found.
> gpg: the signature could not be verified.
> Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.

Thus the building stops.

Any idea?

**Comment by spujadas** [comment]
Tried it on a fresh VM, no problem on my side:

	...
	+ dpkg --print-architecture
	+ curl -L -o /usr/local/bin/gosu https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	100   600    0   600    0     0    912      0 --:--:-- --:--:-- --:--:--   911
	100 1762k  100 1762k    0     0   241k      0  0:00:07  0:00:07 --:--:--  292k
	+ dpkg --print-architecture
	+ curl -L -o /usr/local/bin/gosu.asc https://github.com/tianon/gosu/releases/download/1.8/gosu-amd64.asc
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
	100   604    0   604    0     0    892      0 --:--:-- --:--:-- --:--:--   892
	100   543  100   543    0     0    426      0  0:00:01  0:00:01 --:--:--  5376
	+ mktemp -d
	+ export GNUPGHOME=/tmp/tmp.s0CxKS8N3t
	+ gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
	gpg: keyring `/tmp/tmp.s0CxKS8N3t/secring.gpg' created
	gpg: keyring `/tmp/tmp.s0CxKS8N3t/pubring.gpg' created
	gpg: requesting key BF357DD4 from hkp server ha.pool.sks-keyservers.net
	gpg: /tmp/tmp.s0CxKS8N3t/trustdb.gpg: trustdb created
	gpg: key BF357DD4: public key "Tianon Gravi <tianon@tianon.xyz>" imported
	gpg: no ultimately trusted keys found
	gpg: Total number processed: 1
	gpg:               imported: 1  (RSA: 1)
	+ gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu
	gpg: Signature made Tue 19 Apr 2016 04:58:39 PM UTC using RSA key ID BF357DD4
	gpg: Good signature from "Tianon Gravi <tianon@tianon.xyz>"
	gpg:                 aka "Tianon Gravi <tianon@debian.org>"
	gpg:                 aka "Tianon Gravi <tianon@dockerproject.org>"
	gpg:                 aka "Andrew Page (tianon) <andrew@infosiftr.com>"
	gpg:                 aka "Andrew Page (tianon) <andrew@vitalroute.com>"
	gpg:                 aka "Andrew Page (Tianon Gravi) <admwiggin@gmail.com>"
	gpg:                 aka "Tianon Gravi (Andrew Page) <tianon@infosiftr.com>"
	gpg: WARNING: This key is not certified with a trusted signature!
	gpg:          There is no indication that the signature belongs to the owner.
	Primary key fingerprint: B42F 6819 007F 00F8 8E36  4FD4 036A 9C25 BF35 7DD4
	+ rm -r /tmp/tmp.s0CxKS8N3t /usr/local/bin/gosu.asc
	+ chmod +x /usr/local/bin/gosu
	+ gosu nobody true
	...

On your side the error occurs when verifying the signature of the `gosu` tool. According to a similar issue reported for this tool (https://github.com/tianon/gosu/issues/31), this could be a local network (e.g. proxy, firewall) configuration issue... so nothing much I can do about this unfortunately, but it could point you in the right direction to investigate.
Leaving this open for now: if you do manage to troubleshoot this please let me know so that I can update the documentation to help other users encountering the same situation.

**Comment by Daggerlands** [comment]
Is gosu really necessary? What is it used for in the container?

**Comment by Daggerlands** [comment]
I cloned the repository and build it without changing anything and it actually works (I get no errors). So the problem comes from my Dockerfile.

**Comment by Daggerlands** [comment]
I found the error in my Dockerfile, it had nothing to do with my private network or anything. I still would like to know why gosu is used in this container.

**Comment by spujadas** [comment]
Generally speaking gosu is used as a replacement for su, which sometimes has issues when used in a container (see the gosu project page for further explanations). 
In this image in particular gosu is installed to enable users to install plugins using the Elasticsearch, Logstash, and Kibana user accounts (see https://elk-docker.readthedocs.io/#installing-elasticsearch-plugins and onwards).
