### ISSUE TITLE
Kibana starts showing data after a few hours.

### ISSUE THREAD

**Issue by Daggerlands** [spujadas/elk-docker#146]
I'm having a problem with Kibana. Elasticsearch is getting data (way enough data to show) but Kibana starts showing data only aftrer a few hours. Any idea?

**Comment by spujadas** [comment]
Nope, never encountered that situation. Are you using the default version of the image?
(I think it's very unlikely that this is due to ELK being containerised.)

**Comment by Daggerlands** [comment]
I'm using the defaut images yes.

**Comment by spujadas** [comment]
OK, could you walk me through how you set everything up, what's showing up in the logs, and anything that might be useful for me to replicate the issue?
Additionally could you go through all the steps outlined [here](https://github.com/spujadas/elk-docker/issues/145#issuecomment-308195896) – which is the most basic way in which to use the image – to establish a baseline?

**Comment by Daggerlands** [comment]
My set up is exactly the same as yours, I just use my logstash conf files that works perfectly outside of Docker.

**Comment by spujadas** [comment]
Right, so I gather that in the baseline scenario — i.e. default conf files — everything is working fine, and the only case that's not working properly is your conf files with Docker.

I'll need the details of your set-up (e.g. your conf files, and how you're getting the logs to Logstash) so that I can attempt to replicate your issue.

**Comment by Daggerlands** [comment]
`filter {
    grok {
        add_tag => [ "firewall" ]
        match => [ "message", "<(?<evtid>.*)>(?<datetime>(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9]) (?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:[0-5][0-9])) (?<prog>.*?): (?<msg>.*)" ]
    }
    mutate {
        gsub => ["datetime", "  ", " "]
    }
    date {
        match => [ "datetime", "MMM dd HH:mm:ss" ]
    }
    mutate {
        replace => [ "message", "%{msg}" ]
    }
    mutate {
        remove_field => [ "msg", "datetime" ]
    }
    if [prog] =~ /^filterlog$/ {
        mutate {
            remove_field => [ "msg", "datetime" ]
        }
        grok {
            patterns_dir => "/etc/logstash/conf.d/patterns"
            match => [ "message", "%{PFSENSE_LOG_DATA}%{PFSENSE_IP_SPECIFIC_DATA}%{PFSENSE_IP_DATA}%{PFSENSE_PROTOCOL_DATA}",
           "message", "%{PFSENSE_LOG_DATA}%{PFSENSE_IPv4_SPECIFIC_DATA_ECN}%{PFSENSE_IP_DATA}%{PFSENSE_PROTOCOL_DATA}" ]
        }
        mutate {
            lowercase => [ 'proto' ]
        }
        geoip {
            add_tag => [ "GeoIP" ]
            source => "src_ip"
            # Optional GeoIP database
            # Comment out the below if you do not wise to utilize and omit last three steps dealing with (recommended) suffix
            # database => "/usr/share/GeoIP/GeoLiteCountry.dat"
        }
    }
}`

This is the filter. I'm using the elasticsearch output.

**Comment by spujadas** [comment]
Sorry but in order for me to attempt to reproduce your issue I'll need the full details of your set-up, including the files you added or replaced (e.g. where did you put your filter and how did you add it to the image), the commands you used to start the container, how you configured Kibana to view the logs, and, very importantly, how you pushed the logs to ELK (including a way for me to replicate the kind of log events that you're sending to ELK, either as example files – anonymising them as required – or as a detailed description enabling me to recreate the exact set-up of the log-emitting components), as well as any tests you performed and output you saw (e.g. are the events showing up in Elasticsearch? is there anything in the logs?).
I really need to have all these details in this kind of disturbing situation where the base image works fine, ELK configured as you did works fine outside of Docker, and the only apparent difference is just the "running in Docker" bit… which shouldn't make a difference.

See e.g. https://github.com/spujadas/elk-docker/issues/145#issuecomment-308195896 for an instance of detailed steps describing a set-up (on the ELK side and on the log producer side).

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
