### ISSUE TITLE
 * Starting Elasticsearch Server                                                OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)

### ISSUE THREAD

**Issue by hanwenbo** [spujadas/elk-docker#147]
* Starting Elasticsearch Server                                                OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000085330000, 2060255232, 0) failed; error='Cannot allocate memory' (errno=12)

**Comment by spujadas** [comment]
From the [documentation](http://elk-docker.readthedocs.io/#prerequisites), you need:

> - A minimum of 3GB RAM assigned to Docker
>         Elasticsearch alone needs at least 2GB of RAM to run.

**Comment by waydeng** [comment]
helpful
