### ISSUE TITLE
curl: (7) Failed to connect to elk port 9200: Connection refused

### ISSUE THREAD

**Issue by Wenbo16** [spujadas/elk-docker#151]
Hi,
I am following this tutorial 'https://elk-docker.readthedocs.io/' to configure ELK using docker on VirtualBox Ubuntu 16.04. 
Everything goes well except when I do 'docker run -p 80:80 -it --link elk:elk --name filebeat-nginx-example filebeat-nginx-example' I got:
```
curl: (7) Failed to connect to elk port 9200: Connection refused
2017/07/07 18:22:39.942187 beat.go:285: INFO Home path: [/usr/share/filebeat] Config path: [/etc/filebeat] Data path: [/var/lib/filebeat] Logs path: [/var/log/filebeat]
2017/07/07 18:22:39.942366 beat.go:186: INFO Setup Beat: filebeat; Version: 5.4.0
2017/07/07 18:22:39.942698 logstash.go:90: INFO Max Retries set to: 3
2017/07/07 18:22:39.942781 outputs.go:108: INFO Activated logstash as output plugin.
2017/07/07 18:22:39.942941 publish.go:295: INFO Publisher name: b4e0c7254caf
2017/07/07 18:22:39.943073 async.go:63: INFO Flush Interval set to: 1s
2017/07/07 18:22:39.943101 async.go:64: INFO Max Bulk Size set to: 2048
Config OK
==> /var/log/nginx/access.log <==
==> /var/log/nginx/error.log <==
```
But `curl localhost:9200` is fine.
and I also get `debconf: delaying package configuration, since apt-utils is not installed`
 when built filebeat-nginx-example

**Comment by spujadas** [comment]
> But curl localhost:9200 is fine.

From where? From within the running `filebeat-nginx-example` container? From the host? From the ELK container?
Are both containers running on the same host? (I assume that this is the case as you're using the `--link elk:elk` command-line option.)

Could you confirm that "fine" means that you're receiving something like this (i.e. Elasticsearch is running properly)?

    $ curl localhost:9200
    {
      "name" : "4tyOaZt",
      "cluster_name" : "elasticsearch",
      "cluster_uuid" : "zE48QYhyQOa98SRzU5oZdw",
      "version" : {
        "number" : "5.5.0",
        "build_hash" : "260387d",
        "build_date" : "2017-06-30T23:16:05.735Z",
        "build_snapshot" : false,
        "lucene_version" : "6.6.0"
      },
      "tagline" : "You Know, for Search"
    }

> and I also get debconf: delaying package configuration, since apt-utils is not installed
when built filebeat-nginx-example

You can safely ignore this warning.

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
