### ISSUE TITLE
Need help with Elasticsearch input  / Logstash output conf

### ISSUE THREAD

**Issue by mattias88** [spujadas/elk-docker#153]
Problem is, that i can see messages incomming to Logstash (stdout) from my application but forwarding them to elasticsearch seems to fail.

Had a previous version of this image up an running a few weeks ago. Updated now to current version 550.
I made some changes to the config because my application sends Logdata over tcp. 
I build my own Image based on sebp/elk:550. It runs in a VM (VirtualBox with CentOS7) on my Windows-Machine (Windows 7). 
All local ports are forwarded 1:1 to the VM. VM-IP-Address is 172.18.0.8 (just for Information)

[elasticsearch_log.txt](https://github.com/spujadas/elk-docker/files/1196371/elasticsearch.txt)
[logstash_log.txt](https://github.com/spujadas/elk-docker/files/1196370/logstash.txt)

*12-input-conf:*

input {
    tcp {
        port => 4560
        codec => json_lines
    }
}

*30-output-conf:*

filter {
  mutate {
    lowercase => [ "HOSTNAME" ]
  }
}

output {
  if [appname] {
    elasticsearch {
      hosts => ["localhost"]
      sniffing => false
      manage_template => false
      index => "%{[appname]}-%{[HOSTNAME]}-%{+YYYY.MM.dd}" 
      document_type => "logs" 
    }
    } else {
    elasticsearch { 
      hosts => ["localhost"]
      sniffing => false
      manage_template => false
      index => "other-%{[HOSTNAME]}-%{+YYYY.MM.dd}" 
      document_type => "logs" 
    }
  }
  #stdout { codec => rubydebug }
}

**Comment by spujadas** [comment]
I'm going to redirect you to https://discuss.elastic.co/, where knowledgeable users will most certainly be able to help you with the configuration aspects of ELK.

**Comment by mattias88** [comment]
Finaly found it. I'm using Logback with logstash-logback-encoder. Due to a change in Logback, the HOSTNAME doesn't appear in the logevent (https://github.com/logstash/logstash-logback-encoder/issues/216). Since my Index uses HOSTNAME as part of the name it just fails silent and didn't produce anything at all. Configuring the Hostname as a customField in my Logback-Config fixed the issue.
