### ISSUE TITLE
elasticsearch and logstash not working

### ISSUE THREAD

**Issue by folivi** [spujadas/elk-docker#154]
hi
elasticsearch and logstash seem not be starting.
I simply copied the sample code for docker-compose and run it.
Kibana works fine but not elasticsearch and logstash

Here is my log:

`elk_1      |  * Starting periodic command scheduler cron
elk_1      |    ...done.
elk_1      |  * Starting Elasticsearch Server
elk_1      |    ...done.
elk_1      | waiting for Elasticsearch to be up (1/30)
elk_1      | waiting for Elasticsearch to be up (2/30)
elk_1      | waiting for Elasticsearch to be up (3/30)
elk_1      | waiting for Elasticsearch to be up (4/30)
elk_1      | waiting for Elasticsearch to be up (5/30)
elk_1      | waiting for Elasticsearch to be up (6/30)
elk_1      | waiting for Elasticsearch to be up (7/30)
elk_1      | waiting for Elasticsearch to be up (8/30)
elk_1      | waiting for Elasticsearch to be up (9/30)
elk_1      | waiting for Elasticsearch to be up (10/30)
elk_1      | waiting for Elasticsearch to be up (11/30)
elk_1      | waiting for Elasticsearch to be up (12/30)
elk_1      | Waiting for Elasticsearch cluster to respond (1/30)
elk_1      | logstash started.
elk_1      |  * Starting Kibana5
elk_1      |    ...done.
elk_1      | ==> /var/log/elasticsearch/elasticsearch.log <==
elk_1      | [2017-08-03T09:42:41,589][INFO ][o.e.d.DiscoveryModule    ] [Jycji2g] using discovery type [zen]
elk_1      | [2017-08-03T09:42:42,319][INFO ][o.e.n.Node               ] initialized
elk_1      | [2017-08-03T09:42:42,320][INFO ][o.e.n.Node               ] [Jycji2g] starting ...
elk_1      | [2017-08-03T09:42:43,053][INFO ][o.e.t.TransportService   ] [Jycji2g] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
elk_1      | [2017-08-03T09:42:43,096][INFO ][o.e.b.BootstrapChecks    ] [Jycji2g] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elk_1      | [2017-08-03T09:42:43,334][INFO ][o.e.m.j.JvmGcMonitorService] [Jycji2g] [gc][1] overhead, spent [359ms] collecting in the last [1s]
elk_1      | [2017-08-03T09:42:46,225][INFO ][o.e.c.s.ClusterService   ] [Jycji2g] new_master {Jycji2g}{Jycji2gXS4qi1ncPBNquVA}{sMDIwoZRQ6uA5vg3rq9H-Q}{172.18.0.2}{172.18.0.2:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
elk_1      | [2017-08-03T09:42:46,266][INFO ][o.e.h.n.Netty4HttpServerTransport] [Jycji2g] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
elk_1      | [2017-08-03T09:42:46,266][INFO ][o.e.n.Node               ] [Jycji2g] started
elk_1      | [2017-08-03T09:42:46,283][INFO ][o.e.g.GatewayService     ] [Jycji2g] recovered [0] indices into cluster_state
elk_1      | 
elk_1      | ==> /var/log/logstash/logstash-plain.log <==
elk_1      | 
elk_1      | ==> /var/log/kibana/kibana5.log <==
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:52Z","tags":["status","plugin:kibana@5.5.0","info"],"pid":209,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:52Z","tags":["status","plugin:elasticsearch@5.5.0","info"],"pid":209,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:52Z","tags":["status","plugin:console@5.5.0","info"],"pid":209,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:52Z","tags":["status","plugin:metrics@5.5.0","info"],"pid":209,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:53Z","tags":["status","plugin:timelion@5.5.0","info"],"pid":209,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:53Z","tags":["listening","info"],"pid":209,"message":"Server running at http://0.0.0.0:5601"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:42:53Z","tags":["status","ui settings","info"],"pid":209,"state":"yellow","message":"Status changed from uninitialized to yellow - Elasticsearch plugin is yellow","prevState":"uninitialized","prevMsg":"uninitialized"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:09Z","tags":["status","plugin:elasticsearch@5.5.0","info"],"pid":209,"state":"yellow","message":"Status changed from yellow to yellow - No existing Kibana index found","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:09Z","tags":["error","elasticsearch","admin"],"pid":209,"message":"Request error, retrying\nPUT http://localhost:9200/.kibana => socket hang up"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:09Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:09Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:09Z","tags":["status","plugin:elasticsearch@5.5.0","error"],"pid":209,"state":"red","message":"Status changed from yellow to red - Unable to create Kibana index \".kibana\"","prevState":"yellow","prevMsg":"No existing Kibana index found"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:09Z","tags":["status","ui settings","error"],"pid":209,"state":"red","message":"Status changed from yellow to red - Elasticsearch plugin is red","prevState":"yellow","prevMsg":"Elasticsearch plugin is yellow"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:11Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:11Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:11Z","tags":["status","plugin:elasticsearch@5.5.0","error"],"pid":209,"state":"red","message":"Status changed from red to red - Unable to connect to Elasticsearch at http://localhost:9200.","prevState":"red","prevMsg":"Unable to create Kibana index \".kibana\""}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:14Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:14Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | 
elk_1      | ==> /var/log/logstash/logstash-plain.log <==
elk_1      | [2017-08-03T09:43:14,959][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/opt/logstash/data/queue"}
elk_1      | [2017-08-03T09:43:14,966][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/opt/logstash/data/dead_letter_queue"}
elk_1      | [2017-08-03T09:43:15,017][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"49a56a7c-f895-43da-bf9a-c432c9dcc497", :path=>"/opt/logstash/data/uuid"}
elk_1      | [2017-08-03T09:43:15,913][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
elk_1      | [2017-08-03T09:43:15,916][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
elk_1      | [2017-08-03T09:43:16,046][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x19bfe305>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
elk_1      | [2017-08-03T09:43:16,061][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<Java::JavaNet::URI:0x72d1da9c>]}
elk_1      | [2017-08-03T09:43:16,226][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
elk_1      | [2017-08-03T09:43:16,961][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
elk_1      | [2017-08-03T09:43:17,023][INFO ][logstash.pipeline        ] Pipeline main started
elk_1      | [2017-08-03T09:43:17,117][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
elk_1      | 
elk_1      | ==> /var/log/kibana/kibana5.log <==
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:16Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:16Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:19Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:19Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | 
elk_1      | ==> /var/log/logstash/logstash-plain.log <==
elk_1      | [2017-08-03T09:43:21,088][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
elk_1      | [2017-08-03T09:43:21,099][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x19bfe305>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
elk_1      | 
elk_1      | ==> /var/log/kibana/kibana5.log <==
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:21Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:21Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:24Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:24Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | 
elk_1      | ==> /var/log/logstash/logstash-plain.log <==
elk_1      | [2017-08-03T09:43:26,103][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
elk_1      | [2017-08-03T09:43:26,107][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x19bfe305>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
elk_1      | 
elk_1      | ==> /var/log/kibana/kibana5.log <==
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:26Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:26Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:29Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"Unable to revive connection: http://localhost:9200/"}
elk_1      | {"type":"log","@timestamp":"2017-08-03T09:43:29Z","tags":["warning","elasticsearch","admin"],"pid":209,"message":"No living connections"}
elk_1      | 
elk_1      | ==> /var/log/logstash/logstash-plain.log <==
elk_1      | [2017-08-03T09:43:31,111][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
elk_1      | [2017-08-03T09:43:31,115][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<Java::JavaNet::URI:0x19bfe305>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
elk_1      | 
`

**Comment by geostant** [comment]
Same here,
Seems that elasticsearch doesn't listen on port 9200 (it's closed)
I've tried images 5.5.0 and 5.4.3, both suffer from the same issue.

**Comment by spujadas** [comment]
Can't reproduce, unfortunately: it's working fine on my local VM (Ubuntu on Windows) and on a fresh cloud-hosted VM (Ubuntu), with a very similar start-up sequence suggesting that ES started proporly (see below). I don't see what the issue could be due to here…

Is the ES service running in the container? Is it responding properly (e.g. `curl localhost:9200`)?
Also could you try using the image on another machine?

---

	$ docker-compose up
	Starting elkdocker_elk_1
	Attaching to elkdocker_elk_1
	elk_1  |  * Starting periodic command scheduler cron
	elk_1  |    ...done.
	elk_1  |  * Starting Elasticsearch Server
	elk_1  |    ...done.
	elk_1  | waiting for Elasticsearch to be up (1/30)
	elk_1  | waiting for Elasticsearch to be up (2/30)
	elk_1  | waiting for Elasticsearch to be up (3/30)
	elk_1  | waiting for Elasticsearch to be up (4/30)
	elk_1  | waiting for Elasticsearch to be up (5/30)
	elk_1  | waiting for Elasticsearch to be up (6/30)
	elk_1  | waiting for Elasticsearch to be up (7/30)
	elk_1  | waiting for Elasticsearch to be up (8/30)
	elk_1  | waiting for Elasticsearch to be up (9/30)
	elk_1  | Waiting for Elasticsearch cluster to respond (1/30)
	elk_1  | logstash started.
	elk_1  |  * Starting Kibana5
	elk_1  |    ...done.
	elk_1  | ==> /var/log/elasticsearch/elasticsearch.log <==
	elk_1  | [2017-08-09T17:37:20,287][INFO ][o.e.d.DiscoveryModule    ] [QeDRtYb] using discovery type [zen]
	elk_1  | [2017-08-09T17:37:20,927][INFO ][o.e.n.Node               ] initialized
	elk_1  | [2017-08-09T17:37:20,928][INFO ][o.e.n.Node               ] [QeDRtYb] starting ...
	elk_1  | [2017-08-09T17:37:21,098][INFO ][o.e.t.TransportService   ] [QeDRtYb] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
	elk_1  | [2017-08-09T17:37:21,110][INFO ][o.e.b.BootstrapChecks    ] [QeDRtYb] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
	elk_1  | [2017-08-09T17:37:24,355][INFO ][o.e.c.s.ClusterService   ] [QeDRtYb] new_master {QeDRtYb}{QeDRtYbCRX2sLo246vrTfw}{81oxI4gmT3KZGobqxhsM1g}{172.17.0.2}{172.17.0.2:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
	elk_1  | [2017-08-09T17:37:24,428][INFO ][o.e.h.n.Netty4HttpServerTransport] [QeDRtYb] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
	elk_1  | [2017-08-09T17:37:24,428][INFO ][o.e.n.Node               ] [QeDRtYb] started
	elk_1  | [2017-08-09T17:37:24,616][INFO ][o.e.g.GatewayService     ] [QeDRtYb] recovered [2] indices into cluster_state
	elk_1  | [2017-08-09T17:37:24,976][INFO ][o.e.c.r.a.AllocationService] [QeDRtYb] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
	elk_1  |
	elk_1  | ==> /var/log/logstash/logstash-plain.log <==
	elk_1  | [2017-08-09T17:32:04,839][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<Java::JavaNet::URI:0x51bdca6f>}
	elk_1  | [2017-08-09T17:32:04,847][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<Java::JavaNet::URI:0x3cb005a0>]}
	elk_1  | [2017-08-09T17:32:04,961][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250}
	elk_1  | [2017-08-09T17:32:05,520][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
	elk_1  | [2017-08-09T17:32:05,581][INFO ][logstash.pipeline        ] Pipeline main started
	elk_1  | [2017-08-09T17:32:05,681][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
	elk_1  | [2017-08-09T17:37:01,496][WARN ][logstash.runner          ] SIGTERM received. Shutting down the agent.
	elk_1  | [2017-08-09T17:37:01,504][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
	elk_1  | [2017-08-09T17:37:06,556][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>24, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.21-java/lib/logstash/inputs/beats.rb:206:in `run'"}, {"thread_id"=>21, "name"=>"[main]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:121:in `lock'"}, {"thread_id"=>22, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:147:in `lock'"}]}}
	elk_1  | [2017-08-09T17:37:06,562][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
	elk_1  |
	elk_1  | ==> /var/log/kibana/kibana5.log <==
	elk_1  | {"type":"response","@timestamp":"2017-08-09T17:36:38Z","tags":[],"pid":198,"method":"post","statusCode":200,"req":{"url":"/elasticsearch/_msearch","method":"post","headers":{"host":"localhost:5601","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0","accept":"application/json, text/plain, */*","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate","content-type":"application/x-ndjson","kbn-version":"5.5.0","referer":"http://localhost:5601/app/kibana","content-length":"845","connection":"keep-alive"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":95,"contentLength":9},"message":"POST /elasticsearch/_msearch 200 95ms - 9.0B"}
	elk_1  | {"type":"response","@timestamp":"2017-08-09T17:36:43Z","tags":[],"pid":198,"method":"post","statusCode":200,"req":{"url":"/elasticsearch/_msearch","method":"post","headers":{"host":"localhost:5601","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0","accept":"application/json, text/plain, */*","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate","content-type":"application/x-ndjson","kbn-version":"5.5.0","referer":"http://localhost:5601/app/kibana","content-length":"939","connection":"keep-alive"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":24,"contentLength":9},"message":"POST /elasticsearch/_msearch 200 24ms - 9.0B"}
	elk_1  | {"type":"response","@timestamp":"2017-08-09T17:36:48Z","tags":[],"pid":198,"method":"post","statusCode":200,"req":{"url":"/elasticsearch/_msearch","method":"post","headers":{"host":"localhost:5601","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0","accept":"application/json, text/plain, */*","accept-language":"en-GB,en;q=0.5","accept-encoding":"gzip, deflate","content-type":"application/x-ndjson","kbn-version":"5.5.0","referer":"http://localhost:5601/app/kibana","content-length":"938","connection":"keep-alive"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":104,"contentLength":9},"message":"POST /elasticsearch/_msearch 200 104ms - 9.0B"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:03Z","tags":["error","elasticsearch","admin"],"pid":198,"message":"Request error, retrying\nHEAD http://localhost:9200/ => connect ECONNREFUSED 127.0.0.1:9200"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:03Z","tags":["warning","elasticsearch","admin"],"pid":198,"message":"Unable to revive connection: http://localhost:9200/"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:03Z","tags":["warning","elasticsearch","admin"],"pid":198,"message":"No living connections"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:03Z","tags":["status","plugin:elasticsearch@5.5.0","error"],"pid":198,"state":"red","message":"Status changed from green to red - Unable to connect to Elasticsearch at http://localhost:9200.","prevState":"green","prevMsg":"Kibana index ready"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:03Z","tags":["status","ui settings","error"],"pid":198,"state":"red","message":"Status changed from green to red - Elasticsearch plugin is red","prevState":"green","prevMsg":"Ready"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:06Z","tags":["warning","elasticsearch","admin"],"pid":198,"message":"Unable to revive connection: http://localhost:9200/"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:06Z","tags":["warning","elasticsearch","admin"],"pid":198,"message":"No living connections"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:30Z","tags":["status","plugin:kibana@5.5.0","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:30Z","tags":["status","plugin:elasticsearch@5.5.0","info"],"pid":192,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:30Z","tags":["status","plugin:console@5.5.0","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:30Z","tags":["status","plugin:metrics@5.5.0","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:31Z","tags":["status","plugin:timelion@5.5.0","info"],"pid":192,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:31Z","tags":["listening","info"],"pid":192,"message":"Server running at http://0.0.0.0:5601"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:31Z","tags":["status","ui settings","info"],"pid":192,"state":"yellow","message":"Status changed from uninitialized to yellow - Elasticsearch plugin is yellow","prevState":"uninitialized","prevMsg":"uninitialized"}
	elk_1  |
	elk_1  | ==> /var/log/elasticsearch/elasticsearch.log <==
	elk_1  | [2017-08-09T17:37:32,078][INFO ][o.e.m.j.JvmGcMonitorService] [QeDRtYb] [gc][11] overhead, spent [473ms] collecting in the last [1s]
	elk_1  |
	elk_1  | ==> /var/log/kibana/kibana5.log <==
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:31Z","tags":["status","plugin:elasticsearch@5.5.0","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Kibana index ready","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
	elk_1  | {"type":"log","@timestamp":"2017-08-09T17:37:31Z","tags":["status","ui settings","info"],"pid":192,"state":"green","message":"Status changed from yellow to green - Ready","prevState":"yellow","prevMsg":"Elasticsearch plugin is yellow"}
	elk_1  |
	elk_1  | ==> /var/log/logstash/logstash-plain.log <==
	elk_1  | [2017-08-09T17:37:41,065][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
	elk_1  | [2017-08-09T17:37:41,075][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
	elk_1  | [2017-08-09T17:37:41,169][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<Java::JavaNet::URI:0x2002c291>}
	elk_1  | [2017-08-09T17:37:41,170][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<Java::JavaNet::URI:0x5de7f3d7>]}
	elk_1  | [2017-08-09T17:37:41,265][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250}
	elk_1  | [2017-08-09T17:37:41,777][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
	elk_1  | [2017-08-09T17:37:41,834][INFO ][logstash.pipeline        ] Pipeline main started
	elk_1  | [2017-08-09T17:37:42,012][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
