### ISSUE TITLE
docker-compose build elk error

### ISSUE THREAD

**Issue by brianjill** [spujadas/elk-docker#156]
Hello,
I clone this code and run docker-compose build elk 
but i got this error. please help i am running in windows 7

$ docker-compose build elk
Building elk
Step 1/56 : FROM phusion/baseimage
 ---> 877509368a8d
Step 2/56 : MAINTAINER Sebastien Pujadas http://pujadas.net
 ---> Using cache
 ---> 15404ba775db
Step 3/56 : ENV REFRESHED_AT 2017-01-13
 ---> Using cache
 ---> ea292dd2c2be
Step 4/56 : ENV GOSU_VERSION 1.8
 ---> Using cache
 ---> 5726a89a4797
Step 5/56 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> e1086f6d87d0
Step 6/56 : RUN set -x  && apt-get update -qq  && apt-get install -qqy --no-inst
all-recommends ca-certificates curl  && rm -rf /var/lib/apt/lists/*  && curl -L
-o /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_V
ERSION/gosu-$(dpkg --print-architecture)"  && curl -L -o /usr/local/bin/gosu.asc
 "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --p
rint-architecture).asc"  && export GNUPGHOME="$(mktemp -d)"  && gpg --keyserver
hkp://ha.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25
BF357DD4  && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu  &
& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc  && chmod +x /usr/local/bin/gosu  &
& gosu nobody true  && apt-get update -qq  && apt-get install -qqy openjdk-8-jdk
  && apt-get clean  && set +x
 ---> Running in 73c9d7081e0d
**+ apt-get update -qq
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' do
es not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial Release' does not hav
e a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does
 not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' do
es not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/
source/Sources  Connection failed [IP: 91.189.91.23 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/source/Sou
rces  Connection failed [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/so
urce/Sources  Connection failed [IP: 91.189.88.162 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/
source/Sources  Connection failed [IP: 91.189.88.162 80]
E: Some index files failed to download. They have been ignored, or old ones used
 instead.**
ERROR: Service 'elk' failed to build: The command '/bin/sh -c set -x  && apt-get
 update -qq  && apt-get install -qqy --no-install-recommends ca-certificates cur
l  && rm -rf /var/lib/apt/lists/*  && curl -L -o /usr/local/bin/gosu "https://gi
thub.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-archite
cture)"  && curl -L -o /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/r
eleases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc"  && export
 GNUPGHOME="$(mktemp -d)"  && gpg --keyserver hkp://ha.pool.sks-keyservers.net:8
0 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4  && gpg --batch --verify
/usr/local/bin/gosu.asc /usr/local/bin/gosu  && rm -r "$GNUPGHOME" /usr/local/bi
n/gosu.asc  && chmod +x /usr/local/bin/gosu  && gosu nobody true  && apt-get upd
ate -qq  && apt-get install -qqy openjdk-8-jdk  && apt-get clean  && set +x' ret
urned a non-zero code: 100

**Comment by spujadas** [comment]
> E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/
source/Sources Connection failed [IP: 91.189.91.23 80]

Looks like a firewall is preventing the connection, or perhaps the outgoing connections need to go through a proxy. In the latter case, you may want to check this out: https://docs.docker.com/engine/admin/systemd/#httphttps-proxy
