### ISSUE TITLE
logstash service fails to start

### ISSUE THREAD

**Issue by austingoudge** [spujadas/elk-docker#159]
On a clean install of elk, I was getting a problem where everything started except for logstash.

Looking in `/var/log/logstash/error.log` the following error was being logged: `ERROR: Unrecognised option '--no-auto-reload'`.  

Traced where this option was being set to line 40 of `/etc/init.d/logstash`: `LS_OPTS="--no-auto-reload"`

To solve this I created my own Docker image, overriding this file with that line commented out.  logstash then started up correctly.  However, I was surprised that this problem happened at all.  I can see references to `no-auto-reload` and `auto-reload` in the Breaking Changes section of the [docs](https://elk-docker.readthedocs.io) and that this was removed in later tags, but surely the init.d script should therefore no longer reference it, or have I missed or misunderstood something?

**Comment by spujadas** [comment]
This is very strange indeed: the line that you refer to (https://github.com/spujadas/elk-docker/blob/master/logstash-init#L40) has had `LS_OPTS=` for over a year, and `bash`-ing into the running container shows (as expected):

	root@e542e9a627fd:/# grep LS_OPTS= /etc/init.d/logstash
	LS_OPTS=

And previously (and for a short time) that line was `LS_OPTS="--auto-reload", see https://github.com/spujadas/elk-docker/commit/ac194e2cc2bc0cda523662a2094adb945b1f3a55…

… so I have no idea how you're getting `LS_OPTS="--no-auto-reload"` in your `/etc/init.d/logstash`, but it didn't come from the `sebp/elk` image itself.

Did you overwrite the `/etc/init.d/logstash` or bind-mount a custom file there at some point?

**Comment by austingoudge** [comment]
No I did no custom setup or bind-mounting (that will come later, once I get to grips with the basic setup!)

However, I have traced the problem - it is partially a problem with the setup documentation and partially a misunderstanding by me.

I did the original setup some weeks ago and while following the docs I ended up scripting the initial build.  This included scripting the following line which is in the 'Overriding Start-up variables' section of the docs:

```bash
$ sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it \
    -e ES_HEAP_SIZE="2g" -e LS_HEAP_SIZE="1g" -e LS_OPTS="--no-auto-reload" \
    --name elk sebp/elk
```

Because I scripted this, I forgot about it but now realise that this sets the `LS_OPTS` variable and I hadn't appreciated that this would be written into the init.d script.  I now understand how this works but I suggest that the above line in your docs needs to be caveated or the `-e LS_OPTS="--no-auto-reload"` element removed completely as it doesn't work with the latest ELK builds.

**Comment by spujadas** [comment]
Ah, misleading documentation, wasn't expecting that! 😅
Will update, thanks for pointing this out.

**Comment by austingoudge** [comment]
That's great - I see you've removed the reference from the start up variables section of the docs.  Note that you also reference it lower down in the Breaking Changes section, where you suggest using that option in some circumstances.  Worth removing that too, to avoid confusion?

**Comment by spujadas** [comment]
Thanks for the suggestion, I'll update the documentation to clarify this (the option still exists but isn't the same in Logstash 5 as it was in Logstash 2).
