### ISSUE TITLE
Kibana log files

### ISSUE THREAD

**Issue by jchannon** [spujadas/elk-docker#16]
I've left our docker container running doing nothing for a few days and found out that Kibana had stopped. I'm not sure why which is worrying. I see by default Kibana doesnt log errors to a file by default on v4.

Is it worth telling it to on the dockerfile a bit like you've done for logstash so it writes to /var/log/kibana?

`kibana -l /var/log/kibana`

**Comment by spujadas** [comment]
Yes, sounds like a great idea, will push an update in just a bit.
(Oh, and do let me know if you find out why Kibana stops unexpectedly.)

**Comment by jchannon** [comment]
Thanks, have pulled the image and fired it up. For now I see HTTP request logs in the kibana log file, lets hope it logs something if it falls over

**Comment by jchannon** [comment]
Kibana has gone down, the logs only seem to show http requests though so I'm a bit in the dark. Any ideas where to look?

**Comment by spujadas** [comment]
Yep, reminded me of this one as well (which is solved, so I should probably try to reproduce and adjust the memory parameters accordingly): https://github.com/elastic/kibana/issues/5170

**Comment by jchannon** [comment]
I put the output of `docker stats` in that issue, not sure if that helps you?

**Comment by spujadas** [comment]
Following up at #17
