### ISSUE TITLE
`chmod`/`chown` to `/var/lib/elasticsearch` in `start.sh`?

### ISSUE THREAD

**Issue by leesei** [spujadas/elk-docker#160]
When mounting host folder to `/var/lib/elasticsearch`, user `elasticsearch` in the container does not have permission to write to the folder.

Instead of requiring user to set uid/gid of the mount folder, Mariadb container does a `chown` as root before starting the server as `mysql` user.
https://github.com/docker-library/mariadb/blob/master/docker-entrypoint.sh#L70

**Comment by spujadas** [comment]
Sounds good, thanks for the suggestion.
