### ISSUE TITLE
add `elk-post-hooks.sh`

### ISSUE THREAD

**Issue by leesei** [spujadas/elk-docker#161]
I found it useful for:
- adding index template to ES
- adding index pattern to Kibana

Also I suggest waiting for Kibana to start (like ES) in `start.sh`, this ensures `.kibana` index is created before the execution of post hooks.

**Comment by spujadas** [comment]
Wasn't sure there was a use case for post hooks, but I see you found a couple.
Not 100% sure when the `.kibana` index is created exactly, so assuming that by the time Kibana responds on port 5601 the index has been created.

**Comment by pierreyves-lebrun** [comment]
May I ask how you managed to add an index pattern to Kibana using that script?
