### ISSUE TITLE
Elasticsearch Unreachable

### ISSUE THREAD

**Issue by shannnon** [spujadas/elk-docker#163]
I tried to pull the latest image but unfortunately, when I ran it I got the below error.

::JavaNet::URI:0x2f2ed784>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}

**Comment by spujadas** [comment]
I just fired up a fresh VM and everything is working fine, so not sure how to help you troubleshoot this issue, apart from the usual: is ES running? can you reach localhost:9200 (also try with localhost:5601 to establish a baseline) from your host, and from within the container?

**Comment by shannnon** [comment]
Yes, ES is up. I used 2 mac machines now just verify if the said issue is only happening on machine but unfortunately, we got the same connection error time on second machine. Also, I tried other older image version and still getting the same error.

**Comment by spujadas** [comment]
Can you connect (using e.g. `curl`) to localhost:9200 from the host and from within the container?
(For some unknown reason…) there may be an issue with the resolution of hostnames, which may mean that `localhost` needs to be replaced with `127.0.0.1` in your Logstash configuration file in your set-up (although I've never heard about this from Mac users).

**Comment by shannnon** [comment]
This is what I get, I checked the Kibana first and it worked.
------------------------------------
docker exec -it 32551a24ce61 bash
root@32551a24ce61:/# curl localhost:5601
<script>var hashRoute = '/app/kibana';
var defaultRoute = '/app/kibana';
var hash = window.location.hash;
if (hash.length) {
  window.location = hashRoute + hash;
} else {
  window.location = defaultRoute;
}</script>
------------------------------------
Then, I checked the ES and i got the connection error
-------------------------------------
root@32551a24ce61:/# curl localhost:9200
curl: (7) Failed to connect to localhost port 9200: Connection refused
root@32551a24ce61:/#

**Comment by shannnon** [comment]
I've tried to pull and run the ES from official elasticsearch image and I can access the localhost:9200 withou any errors.

**Comment by spujadas** [comment]
Ah! Could you try adding this line:

    http.host: 0.0.0.0

to `elasticsearch.yml`? Then restart ES (`service elasticsearch restart`).

**Comment by shannnon** [comment]
@spujadas sorry I don't think If I have the elasticsearch.yml file. should I create that? It didn't mention that file in your documentation.

**Comment by shannnon** [comment]
@spujadas do you think this is something that you need to change on docker image especially on elasticsearch.yml?

**Comment by shannnon** [comment]
I resolved the issue by increasing the allocated memory for docker to 4G.

Thanks @spujadas.

**Comment by spujadas** [comment]
Ah, great to hear that, thanks very much for the update. I'll bump up the memory requirements in the documentation to be on the safe side.

(As far as what I was suggesting was concerned – which I appreciate may have been unclear – I was asking if you could edit the `/etc/elasticsearch/elasticsearch.yml` in the container to see if that solved the issue. If it had, then I would have updated the image with a new `elasticsearch.yml`. Anyway, wasn't that after all!)
