### ISSUE TITLE
pulling from sebp/elk authentication required

### ISSUE THREAD

**Issue by hayahyts** [spujadas/elk-docker#166]
Hello...I am trying to pull sebp/elk with `docker pull sebp/elk` but I keep getting an **

> authentication required error.

** 
![authentication-required](https://user-images.githubusercontent.com/22107559/30301310-d5020b64-9751-11e7-878a-5e74b3d5e9fa.PNG)

**Comment by spujadas** [comment]
Sounds like a temporary problem with Docker Hub (or, but unlikely as you can pull some images, with your local proxy).
(If you continue to experience this this then I'm afraid I don't know what the issue could be as it looks like a generic issue when accessing Docker Hub: https://forums.docker.com/ may be able to help.)
