### ISSUE TITLE
wrong github link on readthedocs 

### ISSUE THREAD

**Issue by rdxmb** [spujadas/elk-docker#168]
The dropdown "read the docs" at the left bottom on https://elk-docker.readthedocs.io include wrong links:

OnGithub:
View: 
https://github.com/spujadas/elk-docker/blob/master/home/docs/checkouts/readthedocs.org/user_builds/elk-docker/checkouts/latest/docs/index.md
Edit: 
https://github.com/spujadas/elk-docker/edit/master/home/docs/checkouts/readthedocs.org/user_builds/elk-docker/checkouts/latest/docs/index.md

**Comment by spujadas** [comment]
Well spotted. There is actually an open issue on this in the readthedocs.org repo (https://github.com/rtfd/readthedocs.org/issues/1917)… so can't do anything about this, will have to wait until it's fixed on their side.
