### ISSUE TITLE
Kibana shuts down over time: out of memory?

### ISSUE THREAD

**Issue by spujadas** [spujadas/elk-docker#17]
See #16 for background.

**Comment by spujadas** [comment]
@jchannon OK, just started a container, I'm monitoring the (idle) container using New Relic and tracking memory usage and next victim of `oom_killer` (which is presumed to be how Kibana gets killed once its memory usage gets out of hand) using `dstat`.
So far (30 minutes in), Elasticsearch and Logstash are both stable at 270MB and 180MB of memory, and Kibana is using 150MB and on the rise, up from 120MB half an hour ago.
I'll leave everything up and running overnight and "hope" that Kibana dies with useful clues.

**Comment by jchannon** [comment]
I think it took mine from 24-36 hours

**Comment by spujadas** [comment]
Goodness me! Right, I'd better restart the container with much less memory available to begin with!

**Comment by spujadas** [comment]
Still running…

    $ docker stats elk
    CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
    elk                 3.81%               770.6 MB/838.9 MB   91.86%              7.964 MB/2.208 MB

Overall memory usage:
![screenshot-rpm newrelic com 2016-01-21 07-18-12](https://cloud.githubusercontent.com/assets/930566/12473106/7cdf4282-c00f-11e5-9160-6458a6042a41.png)

Kibana memory usage:
![screenshot-rpm newrelic com 2016-01-21 07-16-35](https://cloud.githubusercontent.com/assets/930566/12473189/3906d498-c010-11e5-8ee3-715dc56dedf7.png)

Elastisearch's and Logstash's memory usage is fairly constant (and even somewhat decreasing).

Candidate process for `oom_killer` if/when memory runs own was initially `java` (Elasticsearch or Logstash), but is now `node` (Kibana).

    # dstat --mem --top-oom --top-mem
    ------memory-usage----- --out-of-memory--- --most-expensive-
     used  buff  cach  free|    kill score    |  memory process
    1271M  362M  288M 79.8M|node          152 |node         377M

So at this point, Kibana's cyclic and increasing sawtooth memory usage trend suggests that it will ultimately make the container run out of memory and be killed by `oom_killer`, which reproduces and explains the issue (not Docker-specific), but doesn't solve it.

Will run more tests this evening with `node`'s`--max-old-space-size` option to try and mitigate the problem.

**Comment by jchannon** [comment]
I've just started it up and its sitting at 459MB of 1.023 GB, will keep any eye.

What tool did you use to get those graphs? :smile:

**Comment by spujadas** [comment]
I'm using New Relic to get the graphs: it's SaaS so no server to set up on my side, just a client-side agent to `apt-get install` in the running container and hey presto!

**Comment by spujadas** [comment]
OK, Kibana died after roughly 16 hours (had limited the container's memory to 800MB, Kibana crashed after peaking at 424MB), so can confirm the issue :smile: 
![screenshot-rpm newrelic com 2016-01-21 20-31-56](https://cloud.githubusercontent.com/assets/930566/12493144/f42b1450-c083-11e5-8831-ec0e5c9b3c79.png)

Next step: same thing, but limiting NodeJS's maximum heap size to a lower value and seeing what happens. Will keep you posted.

**Comment by jchannon** [comment]
Thanks

I saw ours rise to 565mb of 1023mb but no crash yet

**Comment by spujadas** [comment]
After about 10 hours, memory usage _kind of_ looks better than it did during the previous test.

    CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
    elk                 1.35%               437.9 MB/838.9 MB   52.20%              14.78 MB/7.004 MB

Kibana's behaviour seems reasonable (currently peaking at 240MB), but there is an upward trend in the memory usage, so let's see how this goes during the next few hours.

![screenshot-rpm newrelic com 2016-01-22 07-26-40](https://cloud.githubusercontent.com/assets/930566/12504003/fd9cc910-c0d9-11e5-9e80-64c72841b218.png)

Again, Kibana is the top candidate for `oom_killer` if anything goes south.

**Comment by jchannon** [comment]
Yup my Kibana fell over during the night. Although I don't have anything
monitoring it really. Looks like you have all the right tools to keep an
eye on this :)

Thanks

**Comment by spujadas** [comment]
Right, memory usage seems to remain under control, so I updated the image.

![screenshot-rpm newrelic com 2016-01-22 20-00-52](https://cloud.githubusercontent.com/assets/930566/12521099/d50d2b88-c148-11e5-9fa4-3594672579d1.png)

If you could it a spin and tell me how it goes that would be terrific.

**Comment by jchannon** [comment]
Brill. What do you think the issue is?

**Comment by spujadas** [comment]
According to https://github.com/elastic/kibana/issues/5170, the most likely explanation is that Kibana's underlying NodeJS is failing to collect garbage properly, which _might_ be due to NodeJS getting confused by Docker and not being able to figure out how much memory is actually available. Solved by forcing garbage collection when the heap reaches 250MBs.

**Comment by jchannon** [comment]
Ah interesting. Thanks for the help. Will pull it down and try

**Comment by jchannon** [comment]
Have pulled it and deployed. One thing I noticed, I ran docker stats elk
and then in the browser, kept refreshing a saved search in kibana and the
mem usage in docker stats kept increasing.

**Comment by spujadas** [comment]
Tried it, same here, but nothing too dramatic, and eventually dropped to the initial level (garbage collection kicking in perhaps?). When left alone `ps aux` reports about 150MB (and slooooowly climbing, as usual) for Kibana's RSS.
How bad is it on your side?

**Comment by jchannon** [comment]
Kibana seems to be at 159mb

docker stats elk reports 642mb although I can't seem to get that to drop

**Comment by spujadas** [comment]
Sounds about right. Here's the latest on my end (quick and dirty hack plotted using R based on raw `ps aux` data)

![rplot](https://cloud.githubusercontent.com/assets/930566/12531522/5d313a36-c1fd-11e5-9595-9ec39bcc7fe8.png)

The red line shows max value 341MB (at which point I assume garbage is collected), container stays under 900MB (albeit with zero incoming log activity)… so we might be out of the woods!

**Comment by jchannon** [comment]
Just checked and all values are not really higher than yesterday so fingers crossed.

I'll keep it running over the weekend and check Monday morning to see if its still up.

Thanks for the awesome help :+1:

**Comment by spujadas** [comment]
All righty! Cheers!

**Comment by jchannon** [comment]
Stil up so its looking good :smile:

**Comment by spujadas** [comment]
Cool! Same over here. I'll leave this issue open for a few more days and if everything continues playing nicely I'll close it.

**Comment by jchannon** [comment]
Brill, thanks for the support

**Comment by jchannon** [comment]
Its stil up so I think we're good! :+1: :smile:

**Comment by spujadas** [comment]
:smiley: Thanks so much for your feedback, same behaviour here, so… closing the issue!

**Comment by jalagrange** [comment]
Hey guys, I'm experiencing the same behavior. Could you point out a way to define when garbage collection should be triggered on my server? or node instance? what should I configure for this to happen?

**Comment by jchannon** [comment]
I dont think you need to do anything if you have pulled the lastest image

**Comment by spujadas** [comment]
@jalagrange Are you experiencing this behaviour with the latest version of the image? This should have been solved by https://github.com/spujadas/elk-docker/commit/aaa09d3ea432d618a46365b6437a55dbeb3a20d2 that I published a few weeks ago (by the way, if you take a look at that specific commit, you'll see how I configured garbage collection, you'll also want to have a look at https://github.com/elastic/kibana/issues/5170 for background information on this issue).

Also, how much memory are you dedicating to the container?

**Comment by jalagrange** [comment]
Wao thanks guys, that was quick... I am actually running kibara 4.3.1 directly on an CentOS server that connects to a remote Elastic Search cluster, not using docker. But take a look at my node memory usage in 3 hours without any type of usage, it sounds very similar to what you guys are describing:

![screen shot 2016-02-11 at 1 27 42 pm](https://cloud.githubusercontent.com/assets/59909/12991265/6214d380-d0c3-11e5-8b7e-69c7a8834d90.png)

I am currently running this on an AWS micro instance so 1GB of memory.

**Comment by spujadas** [comment]
Ah yes, looks familiar. https://github.com/elastic/kibana/issues/5170 is what you want to have a look at for the non-Docker version of the issue (long story short: setting `NODE_OPTIONS="--max-old-space-size=250"` before starting Kibana should solve the problem).
Can't help beyond that as this is really a Kibana issue (I'm merely packaging it as a Docker image!), so if setting `NODE_OPTIONS` doesn't help, you might want to consider filing an issue with the Kibana guys.

**Comment by jalagrange** [comment]
Thanks a lot @spujadas ! I did just that and took a look at the issue you mentioned. I'm pretty confident it will work but I'l post back in case it doesn't. Just to expand your reply, 

NODE_OPTIONS="--max-old-space-size=250"

Must be set at the beginning of bin/kibana that is being executed, 250 being the number of MB you wish to cap the process at. (in case someone else stumbles onto this)

**Comment by Anuga** [comment]
Yup, our kibana on Ubuntu is constantly crashing because of this as well.
