### ISSUE TITLE
docker image base Alpine

### ISSUE THREAD

**Issue by KonstantinKuklin** [spujadas/elk-docker#171]
It would be very nice to reduce image size by using alpine linux.
Do you plan it?

**Comment by spujadas** [comment]
Nope, just too many nice things for Docker in phusion/baseimage that the image relies on, and probably quite a bit of rework to get it working with alpine at a very basic level, so no plans to change the base image.
(Also, I'm going to assume that when running a storage-intensive stack such as ELK, surely the ~230MB difference between phusion and alpine is not that big of a deal.)
