### ISSUE TITLE
Logstash autoreload not working even with the LS_OPTS --config.reload.automatic

### ISSUE THREAD

**Issue by andrevcf** [spujadas/elk-docker#174]
I created a docker-compose file like:
```version: '3.3'
services:
  om-elk:
    image: sebp/elk:562
    ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    volumes:
    - elk-data:/var/lib/elasticsearch
    - ./logstashconfs/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
    container_name: om-elk
    restart: always
    environment: 
      LS_OPTS: --config.reload.automatic
volumes:
  elk-data:
```
But when i change the 02-beats-input.conf logstash is not autoreloading.
When I login to the container and `kill -1 logstashpid` then it works.
Is there any other thing I should config?

**Comment by andrevcf** [comment]
When I changed the volume to a directory and put the 02-beats-input.conf on that directory it works.

`- ./logstashconfs/:/etc/logstash/conf.d/`

Also changed the environment: 
```
environment: 
      - "LS_OPTS=--config.reload.automatic"
```

**Comment by andrevcf** [comment]
Will it be a bug on docker file volume?

**Comment by spujadas** [comment]
>     - ./logstashconfs/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf

I believe you should use an absolute path on the left-hand side of the colon if you're mounting a single file.

Other than that looks good to me.

**Comment by andrevcf** [comment]
I will test that thanks. Closing this because its not an issue with the image
