### ISSUE TITLE
ELK 5.6.4?

### ISSUE THREAD

**Issue by odowdj** [spujadas/elk-docker#179]
Hi there,

I can see that in the tags there are versions 5.6*  through to 6.0.0 but 5.6.4 is missing, just wondering is there a reason for this as I am looking for this version?

Thanks
J

**Comment by spujadas** [comment]
Hi, no reason, I simply missed the release of 5.6.4 (manual process unfortunately).
Expect version 5.6.4 to be available within the next couple of hours.
