### ISSUE TITLE
MAX_OPEN_FILES operation not permitted

### ISSUE THREAD

**Issue by mims92** [spujadas/elk-docker#180]
Hello,

Using the latest image, I have to specify the max open files.

According to https://github.com/spujadas/elk-docker/issues/131, I can use environment variable MAX_OPEN_FILES. 
I did but here is the error:

```
Starting Elasticsearch Server
/etc/init.d/elasticsearch: line 124: ulimit: open files: cannot modify limit: Operation not permitted
```

How could I solve that?

Thanks

**Comment by spujadas** [comment]
Hi,
In most cases you need to set the max open files on the host using `ulimit`, and the parameter will be cascaded to the container.
(The `MAX_OPEN_FILES` env var is made available for some environments where the max open files can only be set from within the container.)

**Comment by mims92** [comment]
I'm using an Amazon Linux AMI, setup the ulimit 
```
$ ulimit
unlimited
$ ulimit -u
65536
```
But I still get the error.

**Comment by spujadas** [comment]
I'm unfamiliar with that Linux image, but I'd say your next port of call is Docker's `ulimit` option: https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container-ulimit
