### ISSUE TITLE
no log forwarding between host and container

### ISSUE THREAD

**Issue by fhenryco** [spujadas/elk-docker#181]
On host, with
sudo tcpdump udp -i enp0s25 port 5044
i can see the logs sent from a remote  firewall

with
sudo tcpdump udp -i docker0 port 5044
I see nothing on the bridge interface

And nothing is received inside the container
From there 
#tcdump 
 outputs nothing 

yet the -p 5044:5044 should redirect everything received on my host ip:5044 to the elk container port 5044 , right ? 
with portainer i can see that the elk container belongs to the  default bridge network as it should and has 
adress 
172.17.0.3 
and gateway 172.17.0.1 , adress of docker0
sysctl net.ipv4.ip_forward 
1
 so ip forwarding should be enabled

so i have no idea what could be wrong...

**Comment by fhenryco** [comment]
sudo iptables -L | grep 5044 
also gives nothing so it's not just a problem of udp vs tcp as i thought

**Comment by fhenryco** [comment]
The problem was that the incoming flow is udp. I can change the docker run command to map -p 5044:5055/udp but then probably logstash is not designed to receive udp , can someone confirm ?

as for nothing in the iptables this is not surprising as the firewall is completely disabled on the host

**Comment by spujadas** [comment]
By default, in this image, Logstash is configured to receive logs shipped by a Filebeat agent ("using the lumberjack protocol, which runs over TCP" (https://www.elastic.co/guide/en/beats/filebeat/6.0/logstash-output.html)).
If you're attempting to send anything else in any other way (which is what I'm guessing as your log data is sent over UDP), then you need to update Logstash's configuration files.
