### ISSUE TITLE
Kibana is crazy slow to initialize

### ISSUE THREAD

**Issue by kenwdelong** [spujadas/elk-docker#182]
I wonder if anyone else has noticed this.  I have been adding this patch https://github.com/fbaligand/kibana/releases/download/v5.6.4-csv-export/csv-export-patch.tar.gz to Kibana.  When I first start the container, Kibana crashes.  I have to exec into the container and run /opt/kibana/bin/kibana from the command line until it stops "Optimizing and caching bundles for kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes".  It often takes 5-10 minutes and the load average goes up to 4-8.  Then I save and commit the container as a tagged image.

Now I've taken the 5.6.4 image and installed Xpack for Kibana.  Now I cannot even start kibana, it is actually crashing my EC2 instance!  If I just start the container, Kibana just crashes.  If I log in, and run /opt/kibana/bin/kibana as root, it takes about 30 seconds and then the EC2 instance crashes.

Does anyone else have this problem?  How am I going to get this XPack instance initialized?  I wonder if this has something to do with the fact that it's a docker image; I've not see anyone else complaining about this.

If anyone is interested in looking, I'm on the newdev branch in https://github.com/kenwdelong/elk-docker.

**Comment by spujadas** [comment]
Thanks for reporting this Ken, and hope someone who has faced the issue can help.

**Comment by kenwdelong** [comment]
I removed the CSV export patch, and now the optimization is done during the docker build when the Kibana XPack is installed.  It still takes 2-3 minutes, but nothing like it was before.

If anyone is curious, check the ELK-5.6.4x tag in my repo (mentioned above).
