### ISSUE TITLE
Unable to connect to Elasticsearch from grafana

### ISSUE THREAD

**Issue by hdattada** [spujadas/elk-docker#183]
I am trying to connect to Elasticsearch from grafana and I see the CORS error 

> Failed to load http://localhost:9200/logs/_mapping: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

My grafana server is running on localhost on port 3000

Below is the dockerfile:
```
FROM sebp/elk

ADD elasticsearch.yml /opt/elasticsearch/config/elasticsearch.yml
```
And below is my elasticsearch.yml file
```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

My grafana version is 4.6.2
And I am pulling the latest sebp/elk image

**Comment by spujadas** [comment]
> `ADD elasticsearch.yml /opt/elasticsearch/config/elasticsearch.yml`

Elasticsearch's configuration file is actually located in `${ES_PATH_CONF}/elasticsearch.yml`, which resolves to `/etc/elasticsearch/elasticsearch.yml`.

**Comment by hdattada** [comment]
Thank you!!! This worked for me.
