### ISSUE TITLE
Unable to clone this repository using ssh

### ISSUE THREAD

**Issue by vaidehi9039** [spujadas/elk-docker#185]
I am unable to clone this repository. 

$ git clone https://github.com/spujadas/elk-docker.git

$ git clone git@github.com:spujadas/elk-docker.git

Both the commands are giving the same error.

Error:
Cloning into 'elk-docker'...
fatal: unable to access 'https://github.com/spujadas/elk-docker.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

**Comment by spujadas** [comment]
Most likely reasons are that you're attempting to clone the repo through a proxy, or your system's OpenSSL is outdated.
Either way, this is not an issue with the repo itself, so closing.
For further guidance on git/GitHub, please ask for help from https://github.community/
