### ISSUE TITLE
Filebeat not sending logs into logstash

### ISSUE THREAD

**Issue by vaidehi9039** [spujadas/elk-docker#186]
below are the steps am following:

1. Filebeat Docker  
docker run -v /C:/HPPS/orion-wso2-flk/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:6.1.2

Filebeat.yml file:

filebeat.prospectors:
- type: log
  enabled: false
  paths:
    - C:\HPPS\orion-wso2-flk\logs\*
    
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:
  host: "localhost:5601"

output.logstash:
  hosts: ["localhost:5044"]

2. running sebp/elk docker image

docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk 

Its not showing any records in logstash, elasticsearch and kibana.

Please help me

**Comment by spujadas** [comment]
Seems that you haven't configured SSL, i.e. you should have something like this in the `output.logstash` section:

    ssl:
      certificate_authorities:
        - /etc/pki/tls/certs/logstash-beats.crt

I would suggest that you first establish a working baseline with Filebeat (as per http://elk-docker.readthedocs.io/#forwarding-logs-filebeat) before customising the `filebeat.yml` file.

Generally speaking, you should have a look at the logs (from ELK and Filebeat) to see if there are any error messages (e.g. the missing configuration for SSL should generate error logs which can help troubleshoot).
I would also recommend starting ELK first (your step 2) before running Filebeat.

**Comment by vaidehi9039** [comment]
I configured SSL like as you menioned still am facing the same issue.

output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]
  ssl:
  certificate_authorities:
    - /etc/pki/tls/certs/logstash-beats.crt

Log: Its just giving kibana logs and no records are there in http://localhost:5601

Status: Downloaded newer image for sebp/elk:latest
 * Starting periodic command scheduler cron
   ...done.
 * Starting Elasticsearch Server
   ...done.
waiting for Elasticsearch to be up (1/30)
waiting for Elasticsearch to be up (2/30)
waiting for Elasticsearch to be up (3/30)
waiting for Elasticsearch to be up (4/30)
waiting for Elasticsearch to be up (5/30)
waiting for Elasticsearch to be up (6/30)
waiting for Elasticsearch to be up (7/30)
Waiting for Elasticsearch cluster to respond (1/30)
logstash started.
 * Starting Kibana5
   ...done.
==> /var/log/elasticsearch/elasticsearch.log <==
[2018-01-25T04:54:53,562][INFO ][o.e.d.DiscoveryModule    ] [x-tg05r] using discovery type [zen]
[2018-01-25T04:54:54,375][INFO ][o.e.n.Node               ] initialized
[2018-01-25T04:54:54,376][INFO ][o.e.n.Node               ] [x-tg05r] starting ...
[2018-01-25T04:54:54,580][INFO ][o.e.t.TransportService   ] [x-tg05r] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2018-01-25T04:54:54,593][INFO ][o.e.b.BootstrapChecks    ] [x-tg05r] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2018-01-25T04:54:57,723][INFO ][o.e.c.s.MasterService    ] [x-tg05r] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {x-tg05r}{x-tg05rjSV6zxC4R0JemBA}{Kh_jfiC3S9CcRJDuJY                                                ppAw}{172.17.0.2}{172.17.0.2:9300}
[2018-01-25T04:54:57,734][INFO ][o.e.c.s.ClusterApplierService] [x-tg05r] new_master {x-tg05r}{x-tg05rjSV6zxC4R0JemBA}{Kh_jfiC3S9CcRJDuJYppAw}{172.17.0.2}{172.17.0.2:9300}, reason: apply cl                                                uster state (from master [master {x-tg05r}{x-tg05rjSV6zxC4R0JemBA}{Kh_jfiC3S9CcRJDuJYppAw}{172.17.0.2}{172.17.0.2:9300} committed version [1] source [zen-disco-elected-as-master ([0] nodes                                                 joined)]])
[2018-01-25T04:54:57,756][INFO ][o.e.h.n.Netty4HttpServerTransport] [x-tg05r] publish_address {172.17.0.2:9200}, bound_addresses {0.0.0.0:9200}
[2018-01-25T04:54:57,756][INFO ][o.e.n.Node               ] [x-tg05r] started
[2018-01-25T04:54:57,777][INFO ][o.e.g.GatewayService     ] [x-tg05r] recovered [0] indices into cluster_state

==> /var/log/logstash/logstash-plain.log <==

==> /var/log/kibana/kibana5.log <==
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["status","plugin:kibana@6.1.2","info"],"pid":175,"state":"green","message":"Status changed from uninitialized to green - Ready","pr                                                evState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["status","plugin:elasticsearch@6.1.2","info"],"pid":175,"state":"yellow","message":"Status changed from uninitialized to yellow - W                                                aiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["status","plugin:console@6.1.2","info"],"pid":175,"state":"green","message":"Status changed from uninitialized to green - Ready","p                                                revState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["status","plugin:elasticsearch@6.1.2","info"],"pid":175,"state":"green","message":"Status changed from yellow to green - Ready","pr                                                evState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["status","plugin:metrics@6.1.2","info"],"pid":175,"state":"green","message":"Status changed from uninitialized to green - Ready","p                                                revState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["status","plugin:timelion@6.1.2","info"],"pid":175,"state":"green","message":"Status changed from uninitialized to green - Ready","                                                prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2018-01-25T04:55:03Z","tags":["listening","info"],"pid":175,"message":"Server running at http://0.0.0.0:5601"}

==> /var/log/logstash/logstash-plain.log <==
[2018-01-25T04:55:24,819][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/opt/logstash/modules/netflow/configuration"}
[2018-01-25T04:55:24,838][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/opt/logstash/modules/fb_apache/configuration"}
[2018-01-25T04:55:24,924][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/opt/logstash/data/queue"}
[2018-01-25T04:55:24,930][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/opt/logstash/data/dead_letter_queue"}
[2018-01-25T04:55:25,384][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-01-25T04:55:25,417][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"80d092aa-46c2-40ee-a3df-419a343b1706", :path=>"/opt/logstash/data/uui                                                d"}
[2018-01-25T04:55:26,197][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.2"}
[2018-01-25T04:55:26,774][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-01-25T04:55:30,634][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, b                                                ut are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have an                                                y questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch hosts=>[//localhost], manage_template=>false,                                                 index=>"%{[@metadata][beat]}-%{+YYYY.MM.dd}", document_type=>"%{[@metadata][type]}", id=>"c4ee5abcf701afed0db36d4aa16c4fc10da6a92bbd615d837cccdf2f368b7802", enable_metric=>true, codec=><Lo                                                gStash::Codecs::Plain id=>"plain_d8e471fa-1a38-4242-a97f-7376d7f7d8f9", enable_metric=>true, charset=>"UTF-8">, workers=>1, template_name=>"logstash", template_overwrite=>false, doc_as_upse                                                rt=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=                                                >"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000,                                                 http_compression=>false>}
[2018-01-25T04:55:31,493][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2018-01-25T04:55:31,501][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}

==> /var/log/kibana/kibana5.log <==
{"type":"response","@timestamp":"2018-01-25T04:55:30Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_mapping&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":53,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_mapping&method=GET 200 53ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:55:30Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_aliases&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":37,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_aliases&method=GET 200 37ms - 9.0B"}

==> /var/log/logstash/logstash-plain.log <==
[2018-01-25T04:55:31,751][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2018-01-25T04:55:31,823][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>nil}
[2018-01-25T04:55:31,828][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-01-25T04:55:31,869][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost"]}
[2018-01-25T04:55:32,152][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.                                                max_inflight"=>250, :thread=>"#<Thread:0x52cf0055 run>"}
[2018-01-25T04:55:32,652][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2018-01-25T04:55:32,803][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
[2018-01-25T04:55:32,935][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2018-01-25T04:55:33,029][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}

==> /var/log/kibana/kibana5.log <==
{"type":"response","@timestamp":"2018-01-25T04:56:31Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_aliases&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":34,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_aliases&method=GET 200 34ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:56:31Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_mapping&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":55,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_mapping&method=GET 200 55ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:57:32Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_aliases&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":22,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_aliases&method=GET 200 22ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:57:32Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_mapping&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":47,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_mapping&method=GET 200 47ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:58:33Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_mapping&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":33,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_mapping&method=GET 200 33ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:58:33Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_aliases&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":36,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_aliases&method=GET 200 36ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:59:34Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_mapping&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":29,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_mapping&method=GET 200 29ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T04:59:34Z","tags":[],"pid":175,"method":"post","statusCode":200,"req":{"url":"/api/console/proxy?path=_aliases&method=GET","method":"post","heade                                                rs":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"text/plain, */*; q=0.01","origin":"http://localhost:5601","kbn-version":"6.1.2","user-agent":"Mozilla/5                                                .0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br                                                ","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":27,"contentL                                                ength":9},"message":"POST /api/console/proxy?path=_aliases&method=GET 200 27ms - 9.0B"}
{"type":"response","@timestamp":"2018-01-25T05:00:19Z","tags":[],"pid":175,"method":"get","statusCode":200,"req":{"url":"/app/kibana","method":"get","headers":{"host":"localhost:5601","conn                                                ection":"keep-alive","cache-control":"max-age=0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36","upgrade-                                                insecure-requests":"1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip,                                                 deflate, br","accept-language":"en-US,en;q=0.9"},"remoteAddress":"172.17.0.1","userAgent":"172.17.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":                                                344,"contentLength":9},"message":"GET /app/kibana 200 344ms - 9.0B"}

How to configure working baseline using http://elk-docker.readthedocs.io/#forwarding-logs-filebeat
Am unable to find this path /etc/filebeat/filebeat.yml in elk container.

please help me

**Comment by spujadas** [comment]
The ELK services appear to be starting up properly.

> How to configure working baseline using http://elk-docker.readthedocs.io/#forwarding-logs-filebeat
Am unable to find this path /etc/filebeat/filebeat.yml in elk container.

It's in the example nginx-filebeat Docker image. For step-by-step instructions on how to establish a baseline using this image, see https://github.com/spujadas/elk-docker/issues/145#issuecomment-308195896 
If it doesn't work then the logs output by the nginx-filebeat container should have more information.

**Comment by vaidehi9039** [comment]
Now am getting below Error:

C:\HPPS\AWS Code Base\elk-docker-master\nginx-filebeat>docker run -p 81:80 -it --link elk:elk --name filebeat-nginx-example filebeat-nginx-example
Warning: Couldn't read data from file "/etc/filebeat/filebeat.template.json",
Warning: this makes an empty POST.
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "request body is required"
      }
    ],
    "type" : "parse_exception",
    "reason" : "request body is required"
  },
  "status" : 400
}
2018/01/25 06:15:38.477428 metrics.go:23: INFO Metrics logging every 30s
2018/01/25 06:15:38.477405 beat.go:436: INFO Home path: [/usr/share/filebeat] Config path: [/etc/filebeat] Data path: [/var/lib/filebeat] Logs path: [/var/log/filebeat]
2018/01/25 06:15:38.478233 beat.go:443: INFO Beat UUID: d40e1952-1f2a-471d-b38e-bdfe127c04da
2018/01/25 06:15:38.478320 beat.go:203: INFO Setup Beat: filebeat; Version: 6.1.2
2018/01/25 06:15:38.479657 module.go:76: INFO Beat name: 3918f6ceec05
Config OK
==> /var/log/nginx/access.log <==

==> /var/log/nginx/error.log <==

**Comment by spujadas** [comment]
@vaidehi9039 It's just a warning, not an error. You should be able to browse to your host on port 81 and see a dummy HTML page.

**Comment by vaidehi9039** [comment]
Thank you for your response, It is working fine now.

But it is fetching logs only from access.log file
How to make it to work for a log file present in my windows system/  wso2 server running locally.

**Comment by vaidehi9039** [comment]
Thank you for your response. It is working fine using nginx .
But when I try to fetch the logs from file present in my system it is not working.

I tried in 2 possible ways, but both are not working
1. filebeat-nginx-example Image
docker run -p 80:80 -it -v /C:/HPPS/orion-wso2-flk/conf/filebeat.yml:/etc/filebeat/filebeat.yml --link elk:elk --name filebeat-nginx-example filebeat-nginx-example

filebeat.yml

output:
  logstash:
    enabled: true
    hosts:
      - elk:5044
    timeout: 15
    ssl:
      certificate_authorities:
      - /etc/logstash/logstash-beats.crt

filebeat:
  prospectors:
    -
      paths:
        - C:\HPPS\orion-wso2-flk\logs\syslog.log
        #– /opt/wso2as-5.3.0/repository/logs/wso2carbon.log

      document_type: syslog
      #document_type: appserver_log

2.  Using docker.elastic.co/beats/filebeat:6.1.2 Image

docker run -v /C:/HPPS/orion-wso2-flk/conf/filebeat.yml:/filebeat.yml -v /C:/HPPS/orion-wso2-flk/conf/filebeat.yml:/logstash-beats.crt docker.elastic.co/beats/filebeat:6.1.2

In both the ways there is no error, but it is not fetching any records.
Please help me

**Comment by spujadas** [comment]
Happy to see that you got the baseline set-up working (and will therefore close this as it appears that there is no issue with the image).
As far as I understand you now need help with the configuration of Filebeat (and possibly Logstash), which is something that I cannot assist you with: I would therefore recommend that you turn to https://discuss.elastic.co/ for further guidance.
