### ISSUE TITLE
There are no /usr/share/zoneinfo in phusion/baseimage

### ISSUE THREAD

**Issue by Cinerar** [spujadas/elk-docker#188]
https://github.com/phusion/baseimage-docker/issues/415

So
https://github.com/spujadas/elk-docker/blob/master/start.sh#L41

should be replaced i believe

**Comment by spujadas** [comment]
Well spotted! It appears that `tzdata` was removed in Ubuntu 16.04 (base image `ubuntu:16.04`).
Will use https://github.com/phusion/baseimage-docker/issues/415#issuecomment-305981737 to fix this.
