### ISSUE TITLE
Multiline logs not working in ELK 

### ISSUE THREAD

**Issue by vaidehi9039** [spujadas/elk-docker#189]
Hi,

Multiline options are working fine if I setup elasticsearch, logstash and kibana seperately in my windows system. Filebeat is sending multiline logs properly, but the logs are not present in kibana.

My Filebeat.yml file:

filebeat.prospectors:  
- type: log

  enabled: true
  paths:
   
    - C:\elk\logs\syslog.log
  fields:
    document_type: prod

  include_lines: ['^TID','^ERR', '^WARN']
  
  multiline.pattern: '^TID'
  multiline.negate: true
  multiline.match: after

filebeat.config.modules:

  path: ${path.config}/modules.d/*.yml

  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:
  host: "localhost:5601"

output.logstash:
  hosts: ["localhost:5044"]

logging.level: debug
logging.selectors: ["*"]

02-beats-input.conf file:

input {
	beats{
		port => 5044
	}    
}

filter {
        grok {
            match => [ "message", "TID:%{SPACE}\[%{INT:tenant_id}\]%{SPACE}\[\]%{SPACE}\[%{TIMESTAMP_ISO8601:event_timestamp}\]%{SPACE}%{LOGLEVEL:level}%{SPACE}{%{JAVACLASS:java_class}}%{SPACE}-%{SPACE}%{GREEDYDATA:log_message}" ]
        }
		date{
			match => [ "event_timestamp", "ISO8601","yyyy-MM-dd HH:mm:ss.SSSZ","yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
			timezone => "Asia/Kolkata"
		}
		mutate {
			remove_field => [ "message" ]
		}	
}

30-output.conf file:

output {
	if[fields][document_type] == "uit" {
		elasticsearch {
			hosts => "localhost:9200"
			manage_template => false
			index => "uit-%{+YYYY.MM.dd}"
			document_type => "%{[@metadata][type]}"
		}
	} else if[fields][document_type] == "prod" {
		elasticsearch {
			hosts => "localhost:9200"
			manage_template => false
			index => "prod-%{+YYYY.MM.dd}"
			document_type => "%{[@metadata][type]}"
		}
	}
}

please help me.
Multiline is working fine if i setup ELK seperately. But if I use sebp/elk docker image it is not working.

**Comment by vaidehi9039** [comment]
The logs are coming to kibana, but it is creating new index with the same name for each hits. And also if i use @timestamp as "time filter field name" it will not show any logs, if i use "I dont want to use time filter option then only it will show the logs".

Please help me to resolve this issue.

**Comment by spujadas** [comment]
Don't know I'm afraid, especially if you have the exact same configurations in your Windows set-up and in the container running sebp/elk.
Leaving this one open in case someone has an idea (in case it turns out that there's an issue with the image), and I would strongly recommend submitting your question over at http://discuss.elastic.co/ for informed advice.

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
