### ISSUE TITLE
Lumberjack protocol error

### ISSUE THREAD

**Issue by gmarineau** [spujadas/elk-docker#190]
Hi,

First thanks for your amazing job ! I have a problem with Filebeat on a remote server to communicate with the docker.

Everything for fine when the SSL is disabled, but when I try to enable the ssl between my docker container and an remote server. I got this error from filebeat :

`2018-02-13T22:17:22+01:00 ERR  Failed to publish events caused by: lumberjack protocol error
2018-02-13T22:17:22+01:00 ERR  Failed to publish events caused by: lumberjack protocol error
2018-02-13T22:17:22+01:00 ERR  Failed to publish events caused by: lumberjack protocol error
2018-02-13T22:17:22+01:00 ERR  Failed to publish events caused by: lumberjack protocol error
2018-02-13T22:17:22+01:00 ERR  Failed to publish events caused by: lumberjack protocol error
2018-02-13T22:17:22+01:00 ERR  Failed to publish events caused by: client is not connected`

I have created my own certificate, copy the crt file, but nothing change always the same error.

The remote server is a Debian 8. I don't know if I need to use nginx proxy to redirect the port or something like this. If you need more details just ask me.

Thanks for your help !

**Comment by spujadas** [comment]
Hi,

Thanks for the kind words!

Hmmm, would have expected more information from the logs, but anyway could you try this command from your remote server to check for basic SSL connectivity:

    openssl s_client -connect <logstash-ip-or-hostname>:5044 -CAfile <ca-certificate>.crt

I'm assuming that you aren't using nginx as a reverse proxy. If you are then you would probably want to enable SSL on the nginx (i.e. secure channel between Filebeat and nginx) and disable it between nginx and Logstash (haven't tested this though).

**Comment by gmarineau** [comment]
Hi,

I get this error when I try the command :  `read:errno=104`

I will try tomorrow to create a host for nginx with reverse proxy to 5044 maybe this is the solution.

**Comment by gmarineau** [comment]
I have try again but nothing change, I get always the same message when I use the command

```
subject=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
issuer=/C=AU/ST=Some-State/O=Internet Widgits Pty Ltd
---
No client certificate CA names sent
---
SSL handshake has read 1387 bytes and written 415 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 308558CA6D829EA051ECACD531816080D5EC5913A4CCAD087DDE47E1CF17451D
    Session-ID-ctx:
    Master-Key: 1FC9ED029DA634027040F7F1B2FC3B23B61020251317358562BE720BA927E2E5B5B55A18605C71288FC37339FBB1B8D7
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1518600145
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
read:errno=104
```

**Comment by gmarineau** [comment]
I found something strange on the docker host log from logstash 

`Handling exception: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER`

**Comment by spujadas** [comment]
OK, let's narrow this down. 
If you run the `openssl` line on the host running the container, using the default certificate from the image, you should get something like this:

    $ openssl s_client -connect localhost:5044 -CAfile logstash-beats.crt
    CONNECTED(00000003)
    depth=0 CN = *
    verify return:1
    ---
    Certificate chain
     0 s:/CN=*
       i:/CN=*
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    MIIC6zCCAdOgAwIBAgIJANPZwuf+5wTLMA0GCSqGSIb3DQEBCwUAMAwxCjAIBgNV
    BAMMASowHhcNMTUxMjI4MTA0NTMyWhcNMjUxMjI1MTA0NTMyWjAMMQowCAYDVQQD
    DAEqMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp+jHFvhyYKiPXc7k
    0c33f2QV+1hHNyW/uwcJbp5jG82cuQ41v70Z1+b2veBW4sUlDY3yAIEOPSUD8ASt
    9m72CAo4xlwYKDvm/Sa3KJtDk0NrQiz6PPyBUFsY+Bj3xn6Nz1RW5YaP+Q1Hjnks
    PEyQu4vLgfTSGYBHLD4gvs8wDWY7aaKf8DfuP7Ov74Qlj2GOxnmiDEF4tirlko0r
    qQcvBgujCqA7rNoG+QDmkn3VrxtX8mKF72bxQ7USCyoxD4cWV2mU2HD2Maed3KHj
    KAvDAzSyBMjI+qi9IlPN5MR7rVqUV0VlSKXBVPct6NG7x4WRwnoKjTXnr3CRADD0
    4uvbQQIDAQABo1AwTjAdBgNVHQ4EFgQUVFurgDwdcgnCYxszc0dWMWhB3DswHwYD
    VR0jBBgwFoAUVFurgDwdcgnCYxszc0dWMWhB3DswDAYDVR0TBAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAaLSytepMb5LXzOPr9OiuZjTk21a2C84k96f4uqGqKV/s
    okTTKD0NdeY/IUIINMq4/ERiqn6YDgPgHIYvQheWqnJ8ir69ODcYCpsMXIPau1ow
    T8c108BEHqBMEjkOQ5LrEjyvLa/29qJ5JsSSiULHvS917nVgY6xhcnRZ0AhuJkiI
    ARKXwpO5tqJi6BtgzX/3VDSOgVZbvX1uX51Fe9gWwPDgipnYaE/t9TGzJEhKwSah
    kNr+7RM+Glsv9rx1KcWcx4xxY3basG3/KwvsGAFPvk5tXbZ780VuNFTTZw7q3p8O
    Gk1zQUBOie0naS0afype5qFMPp586SF/2xAeb68gLg==
    -----END CERTIFICATE-----
    subject=/CN=*
    issuer=/CN=*
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 1256 bytes and written 421 bytes
    ---
    New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-GCM-SHA384
        Session-ID: 4CCAC749254CAB0EFA9069FA6728BC845C5974E42F6EC8436C3996BC33FDB277
        Session-ID-ctx:
        Master-Key: 14BA1F75B621A608DBE28D24412B3F17763997F4AD478D8570FE229BD3A12C4640D1BEA2F230794DBF31A5875D6CE2EC
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1518638882
        Timeout   : 300 (sec)
        Verify return code: 0 (ok)
    ---

Which eventually times out with:

    read:errno=0

And Logstash's logs should show a message like this (as it isn't receiving a proper Lumberjack message):

    [2018-02-14T20:07:47,636][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 172.17.0.1:46311] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 105

By the way, I'm pretty sure that this issue isn't Docker-specific, so you may also want to ask for assistance over at http://discuss.elastic.co/, as at some point it may boil down to an improper client-side or proxy config rather than an actual issue with this Docker image.

**Comment by gmarineau** [comment]
I have test on the host and it's ok. I will try to contact the elastic community to find a response about this issue.

Thank's again for your job.

**Comment by spujadas** [comment]
Thanks for the feedback!
If it turns out that it actually is an issue with the image or if something needs to be clarified in the documentation, do let me know. Cheers.
