### ISSUE TITLE
6.2.1 Image has bug logstash heap on start.sh

### ISSUE THREAD

**Issue by heikkis** [spujadas/elk-docker#191]
## start.sh in master and on docker 6.2.1 image has error location for setting up LS_HEAP_SIZE:
![image](https://user-images.githubusercontent.com/1392264/36395490-171e01d0-15c2-11e8-9ab9-5f297803e69b.png)

## start.sh is fixed already in v6 branch:
![image](https://user-images.githubusercontent.com/1392264/36395496-27065944-15c2-11e8-881d-f699011ecb90.png)

**Comment by spujadas** [comment]
Ah yes, I must have been a bit greedy when searching/replacing at some point. 😅 
Thanks for reporting this.

**Comment by heikkis** [comment]
Thanks
