### ISSUE TITLE
Impossible to connect to Logstash from remote host

### ISSUE THREAD

**Issue by yareg** [spujadas/elk-docker#195]
Hello,
  
$ `telnet localhost 5044 `    

> Trying ::1...     
> Connected to localhost.     
> Escape character is '^]'.    
> Connection closed by foreign host.   

  
All is OK, but  
$ `telnet XX.XX.XX.XX 5044  `

> Trying XX.XX.XX.XX...  
> telnet: Unable to connect to remote host: Connection refused  

  
I've simplified Logstash's config:  
$ `cat 02-beats-input.conf`  

> input {  
>   beats {  
>     port => 5044  
>   }  
> }  

  
Port is opened in AWS security group, iptables is disabled:  
$ `sudo service iptables status`  

> ● iptables.service  
>    Loaded: not-found (Reason: No such file or directory)  
>    Active: inactive (dead) 

 
  
$ `sudo iptables -L`  

> Chain INPUT (policy ACCEPT)  
> target     prot opt source               destination  
>   
> Chain FORWARD (policy DROP)  
> ...  

  

What I'm doing wrong?

**Comment by spujadas** [comment]
Looks good to me.

Seeing that Docker should expose container ports on any possible interfaces, my guess would be that something's wrong with the security groups (missing incoming rule on the host and/or missing outgoing rule on the remote client) — but I understand that you've set up the groups properly — or that your client is not connecting to a routable/public IP address (which I assume is not the case here).

If anyone reading this had a similar experience with AWS and found a way to solve the issue, then by all means do jump in.

**Comment by yareg** [comment]
To make sure I've configured security group properly, I stopped container and run npm http-server on port 5044 - as expected, it works!

**Comment by spujadas** [comment]
Ok that rules out security groups then!
Could you try to explicitly bind the container to the public IP address of your VM/host using `-p HOST_IPADDR:PORT:PORT`?

**Comment by yareg** [comment]
I could run container using private IP address, but behavior is the same: Kibana's web interface is available, but connection to 5044 port is refused.  Also, refused connection from localhost (5601, 5044).  

 When i tried to use public IP got error - " Error starting userland proxy: listen tcp XX.XX.XX.XX:9200: bind: cannot assign requested address."

Do you have any other ideas?

**Comment by spujadas** [comment]
Strange indeed, and hard to troubleshoot without having a similar set-up to play with.
Could you provide the steps to recreate your set-up so that I can attempt to reproduce the issue on my side?

**Comment by yareg** [comment]
I've solved this issue.
The problem was that logstash haven't started, but docker's forwarding I took for correct connection via telnet from localhost.

**Comment by spujadas** [comment]
That definitely makes more sense, thanks for the update.
(Slightly strange as I would have expected you to see identical behaviours whether connecting locally or remotely… but anyway, great that you managed to sort everything out!)
