### ISSUE TITLE
Minimize image size with multi-stage builds?

### ISSUE THREAD

**Issue by drozzy** [spujadas/elk-docker#196]
I'm not sure if it's possible for this image, but making it smaller would be great, with multi-stage builds.
E.g.: https://blog.onebar.io/reducing-docker-image-size-using-multi-stage-build-4ec8ee111aae

**Comment by spujadas** [comment]
As far as I understand it actually wouldn't work with this image (unlike the example in the linked article where the build process generates many artefacts that are useless at runtime, thus benefiting from a two-stage build).
If you take a look at the layers that make up the image (https://microbadger.com/images/sebp/elk), you'll see that out of the 461.5MB (total download size), the incompressible bits are the base OS (73.7MB), Java and other required tools (146.6MB), Elasticsearch (27.7MB), Logstash (134.5MB), and Kibana (79MB), i.e. 461.5MB.
So at best, optimising the Dockerfile would save no more than a few kB (by having a second stage build that adds the files that were modified by the `sed`s in the first stage).

**Comment by drozzy** [comment]
Ok, np! I was just curious. Thanks for clarification.
