### ISSUE TITLE
Log data doesn't persist after removing and rebuilding container

### ISSUE THREAD

**Issue by wesleymusgrove** [spujadas/elk-docker#20]
After inserting dummy log data into logstash, I am able to see the logs in kibana as well as [http://elk:9200/_search?pretty](http://elk:9200/_search?pretty).

But when I `docker-compose kill` followed by `docker-compose rm` and then rebuild using `docker-compose up` the old dummy logs are not being persisted in the VOLUME `/var/lib/elasticsearch`.

I have to insert new dummy logs for kibana to re-create `logstash-*` index pattern and the old logs are not there.

Am I not supposed to `docker-compose rm`?  I thought volumes persisted unless you explicitly run `docker-compose -v rm`...

**Comment by wesleymusgrove** [comment]
I resolved this issue by mounting a host directory as a data volume.  After cloning the git repo, I created a folder at the root called "elk_data", at the same level as the "docs" and "nginx-filebeat" directories.  Then I changed my docker-compose.yml file to look like this:
    
    elk:
      build: .
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5000:5000"
        - "5044:5044"
      volumes:
        - ./elk_data:/var/lib/elasticsearch

And I commented this line out of the Dockerfile `#VOLUME /var/lib/elasticsearch`

**Comment by spujadas** [comment]
That certainly is a great way to work around the issue!
I'd just reproduced your issue and was getting very confused about why the volume had disappeared, contradicting Docker Compose's documentation.
A couple of tests later, `docker volume ls` shows that the volume hasn't been destroyed by `docker-compose rm` (unless you use `-v`), but docker-compose isn't picking up on it when re-`up`ping the container, so not sure what's happening there to be honest…
