### ISSUE TITLE
Elasticsearch crashes in latest image with default settings

### ISSUE THREAD

**Issue by rherrick** [spujadas/elk-docker#200]
I ran the latest version of sebp/elk following the example in the documentation:

`$ docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk`

This seemed to start OK and got up to this line:

`[2018-03-30T01:15:43,812][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}`

I then continued in the documentation with the **Creating a dummy log entry** step. That's where things went wrong. The results on the server side (i.e. where I ran the **docker run** command) are in the attached [elk-fail.log](https://github.com/spujadas/elk-docker/files/1862426/elk-fail.log). The results on the logstash side (where I ran the **/opt/logstash/bin/logstash** command) are in the attached [logstash-launch-fail.log](https://github.com/spujadas/elk-docker/files/1862427/logstash-launch-fail.log).

I went through this a few times and got this failure consistently. I'm on a Macbook Pro, High Sierra 10.13.3, 16 GB RAM, Docker version 18.03.0-ce-mac59 (23608).

I tried using Kitematic as well, which failed similarly.

**Comment by spujadas** [comment]
Nothing springs to mind tbh, so leaving open in case Mac users out there have an idea.

**Comment by waynetheisinger** [comment]
Hi @rherrick you say that your Mac has 16GB of ram but you haven't mentioned how much ram you have allowed docker to use...

It is working fine with the below setup, but it hung when I assigned 4GB...

<img width="516" alt="screenshot 2019-01-09 at 16 08 55" src="https://user-images.githubusercontent.com/8143799/50907954-e4b7aa00-1428-11e9-8686-e47f92656b89.png">

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
