### ISSUE TITLE
using environment variables in a logstash configuration

### ISSUE THREAD

**Issue by Paveltarno** [spujadas/elk-docker#202]
Hello!,
I've seem to hit a wall trying to use and env var inside a custom logstash configuration,
I tried using the `elk-prehooks.sh` script but unlike ES's `/etc/default/elasticsearch` could not find any logstash equivalent file to put my env vars in to be later used by the configuration files.
Looking at the `logstash-init` there is no apparent support for custom env vars though I might be missing something.

**Comment by spujadas** [comment]
`/etc/default/logstash` perhaps (sourced by `logstash-init` at https://github.com/spujadas/elk-docker/blob/master/logstash-init#L42)?

**Comment by Paveltarno** [comment]
Oh I must have missed it [= thank you sir!
