### ISSUE TITLE
forwarding logs from filebeats to logstatsh

### ISSUE THREAD

**Issue by utsav666** [spujadas/elk-docker#213]
I have installed this dockerize-elk on  VM where it's running fine .....now when I want to forward logs from another  vm to the vm(where I have installed this dockerize-vm)....I have gone through the documentation of filebeats where it's refer to change logstash.conf but i didn't find any logstash.conf file in the dockerize repo of sebp/elk....any suggestion how to proceed ...need help

**Comment by spujadas** [comment]
Logstash processes all the `*.conf` files in the configuration directory (see https://www.elastic.co/guide/en/logstash/current/config-setting-files.html#_pipeline_configuration_files).

In the image, the configuration is split across several configuration files (namely `02-beats-input.conf`, `10-syslog.conf`, `11-nginx.conf`, and `30-output.conf`), so for your Filebeats scenario you could edit `02-beats-input.conf`... or you could remove all the default config files and create a single `logstash.conf` file with all of your config in it.
