### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by thiagosoeiro** [spujadas/elk-docker#215]
Why am I getting this error?

**Pulling from sebp/elk
image operating system "linux" cannot be used on this platform**

I'm using Docker with Windows containers.

**Comment by spujadas** [comment]
I'm unfamiliar with Docker for Windows, but some quick searching suggests that it supports two modes: a Windows mode, and a Linux mode.
The _sebp/elk_ image is based on a Linux image, so you would need to switch your Docker to Linux mode.
I can't provide you with steps to do this, but this post in the Docker forums may help: https://forums.docker.com/t/docker-for-windows-image-operating-system-linux-cannot-be-used-on-this-platform/28936

Leaving this issue open to add a note on this in the prerequisites section of the documentation.

**Comment by thiagosoeiro** [comment]
Got it.
Is there any windows compatible image?

**Comment by spujadas** [comment]
Not that I know of.
