### ISSUE TITLE
Tag images

### ISSUE THREAD

**Issue by jchannon** [spujadas/elk-docker#22]
Hi,

We made a change to our docker image that is based on yours so it pulled your latest with the ELK bits upgraded and then kibana just kept saying it was rebuilding the index. Not sure why so we nuked our docker volume and started again as we didn't need the data.

However, going forward this might be an issue once we have stored data.  Would it be possible for you to tag your images on docker hub so if we do pull latest and things go wrong we can fallback to an image tag we know worked.  At the moment you just have `latest` so there is no way to fall back.

Thanks :smile:

**Comment by spujadas** [comment]
Sure thing (and good point you raise there!), will take care of that.

**Comment by jchannon** [comment]
Brill! Thanks
