### ISSUE TITLE
Kibana super slow startup and crash

### ISSUE THREAD

**Issue by kenwdelong** [spujadas/elk-docker#225]
Has anyone else experienced this? I start the container (6.4.0) and in a few seconds Kibana crashes.  I get the dreaded message:

    {"type":"log","@timestamp":"2018-09-07T03:06:23Z","tags":["info","optimize"],"pid":227,"message":"Optimizing and caching bundles for ml, stateSessionStorageRedirect, status_page, timelion, graph, monitoring, dashboardViewer, apm and kibana. This may take a few minutes"}

So I have to `docker exec` into the container, cd to `/opt/kibana`, and run `bin/kibana`.  I wait many minutes (on an EC2 t2.medium it ran for an hour and then the VM crashed, on a t2.large it took 5-10 minutes, I think).  Then I run `chown -R kibana:kibana .` and then I commit that image and push it to Docker Hub.

I use a slightly extended version of this image at https://github.com/kenwdelong/elk-docker.  You can see my travails in the `updates-5.4.0-notes.txt` file.

I'm just wondering if anyone else has this problem and how you are dealing with it.

**Comment by kenwdelong** [comment]
Having the same problem on 6.5.0... am I the only one who gets this?  I have a couple small customizations on this image but nothing that I would imagine causes this...

**Comment by pre1ude** [comment]
see the solution here
https://discuss.elastic.co/t/kibana-not-starting-stuck-at-optimizing-and-caching-bundles-after-upgrade/157870/8
