### ISSUE TITLE
Filebeat 1.1.0 multiline support

### ISSUE THREAD

**Issue by wesleymusgrove** [spujadas/elk-docker#23]
I'm using filebeat to ship multiline logs into logstash per your documentation, but was running into an issue when I realized that each line (like from a stack trace) was being considered as an individual log event.

I thought adding a multiline codec to the beats input filter would do the trick, but it didn't seem to have any effect at all:

    # 02-beats-input.conf
    input {
      beats {
        port => 5044
        ssl => true
        ssl_certificate => "/etc/pki/tls/certs/logstash-beats.crt"
        ssl_key => "/etc/pki/tls/private/logstash-beats.key"
        codec => multiline {
          # Grok pattern names are valid! :)
          pattern => "^%{TIMESTAMP_ISO8601} "
          negate => true
          what => previous
        }
      }
}

Thankfully this issue was recently being talked about here: https://github.com/elastic/filebeat/issues/301 and support announced here: https://www.elastic.co/blog/beats-1-1-0-and-winlogbeat-released.

So I just wanted to bring to your attention that it might be worth updating your docs to include the most recent version of filebeat and maybe a line about multiline support:
`https://download.elastic.co/beats/filebeat/filebeat_1.1.0_amd64.deb`

**Comment by spujadas** [comment]
Great tip, thanks. Will add some words in the documentation very shortly.
