### ISSUE TITLE
Troubleshooting docs addition

### ISSUE THREAD

**Issue by 20bt13github** [spujadas/elk-docker#231]
This is for the https://elk-docker.readthedocs.io/#troubleshooting
I ran into an issue twice the first time I couldnt figure out what the issue was but the second time I thought I'd get to the bottom of it, the docker would not startup it would stop after 30 tries to the Elasticsearch and nothing in the logs, the container would just stop. The issue was the ~/.docker/config.json had a proxy defined and localhost was not there in the no_proxy, I had used 127.0.0.1 all the time and it worked for my images. 

Anyways long story short, can we add one line to the troubleshooting section to ensure that if they are having a proxy defined in the ~/.docker/config.json then ensure that localhost is specified in the no_proxy (like below)
"proxies":
 {
   "default":
   {
     "httpProxy": "http://MY/OMNI/PRESENT/PROXY",
     "noProxy": ".DO/NOT/ACCESS/VIA/PROXY.com,10.*,127.0.0.1, **localhost**"
   }
 }

**Comment by spujadas** [comment]
Closing, see #232
