### ISSUE TITLE
Multiple pipelines are prevented by the hardcoded path.config param

### ISSUE THREAD

**Issue by michaelarnauts** [spujadas/elk-docker#233]
Since path.config is passed to the logstash binary, logstash can't use multiple pipelines.

More info here: https://github.com/elastic/logstash/issues/8420

**Comment by spujadas** [comment]
Thanks for reporting this, and thanks for the pointer which provided all the details needed to fix this.

It's working on my end with just the default pipeline, haven't tested with several pipelines but should work without a hitch (if you want to give the updated image a spin, it's in `sebp/elk:latest` — build is in progress).

**Comment by michaelarnauts** [comment]
I will test this after the weekend. Thanks!

**Comment by michaelarnauts** [comment]
Hmm, it now seems to use LS_HOME as config directory, and that's defaulted to `/opt/logstash/`, therefore, the config in `/etc/logstash` isn't used, except for the default single pipeline that globs everything in `/etc/logstash/conf.d`. Is this the behavior you've expected? Shouldn't LS_HOME be `/etc/logstash/`?

**Comment by spujadas** [comment]
This is the intended behaviour, the image uses the [directory layout from the .tar.gz package](https://www.elastic.co/guide/en/logstash/current/dir-layout.html#zip-targz-layout)… but I realise that this isn't actually documented, so will make sure I put in a word on this.
