### ISSUE TITLE
Can't send filebeat to logstash

### ISSUE THREAD

**Issue by nathanmarks** [spujadas/elk-docker#24]
I've tried hooking up to my elk-docker container from 2 different hosts (a filebeat container on another server, and even just running filebeat on my laptop).

I'm seeing the exact same issue from both -- I'm not sure if this is an issue with my network settings (ports are fine though...) or with the ELK config.

Here's where things seem to go wrong in the filebeat client logs (nothing of interest in the elk-docker logs), and it keeps backing off and retrying:

```
2016/02/17 05:05:02.403280 client.go:136: DBG  Try to publish 1922 events to logstash with window size 10
2016/02/17 05:05:02.436776 client.go:95: DBG  close connection
2016/02/17 05:05:02.436862 client.go:114: DBG  0 events out of 1922 events sent to logstash. Continue sending ...
2016/02/17 05:05:02.436881 single.go:76: INFO Error publishing events (retrying): lumberjack protocol error
2016/02/17 05:05:02.436894 single.go:152: INFO send fail
2016/02/17 05:05:02.436906 single.go:159: INFO backoff retry: 1s
```

Been trying to get this working for hours, so any ideas are helpful! Sorry if this issue has nothing to do with your image.

**Comment by nathanmarks** [comment]
Actually, that was with the cert removed from the client config. When I try provide the cert I get this (I haven't generated my own certs yet, just trying to get the ones you have in this repo working):

```
2016/02/17 05:50:59.921311 transport.go:125: ERR SSL client failed to connect with: x509: certificate signed by unknown authority
2016/02/17 05:50:59.921341 single.go:126: INFO Connecting error publishing events (retrying): x509: certificate signed by unknown authority
```

**Comment by spujadas** [comment]
This is usually due to an incorrect certificate file being used in the Filebeat config. Just to be sure, in your Filebeat configuration, are you pointing to the exact same `logstash-beats.crt` file as the one in the image? (If you're using a recent version of the image, the second line of the certificate file should end in `...NV`.)

If so, could you post steps to reproduce the issue, as well as the Filebeat version and your config file?

To troubleshoot further, I'll also need the output of (if you have an OpenSSL handy):

    openssl s_client -connect localhost:5044

And:

    openssl s_client -connect localhost:5044 -CAfile logstash-beats.crt

Where `logstash-beats.crt` is the file you're using with Filebeat.

**Comment by nathanmarks** [comment]
Thanks! That helped. The output helped me debug that particular issue. My server was sending the wrong certs.

Not sure if I'm still missing any pieces of the puzzle, but would you happen to know if this is related?

```
sympathetic-decisive-wolverine — 2016/02/17 07:10:52.880020 single.go:75: INFO Error publishing events (retrying): EOF
sympathetic-decisive-wolverine — 2016/02/17 07:10:52.880150 single.go:143: INFO send fail
sympathetic-decisive-wolverine — 2016/02/17 07:10:52.880187 single.go:150: INFO backoff retry: 1s
sympathetic-decisive-wolverine — 2016/02/17 07:10:53.894444 single.go:75: INFO Error publishing events (retrying): EOF
sympathetic-decisive-wolverine — 2016/02/17 07:10:53.894484 single.go:143: INFO send fail
sympathetic-decisive-wolverine — 2016/02/17 07:10:53.894498 single.go:150: INFO backoff retry: 2s
sympathetic-decisive-wolverine — 2016/02/17 07:10:55.906416 single.go:75: INFO Error publishing events (retrying): EOF
sympathetic-decisive-wolverine — 2016/02/17 07:10:55.906464 single.go:143: INFO send fail
sympathetic-decisive-wolverine — 2016/02/17 07:10:55.906479 single.go:150: INFO backoff retry: 4s
```

**Comment by spujadas** [comment]
Hard to say, really. Your connectivity should be good if changing the certificate solved the first part of the issue.

Tossing around some ideas (and will try to reproduce):
- Could you set your Filebeat log level to debug to see what it's EOF-ing on?
- Could you post your `filebeat.yml` as well as an excerpt from your log files (anonymised as required)?
- Anything on Logstash's side suggesting that it's receiving anything, and if so if it's choking on anything?
- Just to rule out connectivity issues completely, is there any chance you could try out the instructions from the documentation to have an nginx/filebeat container sending send logs to the ELK container?

**Comment by nathanmarks** [comment]
Additional debug (from my own setup, not your nginx example):

Lots of nginx access log publish debug output (this is the last one):
```
2016/02/17 12:20:12.813233 publish.go:100: DBG  Publish: {
  "@timestamp": "2016-02-17T12:20:10.280Z",
  "beat": {
    "hostname": "900c8766b67e",
    "name": "900c8766b67e"
  },
  "count": 1,
  "fields": null,
  "input_type": "log",
  "message": "169.229.3.91 - - [17/Feb/2016:12:11:54 +0000] \".\\x8C\\x98\\xD0\\xF1\\xB03\\x11\\xB6\\xEA\\xD4\\x14\\xD1sg/?\\x1C~\\xEA~\\xB7\\x02\\xCAuTT\\xB5\\xBA\\xA0\\xA7#\\x181\\xA1]J\\xBA\\x059\\xE3\\x92\\xB2\\xF4\\x86\\xDB\\xC6j$\\xCA\\x82\\xB0\\x18\\xD6(\\x80G\\x93\\xFC\\x0E\\x0B\\xBD\\x9B\\x94\" 400 166 \"-\" \"-\"",
  "offset": 41471,
  "source": "/host/var/log/nginx/access.log",
  "type": "nginx-access"
}
```

followed by:
```
2016/02/17 12:20:12.813268 preprocess.go:94: DBG  Forward preprocessed events
2016/02/17 12:20:12.813329 output.go:103: DBG  output worker: publish 200 events
2016/02/17 12:20:12.813833 client.go:96: DBG  Try to publish %!s(int=200) events to logstash with window size %!s(int=10)
2016/02/17 12:20:12.820562 client.go:79: DBG  %!s(int=0) events out of %!s(int=200) events sent to logstash. Continue sending ...
2016/02/17 12:20:12.820673 single.go:75: INFO Error publishing events (retrying): EOF
2016/02/17 12:20:12.820692 single.go:143: INFO send fail
2016/02/17 12:20:12.820709 single.go:150: INFO backoff retry: 1s
2016/02/17 12:20:13.823849 client.go:96: DBG  Try to publish %!s(int=200) events to logstash with window size %!s(int=10)
2016/02/17 12:20:13.833961 client.go:79: DBG  %!s(int=0) events out of %!s(int=200) events sent to logstash. Continue sending ...
2016/02/17 12:20:13.834114 single.go:75: INFO Error publishing events (retrying): EOF
2016/02/17 12:20:13.834652 single.go:143: INFO send fail
2016/02/17 12:20:13.834956 single.go:150: INFO backoff retry: 2s
```

Last 3 lines from the file:

```
141.212.122.193 - - [17/Feb/2016:01:45:54 +0000] "GET / HTTP/1.1" 301 178 "-" "Mozilla/5.0 zgrab/0.x"
137.116.71.170 - - [17/Feb/2016:07:29:12 +0000] "GET /robots.txt HTTP/1.1" 499 0 "-" "CSS Certificate Spider (http://www.css-security.com/certificatespider/)"
169.229.3.91 - - [17/Feb/2016:12:11:54 +0000] ".\x8C\x98\xD0\xF1\xB03\x11\xB6\xEA\xD4\x14\xD1sg/?\x1C~\xEA~\xB7\x02\xCAuTT\xB5\xBA\xA0\xA7#\x181\xA1]J\xBA\x059\xE3\x92\xB2\xF4\x86\xDB\xC6j$\xCA\x82\xB0\x18\xD6(\x80G\x93\xFC\x0E\x0B\xBD\x9B\x94" 400 166 "-" "-"
```


And my filebeat.yml:

```yaml
filebeat: 
  prospectors: 
    - 
      document_type: nginx-access
      paths: 
        - /usr/local/var/log/nginx/access.log
    - 
      document_type: nginx-error
      paths: 
        - /usr/local/var/log/nginx/error.log
output: 
  logstash: 
    enabled: true
    hosts: 
      - "xxxxxxxxxxxxxxxx:5044"
    tls: 
      certificate_authorities: 
        - /usr/local/etc/ssl/certs/logstash-beats.crt
```


Will try your nginx example shortly and report back.

**Comment by nathanmarks** [comment]
Here is the log output from your example container, another cert error this time:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{
  "acknowledged" : true
}
100   800  100    28  100   772     33    920 --:--:-- --:--:-- --:--:--   920
2016/02/17 12:45:23.290867 transport.go:125: ERR SSL client failed to connect with: x509: certificate is valid for *, not xxx.xxxxxxxxxxxxx.com
==> /var/log/nginx/access.log <==

==> /var/log/nginx/error.log <==
```

**Comment by spujadas** [comment]
OK, I'll start with the last one (using the example container): the certificate error is completely normal (see http://elk-docker.readthedocs.org/#certificates for background) as Filebeat is referencing ELK by a multi-part domain name (_xxx.xxx.com_) whereas the dummy certificate packaged with the ELK image is for a single-part domain name (e.g. just _elk_).
If it's not too much trouble, to try and establish a working baseline, could you add an alias (_elk_) pointing to your _xxx.xxx.com_ in your `/etc/hosts` and use this short-named alias in your `filebeat.yml`?

I'll attempt to reproduce your issue with the input you provided, but my first thought is that your set-up looks absolutely fine, so that's a bit puzzling.

**Comment by spujadas** [comment]
No sorry, can't reproduce I'm afraid :confused: 

I ran Filebeat 1.1 on Windows (to keep things interesting!), and everything is working as expected.

This is what I have.

ELK container started using:

    $ docker run -it --rm -p 5601:5601 -p 9200:9200 -p 5044:5044 -p 5000:5000 --name elk sebp/elk

_nginx-access.log_ (from your excerpt)

	141.212.122.193 - - [17/Feb/2016:01:45:54 +0000] "GET / HTTP/1.1" 301 178 "-" "Mozilla/5.0 zgrab/0.x"
	137.116.71.170 - - [17/Feb/2016:07:29:12 +0000] "GET /robots.txt HTTP/1.1" 499 0 "-" "CSS Certificate Spider (http://www.css-security.com/certificatespider/)"
	169.229.3.91 - - [17/Feb/2016:12:11:54 +0000] ".\x8C\x98\xD0\xF1\xB03\x11\xB6\xEA\xD4\x14\xD1sg/?\x1C~\xEA~\xB7\x02\xCAuTT\xB5\xBA\xA0\xA7#\x181\xA1]J\xBA\x059\xE3\x92\xB2\xF4\x86\xDB\xC6j$\xCA\x82\xB0\x18\xD6(\x80G\x93\xFC\x0E\x0B\xBD\x9B\x94" 400 166 "-" "-"

_filebeat.yml_ (just removed the _nginx-error.log_ bit and changed the directory names)

    filebeat: 
      prospectors: 
        - 
          document_type: nginx-access
          paths: 
            - nginx-access.log
    output: 
      logstash: 
        enabled: true
        hosts: 
          - "localhost:5044"
        tls: 
          certificate_authorities: 
            - logstash-beats.crt

(`logstash-beats.crt` is from the original ELK image)

**`> filebeat -v -e`**

	2016/02/17 20:04:50.194523 geolite.go:24: INFO GeoIP disabled: No paths were set
	 under output.geoip.paths
	2016/02/17 20:04:50.194523 logstash.go:106: INFO Max Retries set to: 3
	2016/02/17 20:04:50.331042 outputs.go:119: INFO Activated logstash as output plu
	gin.
	2016/02/17 20:04:50.331042 publish.go:288: INFO Publisher name: Home-W8
	2016/02/17 20:04:50.344731 async.go:78: INFO Flush Interval set to: 1s
	2016/02/17 20:04:50.344731 async.go:84: INFO Max Bulk Size set to: 2048
	2016/02/17 20:04:50.344731 beat.go:147: INFO Init Beat: filebeat; Version: 1.1.1

	2016/02/17 20:04:50.344731 beat.go:173: INFO filebeat sucessfully setup. Start r
	unning.
	2016/02/17 20:04:50.344731 registrar.go:66: INFO Registry file set to: XXX\.filebeat
	2016/02/17 20:04:50.345708 prospector.go:127: INFO Set ignore_older duration to
	24h0m0s
	2016/02/17 20:04:50.345708 prospector.go:127: INFO Set scan_frequency duration t
	o 10s
	2016/02/17 20:04:50.345708 prospector.go:84: INFO Invalid input type set:
	2016/02/17 20:04:50.345708 prospector.go:87: INFO Input type set to: log
	2016/02/17 20:04:50.345708 prospector.go:127: INFO Set backoff duration to 1s
	2016/02/17 20:04:50.345708 prospector.go:127: INFO Set max_backoff duration to 1
	0s
	2016/02/17 20:04:50.345708 prospector.go:107: INFO force_close_file is disabled
	2016/02/17 20:04:50.345708 prospector.go:137: INFO Starting prospector of type:
	log
	2016/02/17 20:04:50.346699 spooler.go:77: INFO Starting spooler: spool_size: 204
	8; idle_timeout: 5s
	2016/02/17 20:04:50.346699 crawler.go:78: INFO All prospectors initialised with
	0 states to persist
	2016/02/17 20:04:50.346699 registrar.go:83: INFO Starting Registrar
	2016/02/17 20:04:50.346699 publish.go:88: INFO Start sending events to output
	2016/02/17 20:04:50.346699 log.go:113: INFO Harvester started for file: nginx-ac
	cess.log
	2016/02/17 20:04:52.899515 publish.go:104: INFO Events sent: 2
	2016/02/17 20:04:52.902428 registrar.go:157: INFO Registry file updated. 1 state
	s written.
	2016/02/17 20:06:52.865605 publish.go:104: INFO Events sent: 1
	2016/02/17 20:06:52.872438 registrar.go:157: INFO Registry file updated. 1 state
	s written.

Outcome on http://localhost:5601

![screenshot-localhost 5601 2016-02-17 21-18-17](https://cloud.githubusercontent.com/assets/930566/13123359/12a615f4-d5bc-11e5-8009-25852724c65c.png)

I honestly have no idea what difference between our set-ups could cause polar opposite behaviours in what we're seeing on each of our ends.

Another thing you could try is to reproduce the issue using your log files + fresh Filebeat and Docker + the ELK image on an empty/clean VM (e.g. at DigitalOcean – no affiliation btw! – to have a neutral set-up) and see how it goes.

Other than that, I fear I'm running out of ideas.

**Comment by nathanmarks** [comment]
@spujadas Wow!

First off, thank you very much for taking the time to try and help with this. 

Based on your reply, I have a few things to try. I should be able to find the time over the next few days to have another go at getting this up and running. I will let you know what the results are.

Side note -- I am running filebeat inside a docker container, but the nginx server is **not** dockerized and the logs files are on a mounted volume. Do you know if this could have an impact?

Thank you again, I will let you know once I've run some more tests whether I managed to get it working or not!

**Comment by spujadas** [comment]
Well, volumes can sometimes be challenging (especially with regard to permissions, i.e. is the UID running Filebeat authorised to read the bound volume), but in your case I don't think it's the issue: your logs show `output worker: publish 200 events`, so Filebeat can read the logs, which is all that it needs from the volume (the `.filebeat` registry, which it needs to write to to keep track of what it has already parsed, should be in another directory in the container itself).
From the lack of error in the logs following the changes with the certificates, we should be able to assume that Filebeat has established a proper connection to Logstash (whether through an actual network or through Docker links).
So really, it _should_ just work!

Anyway, let me know how your tests go, and we'll take it further from there.

**Comment by basickarl** [comment]
I'm also getting the issue of not being able to ship to Logstash. I can ship directly to ElasticSearch without problems. You might want to fix the configuration files in Logstash for your Dockerfile. Also I've disabled SSL on everything. I'm however creating my own Dockerfile now (I am stresssed!) but you might want to look into it!

**Comment by spujadas** [comment]
@basickarl Happy to fix the config files as needed, but as it's working fine on my end (tested on a clean VM) I'll need more information on the issue you're facing (Filebeat config, how you're starting the container, logs from Filebeat and Logstash, connectivity test to Logstash etc.) and how you solved it, in order for me to reproduce the issue and correct it.
Once that's fixed, you should be able to (stresslessly!) create a `Dockerfile` that extends the _sebp/elk_ image by just adding/removing any config files you see fit, and everything should play along nicely.

**Comment by nathanmarks** [comment]
@spujadas FYI, I haven't forgotten about this, just a very busy week at work so went back to papertrail temporarily.

**Comment by spujadas** [comment]
@nathanmarks No prob at all! If @basickarl is facing the same issue as yours, it might give me another angle to investigate.

**Comment by MrCoder** [comment]
This may have been fixed in Filebeat 1.2. I saw this error before, but after upgrading to Filebeat 1.2, it has gone.

**Comment by spujadas** [comment]
Thanks for the tip @MrCoder!
@nathanmarks let me know if you get a chance to try this one out.

**Comment by spujadas** [comment]
Housecleaning: closing this issue, please feel free to reopen as needed.

**Comment by ayogi** [comment]
I am getting following error when executed:

`openssl s_client -connect localhost:5044`

```
CONNECTED(00000003)
140485635495568:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:184:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 289 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---

```

**Comment by spujadas** [comment]
@ayogi Yes, that error is completely expected: the client can connect (`CONNECTED`), which is a good first step, but as it can't check the server CA certificate an error is displayed. If you use the `-CAfile` option specified in my comment above (or use `-verify 0` to disable the verification of the server certificate altogether) the connection will be established properly.

**Comment by ayogi** [comment]
@spujadas I used -CAfile option, with that also it throws the same error. This test is for checking the connection. But the connection would be established by filebeat plugin running on the client machine.

**Comment by spujadas** [comment]
@ayogi Sorry I just realised I misread your error message. The message you're getting is due to Logstash not being ready, i.e. port 5044 has been opened by Docker, but nothing's available to handle the message behind it.

On a fresh VM on my side, after starting the container (and up to a minute after it being started):

    $ openssl s_client -connect localhost:5044
    CONNECTED(00000003)
    140368737076896:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:177:
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 0 bytes and written 295 bytes
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    ---

After everything's ready, the container's logs will show something like this:

    ==> /var/log/logstash/logstash.log <==
    {:timestamp=>"2016-06-22T17:37:17.947000+0000", :message=>"Pipeline main started"}

And then the `openssl s_client` command will work properly:

    $ openssl s_client -connect localhost:5044
    CONNECTED(00000003)
    depth=0 CN = *
    verify error:num=18:self signed certificate
    verify return:1
    depth=0 CN = *
    verify return:1
    ---
    Certificate chain
     0 s:/CN=*
       i:/CN=*
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    MIIC6zCCAdOgAwIBAgIJANPZwuf+5wTLMA0GCSqGSIb3DQEBCwUAMAwxCjAIBgNV
    BAMMASowHhcNMTUxMjI4MTA0NTMyWhcNMjUxMjI1MTA0NTMyWjAMMQowCAYDVQQD
    DAEqMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp+jHFvhyYKiPXc7k
    0c33f2QV+1hHNyW/uwcJbp5jG82cuQ41v70Z1+b2veBW4sUlDY3yAIEOPSUD8ASt
    9m72CAo4xlwYKDvm/Sa3KJtDk0NrQiz6PPyBUFsY+Bj3xn6Nz1RW5YaP+Q1Hjnks
    PEyQu4vLgfTSGYBHLD4gvs8wDWY7aaKf8DfuP7Ov74Qlj2GOxnmiDEF4tirlko0r
    qQcvBgujCqA7rNoG+QDmkn3VrxtX8mKF72bxQ7USCyoxD4cWV2mU2HD2Maed3KHj
    KAvDAzSyBMjI+qi9IlPN5MR7rVqUV0VlSKXBVPct6NG7x4WRwnoKjTXnr3CRADD0
    4uvbQQIDAQABo1AwTjAdBgNVHQ4EFgQUVFurgDwdcgnCYxszc0dWMWhB3DswHwYD
    VR0jBBgwFoAUVFurgDwdcgnCYxszc0dWMWhB3DswDAYDVR0TBAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAaLSytepMb5LXzOPr9OiuZjTk21a2C84k96f4uqGqKV/s
    okTTKD0NdeY/IUIINMq4/ERiqn6YDgPgHIYvQheWqnJ8ir69ODcYCpsMXIPau1ow
    T8c108BEHqBMEjkOQ5LrEjyvLa/29qJ5JsSSiULHvS917nVgY6xhcnRZ0AhuJkiI
    ARKXwpO5tqJi6BtgzX/3VDSOgVZbvX1uX51Fe9gWwPDgipnYaE/t9TGzJEhKwSah
    kNr+7RM+Glsv9rx1KcWcx4xxY3basG3/KwvsGAFPvk5tXbZ780VuNFTTZw7q3p8O
    Gk1zQUBOie0naS0afype5qFMPp586SF/2xAeb68gLg==
    -----END CERTIFICATE-----
    subject=/CN=*
    issuer=/CN=*
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 1327 bytes and written 513 bytes
    ---
    New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : ECDHE-RSA-AES256-SHA
        Session-ID: 576ACCCBA581A6A9C63D71E0FE155E9BF047C6520676514260CB62DAC934D60D
        Session-ID-ctx: 
        Master-Key: A1F4E99FD1AB0A4E4909BC12068E2B36676E665BB02616B2455FE388D7C865B07E191BCB346BE9E0E4054F3C56816FCF
        Key-Arg   : None
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1466617036
        Timeout   : 300 (sec)
        Verify return code: 18 (self signed certificate)
    ---

**Comment by cumacam** [comment]
@spujadas When I run "openssl s_client -connect localhost:5044 -CAfile logstash-beats.crt", I got the result following;
CONNECTED(00000003)
88508:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s23_clnt.c:593:

and on logstash side I got the log following;
[ERROR][org.logstash.beats.BeatsHandler] Exception: javax.net.ssl.SSLHandshakeException: error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL

What am I missing?

**Comment by spujadas** [comment]
@cumacam I'm going to venture a guess: the version of the OpenSSL libraries on your system may be outdated (you have a 0.9.8 version, current version is 1.1.0).

Here are the supported server ciphers (as reported by the excellent [sslscan](https://github.com/rbsec/sslscan)):

	>sslscan localhost:5044
	Version: 1.11.0 Windows 64-bit (Mingw)
	OpenSSL 1.0.2 22 Jan 2015

	Testing SSL server localhost on port 5044

	  TLS renegotiation:
	Session renegotiation not supported

	  TLS Compression:
	Compression disabled

	  Heartbleed:
	TLS 1.2 not vulnerable to heartbleed
	TLS 1.1 not vulnerable to heartbleed
	TLS 1.0 not vulnerable to heartbleed

	  Supported Server Cipher(s):
	Preferred TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
	Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
	Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256

	  SSL Certificate:
	Signature Algorithm: sha256WithRSAEncryption
	RSA Key Strength:    2048

	Subject:  *
	Issuer:   *

	Not valid before: Dec 28 10:45:32 2015 GMT
	Not valid after:  Dec 25 10:45:32 2025 GMT

To the best of my knowledge, OpenSSL 0.9.8 doesn't support TLSv1.2, so I'd recommend that you upgrade to a more recent version and try again.

If that doesn't help, then please consider opening a post over at https://discuss.elastic.co/c/beats/filebeat as your question isn't specific to this ELK image.

**Comment by drivard** [comment]
My server hostname was elk.project.example.com and as a matter of fact I was encountering the issue where the logs were throwing `ERR SSL client failed to connect with: x509: certificate is valid for *, not xxx.xxxxxxxxxxxxx.com` I did try the fix propose here by @spujadas  of adding an entry in the hosts file and it work for me. Thanks
