### ISSUE TITLE
please help：when pull the image ，unauthorized: authentication required

### ISSUE THREAD

**Issue by patience00** [spujadas/elk-docker#240]
![image](https://user-images.githubusercontent.com/35128024/48107537-048cef00-e27b-11e8-9143-adddfed57e0a.png)

**Comment by patience00** [comment]
![image](https://user-images.githubusercontent.com/35128024/48107906-233fb580-e27c-11e8-8fea-27f5b96d2ac7.png)
when execute this line ，then show this error

**Comment by spujadas** [comment]
Likely a temporary error with Docker Hub, look for help at https://hub.docker.com/help/ if it persists, nothing I can do I'm afraid.

**Comment by patience00** [comment]
Thank you
