### ISSUE TITLE
Remote JMX connection service

### ISSUE THREAD

**Issue by juno-velociti** [spujadas/elk-docker#247]
We are trying to enable visualvm access to the sebp/elk stack container.  How does one enable JMX for remote monitoring of Java Heap usage?  We have tried setting
environment:
    

> LS_JAVA_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=9900 -Dcom.sun.management.jmxremote.rmi.port=9900 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.local.only=false"
>

and 
>command:  ["java", \
		"-Dcom.sun.management.jmxremote", \
		"-Dcom.sun.management.jmxremote.ssl=false", \
		"-Dcom.sun.management.jmxremote.authenticate=false", \
                "-Dcom.sun.management.jmxremote.port=9900", \
        "-Dcom.sun.management.jmxremote.rmi.port=9900", \
        "-Djava.rmi.server.hostname=localhost", \
        "-Dcom.sun.management.jmxremote.local.only=false"]
>
in the docker-compose.yml with no positive results.  Is there another variable we should be using in the docker.compose.yml for setting JMX?

**Comment by kenwdelong** [comment]
Don't forget, you'd also need to expose port 9900 when you run the container.
