### ISSUE TITLE
Any plans to allow configuring auth?

### ISSUE THREAD

**Issue by rikonor** [spujadas/elk-docker#250]
Hey,

Thank you for this image.

I was wondering, in your `elkx` image you mention that it's now possible to use xpack directly with this image. I was hoping to set up an ELK stack with basic auth. Do you have any plans to copy over the setup code from `elkx` to this repo so that it's possible to specify passwords via env vars, etc?

**Comment by spujadas** [comment]
Hi,
No, I'm going to leave that as an exercise to the reader, the `elkx` image ended up slightly too hackish for my liking tbh 😅

**Comment by rikonor** [comment]
Thanks for the quick response. I ended up just running Caddy as a proxy for ELK with basic auth.

**Comment by spujadas** [comment]
Good idea, and keeps everything simple!
(Will probably mention this as a suggestion in the doc, actually.)
