### ISSUE TITLE
how to enable nginx parser

### ISSUE THREAD

**Issue by xralphack** [spujadas/elk-docker#252]
In the note, you mentioned the conf to parse the nginx access logs as following.

Note – The ELK image includes configuration items (/etc/logstash/conf.d/11-nginx.conf and /opt/logstash/patterns/nginx) to parse nginx access logs, as forwarded by the Filebeat instance above.

How can I activate the /opt/logstash/patterns/nginx conf, please help~

**Comment by spujadas** [comment]
They're already activated by default in the image, you don't need to do anything more.
