### ISSUE TITLE
Add APM

### ISSUE THREAD

**Issue by MrKumaPants** [spujadas/elk-docker#257]
Could we possibly get APM integrated into this as well? It's the only part of the stack that's still missing.

Rather not have to extend this and add in APM myself.

**Comment by spujadas** [comment]
Not entirely convinced that APM is needed with ELK in general, so would rather keep it out of the image and leave it up to the users who need it to extend the image themselves (in the same way as e.g. for plugins).

Having said that, I'm willing to keep an open mind, so if there is demand for this (please use the +1/-1 reaction) *and* if someone is willing to submit a PR (really haven't got time to do more than minimal maintenance on the image), then why not.

(If someone does want to have a stab at adding APM as a daemonised service to the image, please also make sure that there is an env var to selectively enable/disable APM — same as the other services, really.)
