### ISSUE TITLE
JAVA_HOME deprecation warning

### ISSUE THREAD

**Issue by tedder** [spujadas/elk-docker#261]
Hey sebp, I think this deprecation warning happened with the bump to java8:

```
 * Starting periodic command scheduler cron
   ...done.
 * Starting Elasticsearch Server
warning: Falling back to java on path. This behavior is deprecated. Specify JAVA_HOME
   ...done.
waiting for Elasticsearch to be up (1/90)
waiting for Elasticsearch to be up (2/90)
```

I also see it when installing a plugin through a Dockerfile, but the warning is happening even in a "default" image, I think. I'm running 670 right now.

**Comment by spujadas** [comment]
Indeed! Fixed, and re-build in progress.
