### ISSUE TITLE
ES_CONNECT_RETRY not taking effect in version sebp/elk:es241_l240_k461

### ISSUE THREAD

**Issue by takearun** [spujadas/elk-docker#267]
Hi,

ES_CONNECT_RETRY is not taking effect in version sebp/elk:es241_l240_k461

For some weird reasons I am try to create a 2.4 elastic cluster and in that version ES_CONNECT_RETRY doesn't seem to take effect.
Is there an alternative way to specify that?

**Comment by spujadas** [comment]
Well if you have to use this version, then your only option is to change the hardcoded value `30` in `start.sh` at  https://github.com/spujadas/elk-docker/blob/es241_l240_k461/start.sh#L68 to bump up the number of retries:

    while [ ! "$(curl localhost:9200 2> /dev/null)" -a $counter -lt 30  ]; do

**Comment by takearun** [comment]
Thank you for getting back to me. Really appreciate it.

Thanks,
Arun
