### ISSUE TITLE
Couldn't start the Elasticsearch in Openshift cluster

### ISSUE THREAD

**Issue by josephmichaelp** [spujadas/elk-docker#269]
After the build was complete and the image is running it produces an output like this:

> Couln't start Elasticsearch. Exiting.
> --
>   | Elasticsearch log follows below.
>   | cat: /var/log/elasticsearch/elasticsearch.log: No such file or directory

I'm already see the frequently issues on https://elk-docker.readthedocs.io/#frequent-issues that you make and kinda confused : 
1. Is it max map count issues or memory issues? 
2. What files do i need to change in the repository to make it work?
Any help or feedback would be great, Thanks!

**Comment by spujadas** [comment]
> Is it max map count issues or memory issues?

Usually with that message the issue is memory (https://elk-docker.readthedocs.io/#es-not-starting-not-enough-memory).

> What files do i need to change in the repository to make it work?

If you're out of memory, you need to assign more memory to the container, no files need to be changed.

**Comment by josephmichaelp** [comment]
Thank you for the response. I've been able to run the elk stack on the openshift cluster and run the kibana interface by changing the elasticsearch.yml discovery type to :

> discovery.type: single-node

But it seems that kibana couldn't find the index patterns that provided by the filebeat because the Logstash Beats is not responding and the interface is unable to open, do you have any other solutions on that? Thanks

**Comment by spujadas** [comment]
Could you please provide detailed steps to reproduce, including what you did to establish that there's an issue with Logstash Beats connectivity (e.g. client side logs from Filebeat)?
(The image works out of the box on a vanilla Linux, so want to establish what difference OpenShift introduces that could cause the image to behave differently.)

**Comment by josephmichaelp** [comment]
I'm new on the devops territory and sorry bit confused of what you want me to provide but basically i build the image on openshift by using new-app command line and it pull your code successfully(the only change i made on the fork repository was to change the discovery type on elasticsearch.yml to single-node). After that i'm expose the route for elk stack on port 5061 to access kibana ui because i'm started the elk stack all at once not separately. When i'm entering the kibana ui and trying to find its index pattern the filebeat didn't show up =

![Screen Shot 2019-05-06 at 14 36 44](https://user-images.githubusercontent.com/46431222/57212162-0149a480-700d-11e9-8f28-7e79a43e8541.png)

this show up if i'm check the system indices=

![Screen Shot 2019-05-06 at 14 37 06](https://user-images.githubusercontent.com/46431222/57212133-e5de9980-700c-11e9-9433-ae39e0a71905.png)

for real i'm not sure what happened that makes the image behave differently

**Comment by spujadas** [comment]
OK thanks, my question is:

>  the Logstash Beats is not responding and the interface is unable to open

how did you establish this? e.g.

- Are Filebeats's logs showing that it can't connect to Logstash?

- If so could it be a matter of opening the proper port on OpenShift?

- If not are the messages send to Logstash Beats showing up in Elasticsearch at http://<your-ip>:9200/_search?pretty?

- etc.

There are a number of reasons for logs not showing up in Kibana, hence my question on providing steps to reproduce (including on Filebeat's side).

**Comment by josephmichaelp** [comment]
There's this error thats shows up on the openshift log=
> 2019-04-30T05:38:29,474][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: undefined] Handling exception: javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
>   | [2019-04-30T05:38:29,474][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
>   | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST

This is the elasticsearh json=
![Screen Shot 2019-05-07 at 10 34 16](https://user-images.githubusercontent.com/46431222/57270520-d5cec480-70b5-11e9-8c61-f4e923c07904.png)

Also, about the port i don't think that there's a problem about it since i change nothing from the repository

**Comment by spujadas** [comment]
> There's this error thats shows up on the openshift log=

My guess is that you're missing the SSL configuration in `filebeat.yml` — see https://elk-docker.readthedocs.io/#forwarding-logs-filebeat

> Also, about the port i don't think that there's a problem about it since i change nothing from the repository

The port seems to be accessible according to your logs, but it may have not been the case due to factors outside of the control of the image (e.g. firewall), so needed to rule out this possibility.

**Comment by josephmichaelp** [comment]
> My guess is that you're missing the SSL configuration in filebeat.yml — see https://elk-docker.readthedocs.io/#forwarding-logs-filebeat
if i disable the ssl config what files that need to change in the repository? Also about your guide there's this sentence that says **In the sample configuration file, make sure that you replace elk in elk:5044 with the hostname or IP address of the ELK-serving host.** will it be working if i'm change the elk to my openshift kibana routes e.g. http://elk-stack-logging.xx.xx.xx.xxx.nip.io ?

> The port seems to be accessible according to your logs, but it may have not been the case due to factors outside of the control of the image (e.g. firewall), so needed to rule out this possibility.
It seems that the firewall factors play a part in it because i'm deploying the elk stack on company openshift cluster. The only logs i've been able to see on openshift logs were the logs if me or someone accessing Kibana routes in the browser.

**Comment by spujadas** [comment]
> if i disable the ssl config what files that need to change in the repository?

See https://elk-docker.readthedocs.io/#disabling-ssl-tls

>  will it be working if i'm change the elk to my openshift kibana routes e.g. http://elk-stack-logging.xx.xx.xx.xxx.nip.io ?

If your Elasticsearch service is running on elk-stack-logging.xx.xx.xx.xxx.nip.io:5044 then yes it will work.

> It seems that the firewall factors play a part in it because i'm deploying the elk stack on company openshift cluster.

As long as the ports listed in https://elk-docker.readthedocs.io/#usage are open you're fine. We've already established that ports 5044 and your Kibana port are open.

**Comment by diman82** [comment]
@josephmichaelp Can you please share your OpenShift configuration?
I'm having a hard time lifting this elk stack on OpenShift (various chmod, chown & crond.d errors)..
