### ISSUE TITLE
Couldn't start ELK on windows 10 system

### ISSUE THREAD

**Issue by bajjurisanthosh** [spujadas/elk-docker#270]
HI,

I am currently working on getting logs of a Windows 2010 system using the SEBP/ELK docker image
I installed docker image on windows 2010 and tried launching the container using the following command:
docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk 
container came up and while l am accessing the "docker ps -a" command I see the container is up and running but the ports 9200,5601,5044 ports are using "0.0.0.0" ip address, I tried changing the elasticsearch.yml file to the "localhost" or "Systems IP" but elastic search/kibana/logstash none of them can be accessed

Can anyone please let me know if I've to change any other files for ELK to come up and running or Any idea what I am missing here

Appreciate immediate response

**Comment by spujadas** [comment]
Haven't got a Windows 10 Docker set-up so can't help with this one I'm afraid.

**Comment by bajjurisanthosh** [comment]
> Haven't got a Windows 10 Docker set-up so can't help with this one I'm afraid.

Can you tell me from your experience whether this image works on any flavor of Windows ?

**Comment by spujadas** [comment]
No idea, I've only used it with Linux (native, and within a guest VM on a Windows host), and haven't heard of anyone using the image with Docker for Windows… but if someone who does sees this issue then maybe they can share some insight.

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
