### ISSUE TITLE
Clarification on how to configure image to accept glef..

### ISSUE THREAD

**Issue by moljnir** [spujadas/elk-docker#271]
Hi,

In an old thread ([Compatibility with gelf log driver? #53](https://github.com/spujadas/elk-docker/issues/53)) you alluded in your response to there being a need to augment the 30-output.conf. Being a complete novice, I tried following your advice with the latest sebp/elk image with a goal of being able to send gelf generated messages to the stack.

Does the change to the configuration file you mentioned prevent the standard behaviour or does it augment behaviour? (I have the container running and am able to see input from filebeat/metricbeat.. .but no gelf)

Could you post the changes required for 30-output.conf?

**Comment by spujadas** [comment]
If you replaced the default `30-output.conf` file with your own `30-output.conf` file, then whatever was in the old one is no longer applied, and only the configuration in your file (presumably as per https://www.elastic.co/guide/en/logstash/current/plugins-outputs-gelf.html) is applied.

I cannot provide individual support on using the image for specific use cases, and as the question is non-Docker-specific, please head over to http://discuss.elastic.co for help with the configuration.

(Closing as there is no issue with image.)
