### ISSUE TITLE
Adding additional node in the same host issue

### ISSUE THREAD

**Issue by qakart** [spujadas/elk-docker#273]

**Comment by qakart** [comment]
I have successfully deployed and tested in AWS but it's a bit slow all the team access hence I have tried to add an additional node using the same elasticsearch-slave.yaml it works.
I have another cron job whenever it crashes it will redeploy the master node. the issue is now the additional node is not linked and lot of unassignedshard in the master node. because of this unassigned node lot of data missing.
is there any workaround for this issue

**Comment by spujadas** [comment]
No idea, but I believe that this is a request for support related to setting up ELK clustering, rather than an issue with the image, so I would suggest heading over to http://discuss.elastic.co to ask for help.
