### ISSUE TITLE
Can't start 6.4.0 anymore since two days ago

### ISSUE THREAD

**Issue by Torah** [spujadas/elk-docker#277]
hi, I used this image very well when exec '/usr/local/bin/start.sh', but the docker seems failed since two days ago. Is there any update?

**Comment by spujadas** [comment]
No, there have been no updates since the image was initially published.

**Comment by Torah** [comment]
Thank you! Maybe it is related with the docker version or internet limits. I will try another way. BTW, it is hard to install this plugin within es500_l500_k500 tag: https://github.com/virusu/3D_kibana_charts_vis. It hints no license. I am so confused.

**Comment by Torah** [comment]
640 shutdown after sh finished. Maybe it's the problem of docker version. But it deserved a better shell to start this container.

**Comment by Torah** [comment]
It's very strange that now when run '/usr/local/bin/start.sh', it hints:
* starting periodic command scheduler cron [ok]
* starting Elasticsearch Server [ok]
waiting for Elasticsearch to be up
Couln't start Elasticsearch. Exiting.

**Comment by SpootDev** [comment]
Have you considered moving to 7.1.1 and "upgrading" the indexes in the gui?  After backups of course.  :)
