### ISSUE TITLE
filebeat broken pipe (no TLS)

### ISSUE THREAD

**Issue by mimmozzo** [spujadas/elk-docker#28]
Hi,

I have created a docker-compose configuration with 2 containers:

1. an ELK stack based on your docker image
2. a tomcat container, containing one web application

I have an issue trying to send log events from container 2 to 1 using Filebeat.

```
2016/03/21 10:21:12.463875 output.go:87: DBG  output worker: publish 145 events
2016/03/21 10:21:12.464030 client.go:136: DBG  Try to publish 145 events to logstash with window size 10
2016/03/21 10:21:12.481885 client.go:95: DBG  close connection
2016/03/21 10:21:12.482323 client.go:114: DBG  0 events out of 145 events sent to logstash. Continue sending ...
2016/03/21 10:21:12.482460 single.go:76: INFO Error publishing events (retrying): write tcp 172.18.0.3:36052->172.18.0.2:5044: write: broken pipe
2016/03/21 10:21:12.482553 single.go:152: INFO send fail
```
I can ping the ELK container from tomcat without issues.
This is the filebeat config on tomcat container:

```
output:
  logstash:
    enabled: true
    hosts: [ "elk:5044" ]
    timeout: 15
    index: filebeat

filebeat:
  prospectors:
    -
      paths:
        - /usr/local/tomcat/logs/*
```

and this is the docker-compose.yml:

```
version: '2'
services:

    elk:
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
            - "5000:5000"

    tomcat-ad:
        extends:
            file: common.yml
            service: tomcat7-jre7-baseline
        ports:
            - "8080:8080"
        volumes:
            - /home/ps/artifacts/webapp-1.0.1.war:/usr/local/tomcat/webapps/webapp.war
            - /home/ps/queues:/root/queues
        links:
            - elk
```

do you have any suggestions?
Thanks, best regards

Domenico

**Comment by mimmozzo** [comment]
Found out that SSL is set in your logstash configuration. Since I am creating a demo env, I would avoid the fuss of setting up certificates... I managed to replace this file:
`/etc/logstash/conf.d/02-beats-input.conf
`
with a custom one, containing:

```
input {
  beats {
    port => 5044
  }
}
```
and now the events are sent correctly.
I extended your ELK image creating this Dockerfile:

```
FROM sebp/elk
MAINTAINER "..."
ADD logstash/02-beats-input.conf /etc/logstash/conf.d/02-beats-input.conf 
```
Thanks anyway, hope this stays as reference to help somebody :+1:

**Comment by spujadas** [comment]
Thanks Domenico. As the need to disable SSL has come up a few times (especially for demo environments), I'll probably add some words on this in the documentation for the next release.
