### ISSUE TITLE
Logstash:6.3.0 xpack  does not work

### ISSUE THREAD

**Issue by fangwei57** [spujadas/elk-docker#282]
[2019-06-18T11:12:51,562][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://+logstash_system:xxxxxx@localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'http://localhost:9200/'"}
elk-master | [2019-06-18T11:12:55,615][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
elk-master | [2019-06-18T11:12:55,619][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'http://localhost:9200/'"}
elk-master | [2019-06-18T11:12:56,566][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://+logstash_system:xxxxxx@localhost:9200/, :path=>"/"}

**Comment by fangwei57** [comment]
Config: logstash.yml  
xpack.monitoring.elasticsearch.username: "logstash_system"
xpack.monitoring.elasticsearch.password: "xxxxxx"
xpack.monitoring.elasticsearch.url: ["http://localhost:9200"]
Config: 02-tcp-input.conf   
output {
       elasticsearch {
        hosts => [ "localhost:9200" ]
        index => "logback-%{+YYYY.MM.dd}"
        user => " logstash_system"
        password => "xxxxxx"
       }  
}

**Comment by fangwei57** [comment]
![image](https://user-images.githubusercontent.com/20739640/59651487-9919e100-91bc-11e9-95d1-b028b2ff0278.png)

I can login kibana with the user logstash_system

**Comment by spujadas** [comment]
> response code '401'

Suggests an issue with how authorisations are configured. Please seek guidance from https://discuss.elastic.co/ for help on this.

Closing as not an issue with the image itself.
