### ISSUE TITLE
elk701->720: Unauthorized error

### ISSUE THREAD

**Issue by Paul0M** [spujadas/elk-docker#285]
```
PUT my_index
{
  "mappings": {
    "properties": {
      "title": {
        "type":     "text",
        "analyzer": "standard"
      }
    }
  }
}
```

701
```
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "my_index"
}
```
But update to 720, 
1. then or 2. first Ok but after a while
```
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Unauthorized"
}
```
guess some configs wrong with the new [720] version

**Comment by spujadas** [comment]
Strange, especially as 7.2.0 doesn't introduce any breaking changes that would explain this (https://www.elastic.co/guide/en/elastic-stack/current/elasticsearch-breaking-changes.html).
At a cursory glance I can't see anything like this in both the Elasticsearch forums and issue tracker.

Leaving open in case someone has the same issue or has a suggestion.

**Comment by Paul0M** [comment]
thanks for the reply.
Maybe I've figured out the reason.
Large synonym.txt[such as **9M**] file will causes a lot problem, including gateway-timeout, Unauthorized and large index.
After removing this file or using smaller one, everything goes fine

**Comment by spujadas** [comment]
Thanks for the update!
