### ISSUE TITLE
Dockerfile missing -p flag

### ISSUE THREAD

**Issue by shanegeyer0** [spujadas/elk-docker#286]
After installing a Logstash protobuf plugin I attempted to rebuild the container following the instructions and got the following error:

mkdir: cannot create directory ‘/etc/pki/tls/private’: File exists
ERROR: Service 'elk' failed to build: The command '/bin/sh -c mkdir -p /etc/pki/tls/certs && mkdir /etc/pki/tls/private' returned a non-zero code: 1

I solved it by adding the -p flag to the Dockerfile on the first RUN command under the "certs/keys for Beats and Lumberjack input" heading

** existing Dockerfile command that gives error **
RUN mkdir -p /etc/pki/tls/certs && mkdir /etc/pki/tls/private

** fixed **
RUN mkdir -p /etc/pki/tls/certs && mkdir -p /etc/pki/tls/private

**Comment by spujadas** [comment]
Strange… but anyway, now fixed.
