### ISSUE TITLE
elasticsearch won't start: java exception

### ISSUE THREAD

**Issue by dmaziuk** [spujadas/elk-docker#288]
freshly installed alpine linux 3.10.1, docker 18.09, no other containers (or anything, for that matter) running:

```
...
[2019-07-29T21:24:37,745][INFO ][o.e.p.PluginsService     ] [elk] no plugins loaded
[2019-07-29T21:24:55,972][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [elk] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to create native process factories for Machine Learning]; nested: FileNotFoundException[/tmp/elasticsearch-4999364238318273181/controller_log_416 (No such file or directory)];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.2.0.jar:7.2.0]
```

**Comment by spujadas** [comment]
Haven't got a regular Alpine set-up, but created a VM with Alpine at DigitalOcean (using https://github.com/bontibon/digitalocean-alpine; `/etc/os-release` reports the version of Alpine as 3.10.0), installed Docker (`apk add docker`), set the VM max map count (`sysctl -w vm.max_map_count=262144`), and started ELK as usual (`docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk`) — everything started up normally, so no idea I'm afraid.

The Elastic forums _may_ have a few ideas to try out (e.g. https://discuss.elastic.co/t/elasticsearchexception-failed-to-create-native-process-factories-for-machine-learning-version-7-1-0/182888), but I don't know why a fresh Alpine with the latest image would behave inconsistently.

**Comment by dmaziuk** [comment]
disabling ml xpack worked on the other setup: with 3 containers and `docker-compose`. AFAICT there is something missing in basic alpine install, or somewhere, but without much digging inside the container I've no idea what it might be.

**Comment by dmaziuk** [comment]
PS the other thing they have in the forums is needing CPU instructions, sse4 or whatever, for ML. this box is an older Opteron but I don't think it's **that** old... haven't checked, though.

**Comment by spujadas** [comment]
Interesting, thanks very much for the update!
