### ISSUE TITLE
Unable to find logstash-plugin

### ISSUE THREAD

**Issue by owen198** [spujadas/elk-docker#290]
Hi, 

I'd like to install a plugin named 'elapsed'
However, I cannot find command `bin/logstash-plugin`
Is there any way to check plugin 'elapsed' already been installed or install manually?

Thanks~

**Comment by spujadas** [comment]
It's in ${LOGSTASH_HOME} (see https://elk-docker.readthedocs.io/#installing-logstash-plugins), so for instance `${LOGSTASH_HOME}/bin/logstash-plugin list` will display the list of installed plugins.
