### ISSUE TITLE
Reaching Elasticsearch from ELK stack outside docker

### ISSUE THREAD

**Issue by codecandy2015** [spujadas/elk-docker#292]
I am trying to reach ES via a GO Client - the official GO Client from ES is able to connect. however, I am trying to see is this client is reaching the ES instance - https://github.com/olivere/elastic

The client is not able to connect to ELK docker based Elasticsearch as  the transport publish address of the instance is always 172.20.0.2:9200

I tried to change this with the following command -
docker run -d -p 5601:5601 -p 9200:9200 -p 5044:5044 --name elk sebp/elk elasticsearch -Enetwork.publish_host=local -Enetwork.host=local,site

the docker container starts.. how ever the http "publish_address": "172.20.0.2:9200"

I also tried with a docker-compose like,

- cluster.name=eslocal
- bootstrap.memory_lock=true
- http.host=127.0.0.1
- transport.host=127.0.0.1
- network.publish_host=127.0.0.1
- transport.publish_port=9200
Neither is this working.. 

I tried it using a custom elasticsearch yml file.. like in here:- https://elk-docker.readthedocs.io/#setting-up-an-elasticsearch-cluster 

I gave the following commands -
docker run -it --rm=true -p 9200:9200 -p 9300:9300 -v c:/dev/docker/elk/docker-compose.yml:/etc/elasticsearch/elasticsearch.yml sebp/elk

I am getting this error - Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/dev/docker/elk/docker-compose.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/854ae312e4b97ff0412a822104f1823542f1dd0c053b35f69b8de8c6a55f809a/merged\\\" at \\\"/var/lib/docker/overlay2/854ae312e4b97ff0412a822104f1823542f1dd0c053b35f69b8de8c6a55f809a/merged/etc/elasticsearch/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

I need to use the ELK stack and I wonder if there is any work around or the right way to use it perhaps ? Any help is appreciated.

thanks
CC

**Comment by spujadas** [comment]
Out of the box in this image, Elasticsearch binds to all available IP addresses, so no need to change anything to expose/publish Elasticsearch on your host.
The IP address that you want to connect to, however, may not be 172.20.0.2:9200 (which looks like an internal IP address used by Docker): make sure that the address is the "public" IP address of your host (e.g. 192.168.x.x on a typical home network).

Also:

>     docker run -it --rm=true -p 9200:9200 -p 9300:9300 \
>       -v c:/dev/docker/elk/docker-compose.yml:/etc/elasticsearch/elasticsearch.yml
>       sebp/elk

Pretty sure this isn't what you want to do: it looks like you want to use `c:/dev/docker/elk/docker-compose.yml` (a Docker compose configuration file?) as Elasticsearch's configuration file, in addition to the file not appearing to exist.

I would recommend following https://elk-docker.readthedocs.io/#usage to make sure that all services are running and that you can send logs normally (first using https://elk-docker.readthedocs.io/#creating-dummy-log-entry, then perhaps using Filebeat as per https://elk-docker.readthedocs.io/#forwarding-logs) and that the basic communication between the services is working properly, before moving on to using the Go client.
