### ISSUE TITLE
unknown setting [default.path.conf]

### ISSUE THREAD

**Issue by agencia** [spujadas/elk-docker#293]
Im a mac user, running a simple `docker run -it sebp/elk bash` fails go me
https://gist.github.com/agencia/220e0e11330fc37b09eb196bf7d6cf62

**Comment by spujadas** [comment]
Yeah I didn't realise the website for the documentation wasn't up to date, have fixed it now.

https://elk-docker.readthedocs.io/#es-not-starting now reads:

		$ ES_PATH_CONF=/etc/elasticsearch gosu elasticsearch /opt/elasticsearch/bin/elasticsearch \
			-Epath.logs=/var/log/elasticsearch
			-Epath.data=/var/lib/elasticsearch
