### ISSUE TITLE
port 9300 is not exposed

### ISSUE THREAD

**Issue by eamonnfaherty** [spujadas/elk-docker#3]
Hey,

Thanks for your contribution! I have been using your image for a while and it has worked well for me.

I am now wanting to use my elk instance as a data store for a scala project but the library uses TCP connections to elasticsearch and not http so port 9300 is needed.

I have created pull request #2  could you please merge it so I can continue to use your image please :smile:

**Comment by spujadas** [comment]
@eamonnfaherty Hi, most happy to oblige (PR merged)! :smiley:
Cheers
