### ISSUE TITLE
Unable to revive connection: http://localhost:9200/

### ISSUE THREAD

**Issue by x1wins** [spujadas/elk-docker#304]
kibana is not working with localhost:9200

> docker exec -it elk-docker_elk_1 /bin/bash
> cat /var/log/kibana/kibana5.log

i get following log 

`{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["info","plugins-system"],"pid":312,"message":"Setting up [4] plugins: [security,translations,inspector,data]"}
{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["info","plugins","security"],"pid":312,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["warning","plugins","security","config"],"pid":312,"message":"Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["warning","plugins","security","config"],"pid":312,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["info","plugins","translations"],"pid":312,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["info","plugins","data"],"pid":312,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2019-10-16T00:11:46Z","tags":["info","plugins-system"],"pid":312,"message":"Starting [3] plugins: [security,translations,data]"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:kibana@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:elasticsearch@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:xpack_main@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:telemetry@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:graph@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:monitoring@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:spaces@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:security@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:searchprofiler@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:ml@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:tilemap@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:watcher@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:grokdebugger@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:dashboard_mode@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:logstash@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:beats_management@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:apm_oss@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:apm@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:code@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:data@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:visualizations@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:interpreter@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:tile_map@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:task_manager@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:maps@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:canvas@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:license_management@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:cloud@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:index_management@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:console@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:console_extensions@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:index_lifecycle_management@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:metrics@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:infra@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["status","plugin:rollup@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:12Z","tags":["info","siem"],"pid":312,"message":"Plugin initializing"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["info","siem"],"pid":312,"message":"Plugin done initializing"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:siem@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:remote_clusters@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:cross_cluster_replication@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:upgrade_assistant@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:uptime@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:oss_telemetry@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:file_upload@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["warning","encrypted_saved_objects"],"pid":312,"message":"Generating a random key for xpack.encrypted_saved_objects.encryptionKey. To be able to decrypt encrypted saved objects attributes after restart, please set xpack.encrypted_saved_objects.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:encrypted_saved_objects@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:snapshot_restore@7.4.0","info"],"pid":312,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:kibana_react@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:region_map@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:timelion@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:ui_metric@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:markdown_vis@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:metric_vis@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:table_vis@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:tagcloud@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:13Z","tags":["status","plugin:vega@7.4.0","info"],"pid":312,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["error","elasticsearch","admin"],"pid":312,"message":"Request error, retrying\nHEAD http://localhost:9200/.apm-agent-configuration => connect ECONNREFUSED 127.0.0.1:9200"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["error","elasticsearch","admin"],"pid":312,"message":"Request error, retrying\nGET http://localhost:9200/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip => connect ECONNREFUSED 127.0.0.1:9200"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:xpack_main@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:graph@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:spaces@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:searchprofiler@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:ml@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:tilemap@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:watcher@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:grokdebugger@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:logstash@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:beats_management@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:maps@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:index_management@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:index_lifecycle_management@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:rollup@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:remote_clusters@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:cross_cluster_replication@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:file_upload@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:snapshot_restore@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["status","plugin:elasticsearch@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from yellow to red - No Living connections","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["error","elasticsearch","data"],"pid":312,"message":"Request error, retrying\nGET http://localhost:9200/_xpack => connect ECONNREFUSED 127.0.0.1:9200"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["warning","elasticsearch","data"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["license","warning","xpack"],"pid":312,"message":"License information from the X-Pack plugin could not be obtained from Elasticsearch for the [data] cluster. Error: No Living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:14Z","tags":["warning","elasticsearch","data"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:17Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:17Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["reporting","warning"],"pid":312,"message":"Generating a random key for xpack.reporting.encryptionKey. To prevent pending reports from failing on restart, please set xpack.reporting.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["status","plugin:reporting@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from uninitialized to red - No Living connections","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["status","plugin:security@7.4.0","error"],"pid":312,"state":"red","message":"Status changed from green to red - No Living connections","prevState":"green","prevMsg":"Ready"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["reporting","warning"],"pid":312,"message":"The Reporting plugin encountered issues launching Chromium in a self-test. You may have trouble generating reports: [Error: Failed to launch chrome!\n[1016/001318.402431:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale \n[1016/001318.402881:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.\n#0 0x55daccf74bf9 <unknown>\n#1 0x55daccee1783 <unknown>\n#2 0x55daccef4e23 <unknown>\n#3 0x55dace3b32ee <unknown>\n#4 0x55daccea10f8 <unknown>\n#5 0x55dace3b998c <unknown>\n#6 0x55dacce9aad1 <unknown>\n#7 0x55dacceddc3d <unknown>\n#8 0x55daccedd9bb <unknown>\n#9 0x7f663c8abb97 __libc_start_main\n#10 0x55dacb3e402a _start\n\nReceived signal 6\n#0 0x55daccf74bf9 <unknown>\n#1 0x55daccee1783 <unknown>\n#2 0x55daccf74781 <unknown>\n#3 0x7f663e034890 <unknown>\n#4 0x7f663c8c8e97 gsignal\n#5 0x7f663c8ca801 abort\n#6 0x55daccf735c5 <unknown>\n#7 0x55daccef5107 <unknown>\n#8 0x55dace3b32ee <unknown>\n#9 0x55daccea10f8 <unknown>\n#10 0x55dace3b998c <unknown>\n#11 0x55dacce9aad1 <unknown>\n#12 0x55dacceddc3d <unknown>\n#13 0x55daccedd9bb <unknown>\n#14 0x7f663c8abb97 __libc_start_main\n#15 0x55dacb3e402a _start\n  r8: 0000000000000000  r9: 00007ffdcfece990 r10: 0000000000000008 r11: 0000000000000246\n r12: 00007ffdcfecfc58 r13: 00002de05e483b80 r14: 00007ffdcfecfc60 r15: 00007ffdcfecfc68\n  di: 0000000000000002  si: 00007ffdcfece990  bp: 00007ffdcfecebe0  bx: 00007ffdcfecec38\n  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f663c8c8e97  sp: 00007ffdcfece990\n  ip: 00007f663c8c8e97 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000\n trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000\n[end of stack trace]\nCalling _exit(1). Core file will not be generated.\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n]"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["reporting","warning"],"pid":312,"message":"See Chromium's log output at \"/opt/kibana/data/headless_shell-linux/chrome_debug.log\""}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["reporting","warning"],"pid":312,"message":"Reporting plugin self-check failed. Please check the Kibana Reporting settings. Error: Could not close browser client handle!"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["warning","elasticsearch","data"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["warning","elasticsearch","data"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:18Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:19Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:19Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:21Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:21Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:22Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:22Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:24Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:24Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:27Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:27Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:29Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:29Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:32Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:32Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:34Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:34Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:37Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:37Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:39Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:39Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:42Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:42Z","tags":["warning","elasticsearch","admin"],"pid":312,"message":"No living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:44Z","tags":["warning","elasticsearch","data"],"pid":312,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-10-16T00:13:44Z","tags":["license","warning","xpack"],"pid":312,"message":"License information from the X-Pack plugin could not be obtained from Elasticsearch for the [data] cluster. Error: No Living connections"}
{"type":"log","@timestamp":"2019-10-16T00:13:44Z","tags":["warning","elasticsearch","data"],"pid":312,"message":"No living connections"}`

**Comment by x1wins** [comment]
And I found solution
https://www.elastic.co/guide/en/kibana/6.7/using-kibana-with-security.html

1. `open kibana.yml`
2. Add config
> elasticsearch.username: "kibana"
> elasticsearch.password: "kibanapassword"
> xpack.security.encryptionKey: "something_at_least_32_characters"
> xpack.security.sessionTimeout: 600000

**Comment by x1wins** [comment]
Can you change issue close?

**Comment by spujadas** [comment]
Hard to tell just looking at these logs. Seems that Elasticsearch is not longer responding for some reason, so that explains why Kibana is no longer working.

> And I found solution but it's not working
> https://www.elastic.co/guide/en/kibana/6.7/using-kibana-with-security.html

Unless you changed the configuration of the image, there's no need to do this: the default image should work as is.

What are Elasticsearch's logs saying?

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
