### ISSUE TITLE
Missing documentation to change logstash configuration

### ISSUE THREAD

**Issue by Schabernack** [spujadas/elk-docker#31]
Hi,

Could you provide some pointers as to what the recommended way is to change the logstash configuration (in my case, i need to add the json filter for incoming events).

When i was looking into this, i read that it is against recommended practices to log into the container and do the changes right there? This means i would have to fork your container and replace the configuration file that is provided by default? 

What would be a good way to set this up if i am in the process of creating a config file and i need to edit and reapply my changes several times before the config is fully finished.

Thanks.

**Comment by spujadas** [comment]
Hi,

The general idea is in the documentation (http://elk-docker.readthedocs.org/#extending-the-image), but I'll add some more detailed information on changing configuration files.

In essence, here are your main options:
- You could fork the source of the image, change the config file and rebuild the image, but then you'd lose any additional goodness from future versions of the original image (unless you fork and update it on your side each time there's an upgrade).
- You could bind-mount (see https://docs.docker.com/engine/userguide/containers/dockervolumes/) your local configuration file to a configuration file within the container at runtime (e.g. `docker run ... -v /path/to/your-30-output.conf:/etc/logstash/conf.d/30-output.conf`), thus enabling you to tinker with the configuration file locally and have the changes dynamically update in the running container.
- You could also (if you're just playing around and testing things) `exec` into the running container and change the config files there, but that is indeed bad practice as the changes won't be persistent.
- Once you've finalised your configuration, you could make things permanent by creating a Dockerfile that extends the original image and replaces Logstash's config file with yours (or adds new config files). Goes something like this:

		FROM seb/elk

		ADD /path/to/your-logstash.conf /etc/logstash/conf.d/your-logstash.conf

Hope that helps.

**Comment by spujadas** [comment]
Closing following documentation update, feel free to reopen if still unclear.

**Comment by Schabernack** [comment]
Thanks a  lot for your help Sébastien, works great.

**Comment by spujadas** [comment]
Cheers!
