### ISSUE TITLE
dockerhub versions > 740 don't exist

### ISSUE THREAD

**Issue by tedder** [spujadas/elk-docker#311]
Hi sebp, [it looks like the last tag, aside from `latest`, that you have posted to dockerhub is 740](https://hub.docker.com/r/sebp/elk/tags?page=1). You imply that the tags should exist but they aren't there. IDK how you are publishing the tags, but .. you aren't publishing the tags :)

**Comment by spujadas** [comment]
The tags _do_ exist in the source repo but for some reason they hadn't been picked up by DockerHub. Happens sometimes.
Anyway, I've manually recreated the build rules for the missing tags, and the corresponding images are being built as I type this.
I've recreated the auto-build rule in DockerHub, and it seems to have picked up the latest tag for version 7.6.0 which I've just created, so the issue has been fixed for the time being.

**Comment by tedder** [comment]
great, thanks! building on top of it now.
