### ISSUE TITLE
future versions of Elasticsearch will require Java 11  fail

### ISSUE THREAD

**Issue by chenyongze** [spujadas/elk-docker#313]
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement

![image](https://user-images.githubusercontent.com/4531363/75742025-5e0a0e80-5d47-11ea-9276-0943b7d7be29.png)

**Comment by chenyongze** [comment]
Couldn't start Elasticsearch. Exiting.
Elasticsearch log follows below.
cat: /var/log/elasticsearch/elasticsearch.log: No such file or directory

**Comment by spujadas** [comment]
> future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement

It's just a warning that can be safely ignored.

> Couldn't start Elasticsearch. Exiting.
> Elasticsearch log follows below.
> cat: /var/log/elasticsearch/elasticsearch.log: No such file or directory

See https://elk-docker.readthedocs.io/#es-not-starting-not-enough-memory
