### ISSUE TITLE
Documentation refine: add "&size=BIGNUMBER"

### ISSUE THREAD

**Issue by Dongrc** [spujadas/elk-docker#315]
At the "Creating a dummy log entry" section, after execute the simple logstash cmd, the doc says:

> If you browse to http://<your-host>:9200/_search?pretty (e.g. http://localhost:9200/_search?pretty for a local native instance of Docker) you'll see that Elasticsearch has indexed the entry:

But I'm not able to see the expected output. Thought either logstash or elasticsearch went wrong, I spent quite some time digging around logs and googling.
Finally it turns out that **nothing is wrong**. It's just that the default size of elasticsearch is only 10 and not enough to see the expected output.
Add **"&size=BIGNUMBER"** to url solved the problem.
>  http://localhost:9200/_search?pretty&size=1000

Maybe some refinement of the documentation will help other new-comers from stumbling on the stupid problem.

**Comment by spujadas** [comment]
Great idea, thanks!
