### ISSUE TITLE
Install on Mac os with docker-machine, Virtualbox vm

### ISSUE THREAD

**Issue by RajanBhattIntapp** [spujadas/elk-docker#317]
I am getting following error on console
I am not able to understand unable to "revive" connection
Any guidance would be appreciated

{"type":"log","@timestamp":"2020-04-06T23:02:25Z","tags":["warning","elasticsearch","admin"],"pid":293,"message":"No living connections"}
{"type":"log","@timestamp":"2020-04-06T23:02:27Z","tags":["warning","elasticsearch","admin"],"pid":293,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2020-04-06T23:02:27Z","tags":["warning","elasticsearch","admin"],"pid":293,"message":"No living connections"}
{"type":"log","@timestamp":"2020-04-06T23:02:30Z","tags":["warning","elasticsearch","admin"],"pid":293,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2020-04-06T23

**Comment by spujadas** [comment]
Don't have a Mac so users who do may want to chime in, but to narrow down the issue could you `docker exec` into the container to check that Elasticsearch is running and, if so, to make sure you can run `curl localhost:9200`?

**Comment by tenaz3** [comment]
I have the same issue, and ES is not running, and can not curl it, but the logs does not say much  =/

**Comment by spujadas** [comment]
Don't know about Macs, but if ES is not running, it was probably ended due to insufficient memory.

**Comment by tenaz3** [comment]
Indeed was the issue
