### ISSUE TITLE
How can I disable Machine Learning?

### ISSUE THREAD

**Issue by raratiru** [spujadas/elk-docker#320]
I am trying to configure this [setting](https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-settings.html#general-ml-settings):

`xpack.ml.enabled: false`

But I cannot figure out how to do it!

**Comment by spujadas** [comment]
The general approach would be to replace the default configuration file for Elasticsearch in the image with a configuration file that suits your needs, using bind-mounting for instance (see https://elk-docker.readthedocs.io/#tweaking-image).

**Comment by raratiru** [comment]
Thank you!
