### ISSUE TITLE
max virtual memory areas vm.max_map_count [65530] using docker over PLESK

### ISSUE THREAD

**Issue by cibernicola** [spujadas/elk-docker#322]
I'm trying to implement ELK version 7.6.1
With the serial configuration parameters and having modified the vm.max_map_count parameter to 262144

When running grep vm.max_map_count /etc/sysctl.conf
after a reset the result is
`vm.max_map_count=262144.`

But when I try to start the Docker instance, I get the error 
`1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

Characteristics:
32GB of RAM available. 

OS
Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic

Plesk Obsidian 18.0.26 
Docker extension for Plesk version 1.4.6-168

Any ideas or suggestions?

**Comment by spujadas** [comment]
I understand that after a reboot `sysctl vm.max_map_count` is still 65530, ignoring what you put in `/etc/sysctl.conf`, is that right?

Does Plesk enable you to modify the system values? (e.g. can you try https://talk.plesk.com/threads/docker-elasticsearch-6-8-6-memory-error.354868/)

**Comment by cibernicola** [comment]
Hello
The configuration is correct and permanent, as I mentioned in the first post, executing the 
sysctl vm.max_map_count
the result is vm.max_map_count=262144

It seems that at some point "someone" is not able to either read or transmit this configuration.

**Comment by spujadas** [comment]
Looks like a Docker for Plesk issue, or at the very least a question for the Plesk experts – would advise heading over to a Plesk forum for help.
Can't help more I'm afraid.

**Comment by hajimurtaza** [comment]
OS: Windows 10, version 2004, build 19041
VM : WSL2 Ubuntu 20.04

I faced similar issue, and was able to run `sudo sysctl -w vm.max_map_count=262144` on my linux distro where docker is running, the issue was fixed. 

Definitely issue with Plesk. Maybe the user is changing in your case who has less permissions.

**Comment by spujadas** [comment]
Closing as likely Plesk-related.

**Comment by cibernicola** [comment]
> I faced similar issue, and was able to run `sudo sysctl -w vm.max_map_count=262144` on my linux distro where docker is running, the issue was fixed.

That was the first thing I did, all right, but apparently Plesk doesn't realize or admit it's modification from the outside. So the plesk-plugin docker combination for Plesk-Ubuntu and this ELK distribution are not compatible.
