### ISSUE TITLE
Kibana crash with Chromium sandbox problem on CentOS 7 host

### ISSUE THREAD

**Issue by karlika** [spujadas/elk-docker#324]
Running sebp/elk:761 on a CentOS 7.7.1908 host (Kernel 3.10.0-1062.18.1.el7.x86_64) with Docker 19.03.8 Kibana crashes on boot with the following error:

{"type":"error","@timestamp":"2020-04-30T11:27:44Z","tags":["reporting","error"],"pid":263,"level":"error","error":{"message":"Failed to launch chrome!\n[0430/112744.726611:WARNING:resource_bundle.cc(358)] locale_file_path.empty() for locale \n[0430/112744.727057:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.\n#0 0x559250ed4bf9 <unknown>\n#1 0x559250e41783 <unknown>\n#2 0x559250e54e23 <unknown>\n#3 0x5592523132ee <unknown>\n#4 0x559250e010f8 <unknown>\n#5 0x55925231998c <unknown>\n#6 0x559250dfaad1 <unknown>\n#7 0x559250e3dc3d <unknown>\n#8 0x559250e3d9bb <unknown>\n#9 0x7f1ff8f9ab97 __libc_start_main\n#10 0x55924f34402a _start\n\nReceived signal 6\n#0 0x559250ed4bf9 <unknown>\n#1 0x559250e41783 <unknown>\n#2 0x559250ed4781 <unknown>\n#3 0x7f1ffa723890 <unknown>\n#4 0x7f1ff8fb7e97 gsignal\n#5 0x7f1ff8fb9801 abort\n#6 0x559250ed35c5 <unknown>\n#7 0x559250e55107 <unknown>\n#8 0x5592523132ee <unknown>\n#9 0x559250e010f8 <unknown>\n#10 0x55925231998c <unknown>\n#11 0x559250dfaad1 <unknown>\n#12 0x559250e3dc3d <unknown>\n#13 0x559250e3d9bb <unknown>\n#14 0x7f1ff8f9ab97 __libc_start_main\n#15 0x55924f34402a _start\n  r8: 0000000000000000  r9: 00007ffca2639c60 r10: 0000000000000008 r11: 0000000000000246\n r12: 00007ffca263af28 r13: 0000395149badb80 r14: 00007ffca263af30 r15: 00007ffca263af38\n  di: 0000000000000002  si: 00007ffca2639c60  bp: 00007ffca2639eb0  bx: 00007ffca2639f08\n  dx: 0000000000000000  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007ffca2639c60\n  ip: 00007f1ff8fb7e97 efl: 0000000000000246 cgf: 0000000000000033 erf: 0000000000000000\n trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000\n[end of stack trace]\nCalling _exit(1). Core file will not be generated.\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"

**Comment by spujadas** [comment]
This is actually "normal" (https://www.elastic.co/guide/en/kibana/current/reporting-chromium-sandbox.html#_docker). The next two lines should read something like:

    {"type":"log","@timestamp":"2020-05-01T09:03:32Z","tags":["reporting","warning"],"pid":231,"message":"See Chromium's log output at \"/opt/kibana/data/headless_shell-linux/chrome_debug.log\""}
    {"type":"log","@timestamp":"2020-05-01T09:03:32Z","tags":["reporting","warning"],"pid":231,"message":"Reporting plugin self-check generated a warning: Error: Could not close browser client handle!"}

The reporting module has crashed, but Kibana itself (and the rest of the modules) should run just fine.

If you absolutely need the reporting module, my suggestions are to either:

- disable the sandbox (see https://www.elastic.co/guide/en/kibana/current/reporting-settings-kb.html#reporting-chromium-settings and https://www.elastic.co/guide/en/kibana/current/reporting-chromium-sandbox.html)

- adjust the Dockerfile and way you start the container as suggested at https://github.com/puppeteer/puppeteer/issues/3451#issuecomment-523961368
