### ISSUE TITLE
Feature request: build Apache 2.0 ELK images

### ISSUE THREAD

**Issue by williamtheaker** [spujadas/elk-docker#327]
It would be useful to offer an image without including any proprietary Elastic License code for people who only want to use the free/libre Apache 2.0 builds.

This could be achieved by prepending oss- to version numbers:
`ARG ELK_VERSION=oss-7.7.1`

**Comment by spujadas** [comment]
Good idea, you can give the image with the tag `oss-780` a try once it's finished building.

**Comment by williamtheaker** [comment]
Everything seems to work great so far on oss-780. Thanks!
