### ISSUE TITLE
geoip plugin

### ISSUE THREAD

**Issue by cb1234** [spujadas/elk-docker#328]
i am trying to get geoip plugin installed

FROM sebp/elk

NV ES_HOME /opt/elasticsearch
WORKDIR ${ES_HOME}

RUN yes | CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin \
    install -b ingest-geoip

i am getting this error
tep 4/4 : RUN yes | CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin     install -b ingest-geoip
 ---> Running in 6d91aae974f7

future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement
A tool for managing installed elasticsearch plugins

-> Installing ingest-geoip
-> Failed installing ingest-geoip
-> Rolling back ingest-geoip
-> Rolled back ingest-geoip
Non-option arguments:
command

Option             Description
------             -----------
-E <KeyValuePair>  Configure a setting
-h, --help         Show help
-s, --silent       Show minimal output
-v, --verbose      Show verbose output
ERROR: Unknown plugin ingest-geoip
The command '/bin/sh -c yes | CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin     install -b ingest-geoip' returned a non-zero code: 64

**Comment by spujadas** [comment]
Straight from https://discuss.elastic.co/t/how-to-install-enable-ingest-geoip-and-ingest-user-agent-in-elk-stack-7-1/186216

> It's part of the default distribution so you don't have to install it anymore.
