### ISSUE TITLE
Problem Running Elasticsearch nodes on a single host

### ISSUE THREAD

**Issue by anggara-ajip** [spujadas/elk-docker#330]
hello, I have problem when I want to add new nodes
here's script 

`sudo docker run -it --rm=true -v /srv/samba/kibana_config/elasticsearch-slave.yml:/etc/elasticsearch/elasticsearch.yml --link elk:elk --name elk2 sebp/elk`

I already create a share folder on /srv/samba/kibana_config , and it can be accessed in other windows pc, but why it still can't running ?

here is the log script

https://gist.github.com/anggara-ajip/86f39e920d9d21a8687361a811eec0f9

is there something missing ?

**Comment by spujadas** [comment]
> `[2020-07-10T07:31:24,139][WARN ][o.e.d.SeedHostsResolver  ] [elk2] failed to resolve host [elk]`
> `java.net.UnknownHostException: elk: Temporary failure in name resolution`

You want to check your configuration to make sure that you're pointing towards a properly resolvable host.

Closing as not an issue with the image. For support on how to configure Elasticsearch, please head over to forums such as http://discuss.elastic.co/.
