### ISSUE TITLE
latest tag does not correspond to oss tag although documentation suggests it

### ISSUE THREAD

**Issue by sandrinr** [spujadas/elk-docker#331]
Looking at the [documentation](https://github.com/spujadas/elk-docker/blame/b295d0b25c55ebb99a57a339d4ea45f39aa1e0fb/README.md#L17) it suggests that the `latest` and `oss-780` tags are the same.

When checking at Dockerhub, however, one can see, that the `latest` and `oss-780` tags do not seem to be the same.
![image](https://user-images.githubusercontent.com/4083653/87510760-733b6600-c674-11ea-8581-eb4a50102438.png)

Are these only irrelevant differences?

**Comment by spujadas** [comment]
Weird, but the differences should indeed be irrelevant as the images for `latest` and `oss-780` are built from the exact same `Dockerfile`. Don't know why the digests are different though.
