### ISSUE TITLE
Ubuntu 18.04     Couldn't start Elasticsearch

### ISSUE THREAD

**Issue by LnkSaber** [spujadas/elk-docker#332]
![image](https://user-images.githubusercontent.com/41216861/92734547-386f5900-f3ab-11ea-888c-58f01fc844e1.png)

**Comment by spujadas** [comment]
See https://elk-docker.readthedocs.io/#es-not-starting-not-enough-memory

**Comment by jaydeepjc** [comment]
Apologies for jumping someone else's Issue, However I am also having same issue

my elk container worked fine for a month and then suddenly stopped working

below are the details

`[root@server1 ]# ulimit -n
65535`

`[root@server1 ]# sysctl vm.max_map_count
vm.max_map_count = 262144`

`[root@server1 ]# cat /etc/sysconfig/docker 
OPTIONS="--default-ulimit nofile=1024:65536"`

`[2020-11-04T06:56:48,368][INFO ][o.e.e.NodeEnvironment    ] [elk] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/nvme0n1p1)]], net usable_space [73gb], net total_space [99.9gb], types [xfs]
[2020-11-04T06:56:48,368][INFO ][o.e.e.NodeEnvironment    ] [elk] heap size [1gb], compressed ordinary object pointers [true]
[2020-11-04T06:56:53,037][INFO ][o.e.n.Node               ] [elk] node name [elk], node ID [DpENUi2_TYW7lp2LJchfIg], cluster name [elasticsearch]
 * Starting periodic command scheduler cron                              [ OK ] 
 * Starting Elasticsearch Server                                         [fail] 
waiting for Elasticsearch to be up (1/30)
waiting for Elasticsearch to be up (2/30)
waiting for Elasticsearch to be up (3/30)
waiting for Elasticsearch to be up (4/30)
waiting for Elasticsearch to be up (5/30)
waiting for Elasticsearch to be up (6/30)
waiting for Elasticsearch to be up (7/30)
waiting for Elasticsearch to be up (8/30)
waiting for Elasticsearch to be up (9/30)
waiting for Elasticsearch to be up (10/30)
waiting for Elasticsearch to be up (11/30)
waiting for Elasticsearch to be up (12/30)
waiting for Elasticsearch to be up (13/30)
waiting for Elasticsearch to be up (14/30)
waiting for Elasticsearch to be up (15/30)
waiting for Elasticsearch to be up (16/30)
waiting for Elasticsearch to be up (17/30)
waiting for Elasticsearch to be up (18/30)
waiting for Elasticsearch to be up (19/30)
waiting for Elasticsearch to be up (20/30)
waiting for Elasticsearch to be up (21/30)
waiting for Elasticsearch to be up (22/30)
waiting for Elasticsearch to be up (23/30)
waiting for Elasticsearch to be up (24/30)
waiting for Elasticsearch to be up (25/30)
waiting for Elasticsearch to be up (26/30)
waiting for Elasticsearch to be up (27/30)
waiting for Elasticsearch to be up (28/30)
waiting for Elasticsearch to be up (29/30)
waiting for Elasticsearch to be up (30/30)
Couldn't start Elasticsearch. Exiting.
Elasticsearch log follows below.`

**Comment by spujadas** [comment]
@jaydeepjc unless the logs (where your message is clipped) show anything interesting, I'd still suggest that this is a memory issue (memory as in RAM available for the container).
If your container's been running for a while and/or if memory hasn't been specifically dedicated to the container, then the container could become short on memory causing Elasticsearch to fail on start-up.

**Comment by jaydeepjc** [comment]
What can be done, I tried resting container as well as host machine, it didn't helped.
Any suggestions?

**Comment by spujadas** [comment]
Assign more memory to your container, not much else that can be done I'm afraid.

**Comment by jaydeepjc** [comment]
Got it, Thanks :)
