### ISSUE TITLE
Functionality gone in latest build (7.9.3)

### ISSUE THREAD

**Issue by Supermillhouse** [spujadas/elk-docker#337]
Having problems with the "Latest" build (7.9.3), can't get most of the panels on the left to come up, notably index management.
I have tried 7.9.2 and it is working fine.

Both have been fresh docker builds (no existing volume data) but only 7.9.2 loads up properly.

**Comment by spujadas** [comment]
The `latest` build is the OSS variant of version 7.9.3, which has fewer features than the regular version: this is presumably why the panels are missing in Kibana.
If you want the default stack, pull the `793` tag (`latest` corresponds to `oss-793`).
