### ISSUE TITLE
The Kibana configuration does not work （version 7.10.0）

### ISSUE THREAD

**Issue by Felfan** [spujadas/elk-docker#340]
1.
**docker-compose.yml**

> version: "3"
> services:
>    elk:
>     image: sebp/elk
>     #restart: always
>     container_name: 'elk'
>     environment:
>       - "TZ=Asia/Shanghai"
>       - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
>       - "ELASTICSEARCH_START=1"
>       - "LOGSTASH_START=0"
>       - "KIBANA_START=1"
>       - "I18N_LOCALE=zh-CN"
>     ports:
>       - "5601:5601"
>       - "9200:9200"
>       - "5044:5044"
>     volumes:
>       #持久化日志数据
>       - ./elk-data:/var/lib/elasticsearch

environment:
  "TZ=Asia/Shanghai" and - "I18N_LOCALE=zh-CN"  does not work

When I visited the Kibana interface, the log was as follows:

> {"type":"response","**@timestamp":"2021-01-04T14:24:56Z**","tags":[],"pid":263,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"39.100.252.159:5601","connection":"keep-alive","content-length":"118","kbn-version":"7.10.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, likeGecko) Chrome/87.0.4280.66 Safari/537.36","content-type":"application/json","accept":"*/*","origin":"http://39.100.252.159:5601","referer":"http://39.100.252.159:5601/app/home","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9"},"remoteAddress":"111.194.51.134","userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36","referer":"http://39.100.252.159:5601/app/home"},"res":{"statusCode":200,"responseTime":22,"contentLength":9},"message":"POST /api/ui_metric/report 200 22ms - 9.0B"}
{"type":"response","@timestamp":"2021-01-04T14:25:53Z","tags":[],"pid":263,"method":"post","statusCode":200,"req":{"url":"/api/ui_metric/report","method":"post","headers":{"host":"39.100.252.159:5601","connection":"keep-alive","content-length":"119","kbn-version":"7.10.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, likeGecko) Chrome/87.0.4280.66 Safari/537.36","content-type":"application/json","accept":"*/*","origin":"http://39.100.252.159:5601","referer":"http://39.100.252.159:5601/app/home","accept-encoding":"gzip, deflate","accept-language":"zh-CN,zh;q=0.9"},"remoteAddress":"111.194.51.134","userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36","referer":"http://39.100.252.159:5601/app/home"},"res":{"statusCode":200,"responseTime":564,"contentLength":9},"message":"POST /api/ui_metric/report 200 564ms - 9.0B"}

then i  change the file: **/opt/kibana/config/kibana.yml**
2.
add the follow:
`i18n.locale: zh-CN`

I really hope you can help me
thank you very much!!!
@all

**Comment by spujadas** [comment]
Probably the same as https://github.com/elastic/kibana/issues/53814, i.e. not working with the OSS version of Kibana.

Please try with `sebp/elk:7.10.0` for version 7.10.0, instead of `sebp/elk` which is currently version 7.10.0 **OSS**.
