### ISSUE TITLE
add ES_HOME as home directory of user elasticsearch

### ISSUE THREAD

**Issue by ollofx** [spujadas/elk-docker#342]
https://github.com/spujadas/elk-docker/blob/1487bf0c079fbe7432242028ebddcd7fcf6a442a/Dockerfile#L65

as it is done for logstash user for instance

&& useradd -r -s /usr/sbin/nologin -d ${LOGSTASH_HOME} -c "Logstash service user" -u ${LOGSTASH_UID} -g logstash logstash

**Comment by spujadas** [comment]
Sure thing, https://github.com/spujadas/elk-docker/commit/a130e79f7f4612ffd624bb4aa0a2b4acdd6c50c2
