### ISSUE TITLE
tag 7.11.1 not available only latest could be used to fetch this version

### ISSUE THREAD

**Issue by ollofx** [spujadas/elk-docker#343]
Dear Community,
I'm used to fix my source docker image version, but the tags 7.11.1 could not be found
FROM sebp/elk:7.11.1
so I was forced to use:
FROM sebp/elk:latest
If there is a new version will the  tag 7.11.1 be created to allow FROM sebp/elk:7.11.1 ?
Is it possible to have latest and 7.11.1 point to the same image by now already ?
Thank you for your help

**Comment by spujadas** [comment]
Yes, this is normally done automatically by Docker Hub’s build system, but for some reason it doesn’t always pick up the tag changes.
Anyway I’ve triggered the builds manually, so the images with the missing tags should be available within the next few hours.
