### ISSUE TITLE
ensure tail -f  OUTPUT_LOGFILES is killed after sigterm received by start.sh

### ISSUE THREAD

**Issue by ollofx** [spujadas/elk-docker#345]
https://github.com/spujadas/elk-docker/blob/a130e79f7f4612ffd624bb4aa0a2b4acdd6c50c2/start.sh#L21

before exit after receiving sig_term ensure also the tail -f doesn't stay as zombie
  

`  # kill script PGID so all the child other the direct child are killed avoid zombie`
 ` trap - SIGTERM SIGINT`
 ` kill -TERM -- -$$ 2>/dev/null `
 ` exit 0`

**Comment by ollofx** [comment]
has to be adapted infinite loop

**Comment by ollofx** [comment]
# kill script PGID so all the child other the direct child are killed avoid zombie
  trap - SIGTERM SIGINT
  kill -TERM -- -$$ 2>/dev/null

**Comment by spujadas** [comment]
Thanks for reporting this and providing a fix — much appreciated!
