### ISSUE TITLE
elk_1  | ERROR: [1] bootstrap checks failed

### ISSUE THREAD

**Issue by JCTRoth** [spujadas/elk-docker#347]
Creating elk-docker_elk_1 ... done
Attaching to elk-docker_elk_1
elk_1  |  * Starting periodic command scheduler cron
elk_1  |    ...done.
elk_1  |  * Starting Elasticsearch Server
elk_1  |    ...done.
elk_1  | waiting for Elasticsearch to be up (1/30)
elk_1  | waiting for Elasticsearch to be up (2/30)
elk_1  | waiting for Elasticsearch to be up (3/30)
elk_1  | waiting for Elasticsearch to be up (4/30)
elk_1  | waiting for Elasticsearch to be up (5/30)
elk_1  | waiting for Elasticsearch to be up (6/30)
elk_1  | waiting for Elasticsearch to be up (7/30)
elk_1  | waiting for Elasticsearch to be up (8/30)
elk_1  | waiting for Elasticsearch to be up (9/30)
elk_1  | waiting for Elasticsearch to be up (10/30)
elk_1  | waiting for Elasticsearch to be up (11/30)
elk_1  | waiting for Elasticsearch to be up (12/30)
elk_1  | ERROR: [1] bootstrap checks failed
elk_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elk_1  | ERROR: Elasticsearch did not exit normally - check the logs at /var/log/elasticsearch/elasticsearch.log
elk_1  | waiting for Elasticsearch to be up (13/30)
elk_1  | waiting for Elasticsearch to be up (14/30)
elk_1  | waiting for Elasticsearch to be up (15/30)
elk_1  | waiting for Elasticsearch to be up (16/30)
elk_1  | waiting for Elasticsearch to be up (17/30)
elk_1  | waiting for Elasticsearch to be up (18/30)
elk_1  | waiting for Elasticsearch to be up (19/30)
elk_1  | waiting for Elasticsearch to be up (20/30)
elk_1  | waiting for Elasticsearch to be up (21/30)
elk_1  | waiting for Elasticsearch to be up (22/30)
elk_1  | waiting for Elasticsearch to be up (23/30)
elk_1  | waiting for Elasticsearch to be up (24/30)
elk_1  | waiting for Elasticsearch to be up (25/30)
elk_1  | waiting for Elasticsearch to be up (26/30)
elk_1  | waiting for Elasticsearch to be up (27/30)
elk_1  | waiting for Elasticsearch to be up (28/30)
elk_1  | waiting for Elasticsearch to be up (29/30)
elk_1  | waiting for Elasticsearch to be up (30/30)
elk_1  | Couldn't start Elasticsearch. Exiting.
elk_1  | Elasticsearch log follows below.
elk_1  | [2021-03-28T20:14:00,551][INFO ][o.e.n.Node               ] [elk] version[7.11.2], pid[197], build[default/tar/3e5a16cfec50876d20ea77b075070932c6464c7d/2021-03-06T05:54:38.141101Z], OS[Linux/5.4.0-70-generic/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/15.0.1/15.0.1+9]
elk_1  | [2021-03-28T20:14:00,555][INFO ][o.e.n.Node               ] [elk] JVM home [/opt/elasticsearch/jdk], using bundled JDK [true]
elk_1  | [2021-03-28T20:14:00,555][INFO ][o.e.n.Node               ] [elk] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.locale.providers=SPI,COMPAT, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-727738373591280356, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms3980m, -Xmx3980m, -XX:MaxDirectMemorySize=2086666240, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/opt/elasticsearch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
elk_1  | [2021-03-28T20:14:03,879][INFO ][o.e.p.PluginsService     ] [elk] loaded module [aggs-matrix-stats]
elk_1  | [2021-03-28T20:14:03,879][INFO ][o.e.p.PluginsService     ] [elk] loaded module [analysis-common]
elk_1  | [2021-03-28T20:14:03,880][INFO ][o.e.p.PluginsService     ] [elk] loaded module [constant-keyword]
elk_1  | [2021-03-28T20:14:03,880][INFO ][o.e.p.PluginsService     ] [elk] loaded module [flattened]
elk_1  | [2021-03-28T20:14:03,880][INFO ][o.e.p.PluginsService     ] [elk] loaded module [frozen-indices]
elk_1  | [2021-03-28T20:14:03,880][INFO ][o.e.p.PluginsService     ] [elk] loaded module [ingest-common]
elk_1  | [2021-03-28T20:14:03,881][INFO ][o.e.p.PluginsService     ] [elk] loaded module [ingest-geoip]
elk_1  | [2021-03-28T20:14:03,881][INFO ][o.e.p.PluginsService     ] [elk] loaded module [ingest-user-agent]
elk_1  | [2021-03-28T20:14:03,881][INFO ][o.e.p.PluginsService     ] [elk] loaded module [kibana]
elk_1  | [2021-03-28T20:14:03,881][INFO ][o.e.p.PluginsService     ] [elk] loaded module [lang-expression]
elk_1  | [2021-03-28T20:14:03,882][INFO ][o.e.p.PluginsService     ] [elk] loaded module [lang-mustache]
elk_1  | [2021-03-28T20:14:03,882][INFO ][o.e.p.PluginsService     ] [elk] loaded module [lang-painless]
elk_1  | [2021-03-28T20:14:03,882][INFO ][o.e.p.PluginsService     ] [elk] loaded module [mapper-extras]
elk_1  | [2021-03-28T20:14:03,882][INFO ][o.e.p.PluginsService     ] [elk] loaded module [mapper-version]
elk_1  | [2021-03-28T20:14:03,882][INFO ][o.e.p.PluginsService     ] [elk] loaded module [parent-join]
elk_1  | [2021-03-28T20:14:03,883][INFO ][o.e.p.PluginsService     ] [elk] loaded module [percolator]
elk_1  | [2021-03-28T20:14:03,883][INFO ][o.e.p.PluginsService     ] [elk] loaded module [rank-eval]
elk_1  | [2021-03-28T20:14:03,883][INFO ][o.e.p.PluginsService     ] [elk] loaded module [reindex]
elk_1  | [2021-03-28T20:14:03,884][INFO ][o.e.p.PluginsService     ] [elk] loaded module [repositories-metering-api]
elk_1  | [2021-03-28T20:14:03,884][INFO ][o.e.p.PluginsService     ] [elk] loaded module [repository-url]
elk_1  | [2021-03-28T20:14:03,884][INFO ][o.e.p.PluginsService     ] [elk] loaded module [search-business-rules]
elk_1  | [2021-03-28T20:14:03,884][INFO ][o.e.p.PluginsService     ] [elk] loaded module [searchable-snapshots]
elk_1  | [2021-03-28T20:14:03,885][INFO ][o.e.p.PluginsService     ] [elk] loaded module [spatial]
elk_1  | [2021-03-28T20:14:03,885][INFO ][o.e.p.PluginsService     ] [elk] loaded module [transform]
elk_1  | [2021-03-28T20:14:03,885][INFO ][o.e.p.PluginsService     ] [elk] loaded module [transport-netty4]
elk_1  | [2021-03-28T20:14:03,885][INFO ][o.e.p.PluginsService     ] [elk] loaded module [unsigned-long]
elk_1  | [2021-03-28T20:14:03,886][INFO ][o.e.p.PluginsService     ] [elk] loaded module [vectors]
elk_1  | [2021-03-28T20:14:03,886][INFO ][o.e.p.PluginsService     ] [elk] loaded module [wildcard]
elk_1  | [2021-03-28T20:14:03,886][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-aggregate-metric]
elk_1  | [2021-03-28T20:14:03,887][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-analytics]
elk_1  | [2021-03-28T20:14:03,887][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-async]
elk_1  | [2021-03-28T20:14:03,887][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-async-search]
elk_1  | [2021-03-28T20:14:03,887][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-autoscaling]
elk_1  | [2021-03-28T20:14:03,888][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-ccr]
elk_1  | [2021-03-28T20:14:03,888][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-core]
elk_1  | [2021-03-28T20:14:03,888][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-data-streams]
elk_1  | [2021-03-28T20:14:03,888][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-deprecation]
elk_1  | [2021-03-28T20:14:03,889][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-enrich]
elk_1  | [2021-03-28T20:14:03,889][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-eql]
elk_1  | [2021-03-28T20:14:03,889][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-fleet]
elk_1  | [2021-03-28T20:14:03,889][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-graph]
elk_1  | [2021-03-28T20:14:03,890][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-identity-provider]
elk_1  | [2021-03-28T20:14:03,890][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-ilm]
elk_1  | [2021-03-28T20:14:03,890][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-ingest]
elk_1  | [2021-03-28T20:14:03,890][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-logstash]
elk_1  | [2021-03-28T20:14:03,890][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-ml]
elk_1  | [2021-03-28T20:14:03,891][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-monitoring]
elk_1  | [2021-03-28T20:14:03,891][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-ql]
elk_1  | [2021-03-28T20:14:03,891][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-rollup]
elk_1  | [2021-03-28T20:14:03,891][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-runtime-fields]
elk_1  | [2021-03-28T20:14:03,892][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-security]
elk_1  | [2021-03-28T20:14:03,892][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-sql]
elk_1  | [2021-03-28T20:14:03,892][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-stack]
elk_1  | [2021-03-28T20:14:03,892][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-voting-only-node]
elk_1  | [2021-03-28T20:14:03,892][INFO ][o.e.p.PluginsService     ] [elk] loaded module [x-pack-watcher]
elk_1  | [2021-03-28T20:14:03,893][INFO ][o.e.p.PluginsService     ] [elk] no plugins loaded
elk_1  | [2021-03-28T20:14:03,974][INFO ][o.e.e.NodeEnvironment    ] [elk] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/sda2)]], net usable_space [175.7gb], net total_space [194.9gb], types [ext4]
elk_1  | [2021-03-28T20:14:03,976][INFO ][o.e.e.NodeEnvironment    ] [elk] heap size [3.8gb], compressed ordinary object pointers [true]
elk_1  | [2021-03-28T20:14:04,031][INFO ][o.e.n.Node               ] [elk] node name [elk], node ID [Aqhl1NxeTe-3NWtJ8eiRew], cluster name [elasticsearch], roles [transform, master, remote_cluster_client, data, ml, data_content, data_hot, data_warm, data_cold, ingest]
elk_1  | [2021-03-28T20:14:09,458][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [elk] [controller/233] [Main.cc@117] controller (64 bit): Version 7.11.2 (Build c940034b34c11c) Copyright (c) 2021 Elasticsearch BV
elk_1  | [2021-03-28T20:14:11,357][INFO ][o.e.t.NettyAllocator     ] [elk] creating NettyAllocator with the following configs: [name=elasticsearch_configured, chunk_size=1mb, suggested_max_allocation_size=1mb, factors={es.unsafe.use_netty_default_chunk_and_page_size=false, g1gc_enabled=true, g1gc_region_size=4mb}]
elk_1  | [2021-03-28T20:14:11,462][INFO ][o.e.d.DiscoveryModule    ] [elk] using discovery type [zen] and seed hosts providers [settings]
elk_1  | [2021-03-28T20:14:12,138][INFO ][o.e.g.DanglingIndicesState] [elk] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
elk_1  | [2021-03-28T20:14:12,977][INFO ][o.e.n.Node               ] [elk] initialized
elk_1  | [2021-03-28T20:14:12,978][INFO ][o.e.n.Node               ] [elk] starting ...
elk_1  | [2021-03-28T20:14:13,002][INFO ][o.e.x.s.c.PersistentCache] [elk] persistent cache index loaded
elk_1  | [2021-03-28T20:14:13,189][INFO ][o.e.t.TransportService   ] [elk] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
elk_1  | [2021-03-28T20:14:13,433][INFO ][o.e.b.BootstrapChecks    ] [elk] bound or publishing to a non-loopback address, enforcing bootstrap checks
elk_1  | [2021-03-28T20:14:13,436][ERROR][o.e.b.Bootstrap          ] [elk] node validation exception
elk_1  | [1] bootstrap checks failed
elk_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elk_1  | [2021-03-28T20:14:13,443][INFO ][o.e.n.Node               ] [elk] stopping ...
elk_1  | [2021-03-28T20:14:13,468][INFO ][o.e.n.Node               ] [elk] stopped
elk_1  | [2021-03-28T20:14:13,468][INFO ][o.e.n.Node               ] [elk] closing ...
elk_1  | [2021-03-28T20:14:13,484][INFO ][o.e.n.Node               ] [elk] closed
elk_1  | [2021-03-28T20:14:13,486][INFO ][o.e.x.m.p.NativeController] [elk] Native controller process has stopped - no new native processes can be started
elk-docker_elk_1 exited with code 1

**Comment by JCTRoth** [comment]
I think you need to add  `sysctl -w vm.max_map_count=262144`

**Comment by spujadas** [comment]
Indeed, see https://elk-docker.readthedocs.io/#prerequisites
