### ISSUE TITLE
how to enable security features or modify the configs of elk

### ISSUE THREAD

**Issue by xdandyx** [spujadas/elk-docker#351]
The description of this image is a little too simple. It would be better to explain how the configuration files inside the container are loaded and worked.
Now, I want to turn on the user login function to avoid illegal access to some services. What should I do?

**Comment by spujadas** [comment]
The image packages the ELK stack, so aside from the features that are Docker-specific and therefore documented, the standard ELK features — including configuration and security features — work as described in the official documentation at https://www.elastic.co/guide/index.html
For further guidance on how to set up the ELK stack, please head over to https://discuss.elastic.co/
Closing as the question is not specific to this image.
