### ISSUE TITLE
ES_HEAP_SIZE doesn't work anymore

### ISSUE THREAD

**Issue by bmario** [spujadas/elk-docker#359]
It seems, the `Xms` and `Xmx` options were removed upstream from the `jvm.options` file for elasticsearch.
The script should create a file with them under `/opt/elasticsearch/config/jvm.options.d/*.options` or use `ES_JAVA_OPTS` instead, apparently.

https://www.elastic.co/guide/en/elasticsearch/reference/7.15/advanced-configuration.html#set-jvm-heap-size

**Comment by spujadas** [comment]
Thanks for reporting this, I think I’m going to go with the `ES_JAVA_OPTS` option as the script already supports this env var.
Will look into this in a couple of days.

**Comment by spujadas** [comment]
Ended up going the `jvm.options.d/*.options` way for `ES_JAVA_OPTS`, and also applied the same technique to `ES_HEAP_DISABLE`.
Updated in the `7.15.2`-tagged image.
Thanks again for raising this issue.
