### ISSUE TITLE
RabbitMQ Support

### ISSUE THREAD

**Issue by gcstang** [spujadas/elk-docker#36]
Will you be adding RabbitMQ support for the image?

**Comment by spujadas** [comment]
Nope: by design I'm keeping the base image as lean as possible (i.e. with Elastic technology only), so that anyone can extend it with whatever plugin they need (e.g. Logstash's _rabbitmq_ output plugin).
See http://elk-docker.readthedocs.io/#installing-logstash-plugins for details if needed.
