### ISSUE TITLE
Question: user authentication for https

### ISSUE THREAD

**Issue by duongpc** [spujadas/elk-docker#369]
If I use default official elasticsearch image and enable https, it will be asking for authentication using user `elastic` with default password `changeme`. 

![image](https://user-images.githubusercontent.com/24272450/169670933-d16657fc-4e1e-42ce-a667-16a7f8403586.png)

For this image after enabling https I tried the same username/password and it didn't work. Is there any steps to setup the superuser account or it is not possible with this image? 

Thanks

**Comment by spujadas** [comment]
Security is disabled by default to make the image usable and user-friendly out-of-the-box.
Enabling security is most definitely possible, but setting it up is a bit fiddly, involving custom config files, at least one restart of the container, and `bash`ing into the container to complete the set-up.
See https://www.elastic.co/guide/en/elasticsearch/reference/8.2/configuring-stack-security.html for details.
