### ISSUE TITLE
Update ELK to latest version (currently 8.3.3)

### ISSUE THREAD

**Issue by phm46** [spujadas/elk-docker#372]
Hey, thanks for your image! It’s great to have it and I’m playing with ELK a lot. However, in your latest version (8.1.0) are some bugs, that renders some functionality useless. Is it possible to update your ELK image to more recent version?
Thanks in advance!

**Comment by BlueIce** [comment]
An update for the ELK release train 7.x would be awesome, too. There are some security issues which got fixed in 7.17.5: https://discuss.elastic.co/t/elastic-8-3-1-8-3-0-and-7-17-5-security-update/308613.

**Comment by spujadas** [comment]
Thanks for raising this, will take care of it next week, for both versions 7 and 8.

**Comment by spujadas** [comment]
The updated images have been published – enjoy!

**Comment by BlueIce** [comment]
Thanks for the new versions. And thank you for maintaining these images over such a long period.
