### ISSUE TITLE
Update ELK to 8.9.0

### ISSUE THREAD

**Issue by mig5** [spujadas/elk-docker#379]
Hi @spujadas !

When you get some time, would you please be able to update your ELK stack to the latest (at time of writing: 8.9.0)

Thanks very much for supporting this project! :)

**Comment by spujadas** [comment]
Hi, thanks for the kind words – build of 8.9.0 is in progress (https://github.com/spujadas/elk-docker/commit/3f183bb3a67b10f60a83b446b7a74f37e014f0e2) and updating to the latest 8.9.1 as I’m typing this.
