### ISSUE TITLE
Kibana 8.11.1 Security Update (ESA-2023-25)

### ISSUE THREAD

**Issue by markof88** [spujadas/elk-docker#381]
Hello,
thanks for providing this image, works really good! There is new Kibana CVE: [Kibana 8.11.1 Security Update (ESA-2023-25)](https://discuss.elastic.co/t/kibana-8-11-1-security-update-esa-2023-25/347149).

Could you please deploy new image with Kibana 8.11.1 in order to fix this CVE? 

Thank you

**Comment by spujadas** [comment]
Thanks for raising this issue, build is in progress following https://github.com/spujadas/elk-docker/commit/893c81e4c54a81d563b5461f69bda00fee558552
