### ISSUE TITLE
For Running on MAC M2 need need bootstrap.system_call_filter: false in elasticsearch.yml

### ISSUE THREAD

**Issue by novaview** [spujadas/elk-docker#385]
Thank you for maintaining this image.

On my M2 Mac, I see the same issue as reported in the following StackOverflow issue - https://stackoverflow.com/questions/50314586/elasticsearch-fails-to-start-config-seccomp-and-config-seccomp-filter-are-neede

The solution is to set bootstrap.system_call_filter: false in elasticsearch.yml

Any suggestions on easiest steps for doing this when using the elk-docker image?

Thanks

**Comment by novaview** [comment]
Solved by starting the container after it had initially exited, and then go into the container shell via DockerDesktop and add bootstrap.system_call_filter: false in elasticsearch.yml found in /etc/elasticsearch .

**Comment by spujadas** [comment]
Thanks, will add this to the documentation!
