### ISSUE TITLE
Upgrade to 8.15.1

### ISSUE THREAD

**Issue by mig5** [spujadas/elk-docker#387]
Hi @spujadas !

Would it be possible to upgrade to 8.15.1, so as to address this critical vulnerability in Kibana? 

https://discuss.elastic.co/t/kibana-8-15-1-security-update-esa-2024-27-esa-2024-28/366119

Thanks!

**Comment by spujadas** [comment]
Hi, sure thing!
Build is available following https://github.com/spujadas/elk-docker/commit/c30d256c597c93ef2eb3fea14b7f09ff987b3e38
