### ISSUE TITLE
Auto Reload considered dangerous?

### ISSUE THREAD

**Issue by kenwdelong** [spujadas/elk-docker#41]
I just wanted to make you aware of another issue that I had with the 2.3.x series.  There might be a resource leak in logstash.  The issue is tracking here:  https://github.com/elastic/logstash/issues/5235.

Once I removed auto-reload from my logstash config, my instance is fine.  It's still running with load average 0.1 after 2 days.

**Comment by spujadas** [comment]
Ouch! Thanks for the heads up, will most certainly consider removing it as a default option (users can always enable it voluntarily using the env vars) and/or flagging it in the documentation.

**Comment by spujadas** [comment]
Thanks again – will keep track of the Elasticsearch issue.
