### ISSUE TITLE
Certificate issue with filebeat agent running inside nginx-filebeat container

### ISSUE THREAD

**Issue by zzkhan** [spujadas/elk-docker#47]
Hi,

Im getting the following error when I run the nginx-filebeat docker container:

`2016/06/10 12:36:46.192860 transport.go:125: ERR SSL client failed to connect with: x509: cannot validate certificate for 192.168.99.100 because it doesn't contain any IP SANs`

Is there something wrong with the cert file (elk-docker/nginx-filebeat/logstash-beats.crt) ?

Any help would be much appreciated.

Thanks,

zzkhan

**Comment by spujadas** [comment]
Hi,
The certificate is fine, you should check out http://elk-docker.readthedocs.io/#certificates for further explanations as to its limitations and for guidance on what to do from there.
