### ISSUE TITLE
Issue when installing Kibana plugin Sense

### ISSUE THREAD

**Issue by mashuble** [spujadas/elk-docker#48]
Hi,

When I try to install the Kibana plugin Sense with this Dockerfile

    FROM sebp/elk

    WORKDIR ${KIBANA_HOME}
    RUN gosu kibana bin/kibana plugin -i elastic/sense

I have theses errors:

    Step 3 : RUN gosu kibana bin/kibana plugin -i elastic/sense
     ---> Running in 662d1a08d470
    Installing sense
    Attempting to transfer from https://download.elastic.co/elastic/sense/sense-latest.tar.gz
    Error: Client request error: getaddrinfo ENOTFOUND download.elastic.co download.elastic.co:443
    Plugin installation was unsuccessful due to error "Client request error: getaddrinfo ENOTFOUND         download.elastic.co download.elastic.co:443"
    ERROR: Service 'elastic' failed to build: The command '/bin/sh -c gosu kibana bin/kibana plugin -i elastic/sense' returned a non-zero code: 70
    Cedric-Vidal:elasticsearch mtournaud$ docker volume create elk-data
    docker: "volume create" requires 0 arguments.

Anybody have a solution ?

**Comment by spujadas** [comment]
Hi,

First thought that springs to find is that you're behind a proxy, in which case you might want to have a look at this discussion: https://github.com/elastic/kibana/issues/5902

FWIW your Dockerfile is working fine on my side.

**Comment by mashuble** [comment]
Find the solution

    docker-machine restart default
    eval $(docker-machine env default)

Thanks for advices
