### ISSUE TITLE
help

### ISSUE THREAD

**Issue by tshanchuan** [spujadas/elk-docker#50]
``sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -p 5000:5000 -it --name elk sebp/elk
is error

WARN[18707] exit status 1                                
WARN[18708] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20/shm: invalid argument
failed to umount /var/lib/docker/containers/aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20/mqueue: invalid argument 
ERRO[18708] Error unmounting device aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20: UnmountDevice: device not-mounted id aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20 
ERRO[18708] Handler for POST /v1.21/containers/aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20/start returned error: Cannot start container aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20: [8] System error: mkdir /var/lib/docker/devicemapper/mnt/aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20/rootfs/sys/fs/cgroup: no such file or directory 
ERRO[18708] HTTP Error                                    err=Cannot start container aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20: [8] System error: mkdir /var/lib/docker/devicemapper/mnt/aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20/rootfs/sys/fs/cgroup: no such file or directory statusCode=500
Error response from daemon: Cannot start container aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20: [8] System error: mkdir /var/lib/docker/devicemapper/mnt/aa944b3c49ff034014d8c002d5528526c62de8204ce8b86402319146e45f2f20/rootfs/sys/fs/cgroup: no such file or directory

**Comment by spujadas** [comment]
That's a Docker error/issue, it's most likely unrelated to whatever container you're trying to start, so will close this issue (feel free to reopen if further troubleshooting suggests that it is actually related to this specific image).
Have a look at https://github.com/docker/docker/issues/16902 for a similar situation, and I would recommend asking for help on the Docker forum (https://forums.docker.com/).
