### ISSUE TITLE
Compatible with Java 8?

### ISSUE THREAD

**Issue by HowardHoffman** [spujadas/elk-docker#52]
I downloaded and installed ELK-Docker according to the instructions at http://elk-docker.readthedocs.io/#installation.  Went fine; things running via Docker on Windows (!).

I am trying to connect ElasticSearch to Microsoft SQL Server so as to evaluate Kibana as a possible alternative to Dashboard engines such as Tableau.  

The JDBC Importer (https://github.com/jprante/elasticsearch-jdbc) was designed to connect ElasticSearch to SQL Server.  However the JDBC Importer requires Java 8.

Is it the case that ELK-Docker does not support Java 8?  I'm more of a Microsoft stack guy so it's quite possible I messed something up; but please confirm the version of Java needed for ELK-Docker.

I'm getting this error message when running the JDBC Importer :

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/xbib/tools/Runner : Unsupported major.minor version 52.0.

The JDBC Importer Issues link on Github says that error is due to Java 8 not being present.

**Comment by spujadas** [comment]
The sebp/elk image is packaged with Java 7, and as far as I understand Elasticsearch works with both Java 7 and Java 8 (https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html#jvm-version).

I'm not a Java guy myself, but I think you should be able to make things work by either:

- Forking this repo to create your own image, replacing the version of Java in the `Dockerfile` (https://github.com/spujadas/elk-docker/blob/master/Dockerfile#L49): this is the easiest way to go about it, but if you want to stay up to date you'll have to re-fork the repo and update the `Dockerfile` each time it changes.

- Extending the image to install a Java 8 package and alter Elasticsearch's init file to make the `JAVA_HOME` environment variable point to Java 8's home.

I haven't thought this through yet, but I'll see if I can do anything to make things easier moving forward (either by facilitating the ability to specify the `JAVA_HOME` for Elasticsearch, or by preinstalling Java 8 in the image, or by maintaining both a Java-7- and Java-8-enabled image).

In the meantime, if you could confirm that either of the methods suggested above do make the JDBC Importer work, that would be great.

 extending the image
