### ISSUE TITLE
Kibana stucks loading after version es231_l231_k450

### ISSUE THREAD

**Issue by marcote** [spujadas/elk-docker#55]
Hi there,

First, thanks for all the effort in the project.
I'm trying to use a version after es231_l231_k450 because I would like to use gosu to install some logstash plugins.
The problem is with any version before es231_l231_k450, es233_l232_k451 for example, Kibana stucks in the "Kibana is loading. Give me a moment here" loading page.

I can repro this also using latest also. es231_l231_k450  works fine. Kibana loads very quick.

Any ideas?
Thanks!

**Comment by spujadas** [comment]
Hi,

Glad to hear you're enjoying this image.

What you're observing is very strange indeed (first time I'm hearing about this). Kibana can take a little time to start, but eventually you should see something.

My first thought is that it might be a proxy issue: could you have a look at your browser's console and check if errors are showing up?
Could you also look at the container's logs to confirm that all the services started properly?
Another possibility is that it's an issue with your browser and that something introduced in Kibana 4.5.1 (or the underlying version AngularJS) is causing problems: see https://www.elastic.co/support/matrix#show_browsers for the list of supported browsers.

**Comment by marcote** [comment]
it's a cache issue!!! 
https://github.com/elastic/kibana/issues/7438 
Loading Kibana in incognito mode works fine!!

I'm closing this. thanks.

**Comment by spujadas** [comment]
Cool! Thanks for the update.
