### ISSUE TITLE
Weird behavior on ELK stack.

### ISSUE THREAD

**Issue by jguzmanCA** [spujadas/elk-docker#64]
I got a question about Logstash particularly. We are working on the manipulation of data, but when we start to test and make changes on the config files, we realize that the agent of logstash only parse log files with recient date (tested with touch command over the log file and making a copy of the same file). Is this an expected behavior? And on that scenario, Is it possible to reconfigure the agent or change the parameters during the reading process for the consideration of older files?

**Comment by spujadas** [comment]
I'm afraid I don't know. As your question seems to pertain to Logstash and doesn't seem to be specific to this Docker image, I'd recommend asking it on [Elastic's Logstash forum](https://discuss.elastic.co/c/logstash), where I'm pretty sure you'll get an answer.

**Comment by jguzmanCA** [comment]
Thanks for your fast response. Digging up a little bit more, i find out that the agent of logstash reads only new files or just the files created within 24 hours. If the files passed to logstash are older than that they'll be omitted a therefore no processed. Thanks anyway mate, this docker image save me a lot of time.

**Comment by spujadas** [comment]
Cheers, and thanks for the update!
