### ISSUE TITLE
doubt in ELK configuration

### ISSUE THREAD

**Issue by fmotnaldo** [spujadas/elk-docker#66]
Hi,

I am new in ELK and I isntalled follwoing this guide:

https://timothy-quinn.com/running-the-elk-stack-on-centos-7-and-using-beats/

When I start the agent in the client I get the following error.

[root@ardc01zabbix certs]#  service filebeat start
Starting filebeat: 2016/08/30 19:31:15.970602 transport.go:125: ERR SSL client failed to connect with: EOF
                                                           [  OK  ]
[root@ardc01zabbix certs]# telnet 10.32.8.20 5044
Trying 10.32.8.20...
Connected to 10.32.8.20.
Escape character is '^]'.

^CConnection closed by foreign host.
[root@ardc01zabbix certs]#

I cheked that the port 5044 can get throught to the master elk server. I need help in order to resolve this I tried everuthing.

Regards

**Comment by spujadas** [comment]
Hi,
Might be a configuration issue with the certificate in Filebeat.
You might want to have a look at:
- The documentation for the image on how to configure Filebeat: http://elk-docker.readthedocs.io/#forwarding-logs-filebeat
- The suggestions in #24.

**Comment by spujadas** [comment]
Housekeeping: closing this issue, please feel free to reopen if needed.
