### ISSUE TITLE
Kibana behind a reverse proxy doesn't work

### ISSUE THREAD

**Issue by pcornelissen** [spujadas/elk-docker#68]
Hi!

I'm running your container, which works great, but I want to access kibana through my Zuul (created by Netflix) proxy and map it for example to /status/logs zuul sends the corresponding http header, but it looks like kibana ignores them for the URL creation.

I think you can configure kibana to use another base path, but your image doesn't seem to allow that for now.

**Comment by pcornelissen** [comment]
Oh ok, forget it https://github.com/elastic/kibana/issues/1555 looks like kibana is build using the "You should have no gods beside me" pattern :-(

**Comment by spujadas** [comment]
Thanks for the update!

Looking at https://github.com/elastic/kibana/issues/5171, I'm not sure that https://github.com/elastic/kibana/issues/1555 is still applicable. 

If you want to give it a shot, I would have suggested to:

- Get the default [kibana.yml](https://github.com/elastic/kibana/blob/master/config/kibana.yml) file.
- Change the `server.basePath` to match your reverse proxy's config.
- Extend the sebp/elk image to add the updated Kibana config file.

**Comment by YouveGotMeowxy** [comment]
Hey all

I'm having no luck getting this working after 3 hours, and am getting frustrated, lol.

My Nginx proxy file looks like this (note that I'm using the LetsEncrypt container for my Nginx, so many of the other proxy settings are also in the [default proxy.conf file](https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/proxy.conf)):

```
location /kibana {
    return 301 $scheme://$http_host/kibana/;
}
location /kibana/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_kibana kibana;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://$upstream_kibana:5601;
}
```

and in my kibana.yml I have this:

```
server.basePath: "/kibana"
server.rewriteBasePath: true
```

But I still get a 502 Bad gateway error?

Please help!

**Comment by YouveGotMeowxy** [comment]
I have to say, the support here is **_amazing_**! :O

**Comment by YouveGotMeowxy** [comment]
Bueller?

**Comment by spujadas** [comment]
@YouveGotMeowxy I think it's unlikely that you'll find help here as this issue tracker is for issues with the Docker image.
For help on setting up a reverse proxy in front of Kibana (containerised or otherwise), you should head over to a support forum for Kibana such as https://discuss.elastic.co/c/kibana/7 (e.g. https://discuss.elastic.co/t/nginx-reverse-proxy-for-kibana/179024 may be a good place to start investigating).
