### ISSUE TITLE
It is sttopping to work 

### ISSUE THREAD

**Issue by weslleycamilo** [spujadas/elk-docker#71]
Hello,

I have been testing it and lately I realized that it works for some hours and it stopped to get new logs.

I cant see the logs on the Kibana website!!

There is no problems with disk space.
There are other docker containers running fine.

If i go to other servers and restart the filebeat i get the error below, but i didnt have it before due to the certificate

 * Restarting Sends log files to Logstash or directly to Elasticsearch. filebeat                                   2016/10/03 13:18:41.067302 transport.go:125: ERR SSL client failed to connect with: dial tcp 52.54.63.30:5044: getsockopt: connection refused.

To resolve this problem i have to restart my docker server and the nginx before restart the filebeat (i dont know why) and everything come to work again.

Do you have any clue?

Thanks you very much in advance.

**Comment by spujadas** [comment]
First impression is that Logstash is running out of memory and therefore stopping (and therefore port 5044 is rejecting connections from Filebeat).
Could you have a look at #57 for steps on how to check this?

**Comment by weslleycamilo** [comment]
Hello .. 

Thank you for your time.. 


I have increased its memory and I am not having this issue anymore.

Best Regards.

**Comment by spujadas** [comment]
Cool! Thanks for your feedback.
