### ISSUE TITLE
Unable to view logs on Kibana using JDBC Logstash plugin

### ISSUE THREAD

**Issue by TESAARON** [spujadas/elk-docker#72]
Hello,

I have successfully connected Logstash to my back-end Vertica database using the JDBC plugin for Logstash. Anytime a new entry is made in the table I am pointing at in Vertica I can view the Logstash update in var/log/logstash/logstash.stdout. However I cannot view the same log change on Kibana. Do I need to update the output configuration? My current output configuration looks like:

output {

    if [type] == "A" {
        elasticsearch {
           hosts => ["localhost"]
           sniffing => true
           manage_template => false
           index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
           document_type => "%{[@metadata][type]}"
        }  
    }
  stdout { codec => rubydebug }
}

Many thanks,
Aaron

**Comment by spujadas** [comment]
Hi,

First of all, always great to hear that about a non-vanilla working set-up!

As far as configuring Logstash is concerned, I'm afraid I don't know, but as what you're trying to do doesn't seem to be tied to this ELK image in particular, I would strongly recommend that you ask the same question to the Logstash crowd over at https://discuss.elastic.co/c/logstash, where you'll have a good chance of getting a quick and knowledgeable answer.

Do feel free to add a comment if you get an answer, in case someone else runs into the same kind of situation.

Leaving this open for now.

**Comment by TESAARON** [comment]
Thanks for the quick response.

Yes we decided that we needed to store logs on our own analytic database to have the option of building custom visualisations and certain aggregations of log data.

I will do as you suggested and return with an update!

Thanks,
Aaron

**Comment by TESAARON** [comment]
Hello,

Managed to get this working. Updated the output to:

output {
if [type] == "A" {
elasticsearch { }
}
}
stdout { codec => rubydebug }
}

And used default elastic configurations. 

Many thanks!

**Comment by spujadas** [comment]
Wow, simple as that then!
Thanks for the update, much appreciated. 
Cheers!
