### ISSUE TITLE
Error Message I/O Timeout

### ISSUE THREAD

**Issue by deepesh-telsiz** [spujadas/elk-docker#75]
Hi, I am seeing this error where filebeats is not working

This is filebeat-5.0.0-beta1-linux-x86_64

172.16.71.245:51652->54.214.224.161:5044: i/o timeout
2016/10/20 07:02:34.319113 logp.go:230: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.write_bytes=132 libbeat.logstash.publish.read_errors=1
2016/10/20 07:02:49.510743 single.go:140: ERR Connecting error publishing events (retrying): read tcp 172.16.71.245:51658->54.214.224.161:5044: i/o timeout
2016/10/20 07:03:04.319032 logp.go:230: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_errors=1
2016/10/20 07:03:34.319059 logp.go:230: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.write_bytes=132
2016/10/20 07:03:35.553716 single.go:140: ERR Connecting error publishing events (retrying): read tcp 172.16.71.245:51750->54.214.224.161:5044: i/o timeout
2016/10/20 07:04:04.319051 logp.go:230: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.read_errors=1
2016/10/20 07:04:34.319113 logp.go:230: INFO Non-zero metrics in the last 30s: libbeat.logstash.publish.write_bytes=132
2016/10/20 07:04:37.602399 single.go:140: ERR Connecting error publishing events (retrying): read tcp 172.16.71.245:51974->54.214.224.161:5044: i/o timeout

I have reachability to the server where logstash is running from the client

 help would be appreciated

Filebeat.yml

filebeat.prospectors:
- input_type: log
  
  paths:
  - /var/log/vdebug
  - /var/log/auth.log
  - /var/log/kern.log
  - /var/log/vsyslog
  
  document_type: syslog

output.logstash:
  # The Logstash hosts
  hosts: ["x.x.x.x:5044"]
  bulk_max_size: 1024
  ssl:

```
verification_mode: none
```

**Comment by spujadas** [comment]
Hi, 

Could you confirm that:

- Logstash is running properly in your container (starting up properly, process running).
- You can not only reach the server from the client but also connect to port 5044 from the client (`nc -vz your.logstash.server 5044`).

If the above checks out, then could you try to use a non-beta version of Filebeat? It's possible (going out on a limb here) that all the version 5s of the ELK stack and Beats are expected to work together and that there may be incompatibilities with earlier versions of the various products (e.g. between Filebeat 5.x and Logstash 2.x).

**Comment by deepesh-telsiz** [comment]
Hi,

Logstash is running , I have checked the process.
I have multiple client machines (I am monitoring logs on these) that are running filebeat, it is  the same version as I mentioned earlier, but some of these are getting these errors and even on these machines Filebeat was working properly earlier. 

I can try a non beta version of filebeat,but still wanted to know as to why this was happening.

**Comment by spujadas** [comment]
Hmmm, might also be worth checking in over at the [Beats and/or Logstash forums](https://discuss.elastic.co/), as your issue might be generic and not specific to this ELK image.

**Comment by spujadas** [comment]
Housekeeping: closing this issue, feel free to reopen if needed (+ everything should be working with the full version 5 stack).
