### ISSUE TITLE
elk:es500_l500_k500 - Logstash not running

### ISSUE THREAD

**Issue by VMRuiz** [spujadas/elk-docker#78]
Service logstash fails while booting up.
Logs shows the following error:

```
ERROR: Unknown command 'agent'

See: 'bin/logstash --help'
```

It started to work again after I removed the `agent` param from the logstash-init file.

**Comment by spujadas** [comment]
Thanks for reporting this, I'll take care of this ASSP later today.

**Comment by spujadas** [comment]
Thanks again, fixed as per your suggestion, and it's now working (embarrassing that I didn't catch it earlier 😕).
Will do some more checks/tests later to make sure that there aren't other issues in the init file.

**Comment by VMRuiz** [comment]
Thanks to you, your docker images saved me a lot of time! I really appreciate your work.

**Comment by spujadas** [comment]
Many thanks for the kind words!
