### ISSUE TITLE
ELK 5.0.0 update: elasticsearch not starting up

### ISSUE THREAD

**Issue by luispabon** [spujadas/elk-docker#79]
See:

http://pastebin.com/KgimwDZA

**Comment by spujadas** [comment]
Yep, known issue in version 5, see http://elk-docker.readthedocs.io/#troubleshooting (paragraph that begins with "As from version 5, if Elasticsearch is no longer starting…").

Also please pull the image again in a few minutes (currently building), as in the one I initially published yesterday Logstash isn't starting (now fixed).

**Comment by luispabon** [comment]
Roger that, will test once it's ready, I can see it's still building

**Comment by spujadas** [comment]
Housekeeping: closing this issue, feel free to reopen if needed.
