### ISSUE TITLE
Logstash tail log location doesn't match what's there

### ISSUE THREAD

**Issue by willclarktech** [spujadas/elk-docker#83]
Since switching to the Version 5 image, running `docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk` I get logs for elasticsearch and kibana, but not for logstash:
```
tail: cannot open '/var/log/logstash/logstash.log' for reading: No such file or directory
```

```
$ ls /var/log/logstash/
logstash-plain.log  logstash.err  logstash.stdout
```

**Comment by spujadas** [comment]
Yep, I need to update `start.sh` to `tail` the contents `logstash-plain.log`, will sort this out as soon as I can (later today probably).

**Comment by spujadas** [comment]
Good to go!
