### ISSUE TITLE
Kibana to elasticsearch connection retry should be configurable

### ISSUE THREAD

**Issue by bryanstaley** [spujadas/elk-docker#86]
We have an instance of elk-docker where our ES instance takes some time (> 30 secs) to initialize.  If ES isn't up by 30 secs, the container exits.

https://github.com/spujadas/elk-docker/blob/ae976883922f378f51f05c90a23a6a98d8c7e2cf/start.sh#L71

**Comment by bryanstaley** [comment]
As a hack to Dockerfile

`RUN sed -i -- 's/\$counter -lt 30/\$counter -lt $ES_CONNECT_RETRY/g' /usr/local/bin/start.sh
`

**Comment by spujadas** [comment]
That env var is a very good idea, I'll update the image to have 30 seconds by default, and make it overridable at runtime for cases when 30 isn't enough (I don't want to hardcode it to too high a value as I want the `start.sh` script to fail and exit fairly quickly if it can't start Elasticsearch at all).
