### ISSUE TITLE
using log-driver with the ssl-termination around logstash

### ISSUE THREAD

**Issue by fjoesne** [spujadas/elk-docker#9]
I'm trying to receive logs from a container running on a remote sever using the docker log-driver (syslog), however logstash does not seem to accept anything but ssl(correct?) 

I haven't found a way to make the docker log-driver to use ssl yet. Is there a simple way to disable the ssl requirement by logstash? In the near future i will probably utilize a VPN or tunnel of some sort anyway, I just need this to be open for now while testing and configuring.

**Comment by spujadas** [comment]
With the [lumberjack input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-lumberjack.html) that is configured in the image (in [01-lumberjack-input.conf](https://github.com/spujadas/elk-docker/blob/master/01-lumberjack-input.conf)), no, as the plugin requires SSL to be configured.

To solve your issue, you need to extend the sebp/elk image to add a configuration for an input plugin that can receive syslog events without requiring SSL:
- The [syslog input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html) is one option if you only need to receive syslog events and don't want SSL.
- The new [beats input plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html) is IMHO a better option if you can use [Filebeat](https://www.elastic.co/products/beats/filebeat) ("the next-generation Logstash Forwarder") on your remote server to collect and ship the logs to Logstash. You can configure Filebeat and the beats input plugin to use SSL or not, as you need. See the [documentation for the sebp/elk image](http://elk-docker.readthedocs.org/#forwarding-logs-filebeat) for more info on how to proceed.

**Comment by fjoesne** [comment]
I got it, thanks. :+1:

**Comment by spujadas** [comment]
np, you're welcome!
