### ISSUE TITLE
Issue on latest image: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]

### ISSUE THREAD

**Issue by fahadysf** [spujadas/elk-docker#92]
Launching the latest docker image fails with the error message:

Output from image console is: [pastebin-link with complete output]( https://nopaste.me/view/raw/4fd6717b)

Relevant error message:
`elk_1  | [2016-11-27T21:58:16,368][INFO ][o.e.b.BootstrapCheck     ] [jpehzFE] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks`
`elk_1  | [2016-11-27T21:58:16,369][ERROR][o.e.b.Bootstrap          ] [jpehzFE] node validation exception`
`elk_1  | bootstrap checks failed`
`elk_1  | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`

**Comment by fahadysf** [comment]
I googled up this [issue](https://github.com/docker-library/elasticsearch/issues/98) on the elasticsearch docker image issue list and the suggestion to use:
`sysctl -w vm.max_map_count=262144` 
on the host running the image resolves the problem. Is there any other/better way to do this?

**Comment by spujadas** [comment]
That's one way to do it, you can make the change permanent by editing the `/etc/sysctl.conf` file (see #79, #89, and http://elk-docker.readthedocs.io/#troubleshooting).

**Comment by x-itec** [comment]
Even if this value is corrent, ES5 won't start anymore in docker with same error here.

**Comment by spujadas** [comment]
@x-itec This issue has been pretty much solved for everyone by now, so shouldn't remain a problem: see http://elk-docker.readthedocs.io/#prerequisites for ways around this. If this doesn't solve it:

- Could you post a full output of how you set `vm.max_map_count` and started the container + output from the container? ("bla bla readonly error" isn't the usual error one gets when the parameter is set incorrectly)

- What are you running Docker on?

- Can you confirm that you have set `vm.max_map_count` on the host?

- If you `bash` into the container, has this value been taken into account? 

- Depending on your setup, have you tried setting the `MAX_MAP_COUNT` environment variable?

**Comment by nexusguy59** [comment]
Hello Guys,

I am getting similar behavior:

_root@cfELK:~# sysctl -w vm.max_map_count=262144 
sysctl: setting key "vm.max_map_count": Read-only file system_

I tried this and it did take but it still doesn't start with the new value
_vim /etc/sysctl/sysctl.conf_
and added this to the bottom of the file and rebooted the server
_vm.max_map_count = 262144_

So at this point not sure where to go with this, any help would be appreciated,
Thanks,
Michael

**Comment by spujadas** [comment]
@nexusguy59 

>	root@cfELK:~# sysctl -w vm.max_map_count=262144
>	sysctl: setting key "vm.max_map_count": Read-only file system

It seems that you're attempting to change the parameter in the container: you need to do it on the host running the container (and check that the value has actually been updated using `sysctl vm.max_map_count`).

**Comment by sunnyagain** [comment]
root@cfELK:~# sysctl -w vm.max_map_count=262144 Helped me, Many thanks

**Comment by nexusguy59** [comment]
On the host though correct?

On Oct 9, 2017 3:06 AM, "Sunny" <notifications@github.com> wrote:

root@cfELK:~# sysctl -w vm.max_map_count=262144 Helped me, Many thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/spujadas/elk-docker/issues/92#issuecomment-335079398>,
or mute the thread

**Comment by mikebrusilov** [comment]
@spujadas 

What if the host is windows? How do you change the parameter.

> root@cfELK:~# sysctl -w vm.max_map_count=262144
> sysctl: setting key "vm.max_map_count": Read-only file system
> It seems that you're attempting to change the parameter in the container: you need to do it on the host running the container (and check that the value has actually been updated using sysctl vm.max_map_count).

**Comment by spujadas** [comment]
@mikebrusilov haven't tested it but I assume that https://github.com/boot2docker/boot2docker/issues/1216 should do the trick. Let me know if it works out for you.
